# Generated by Django 6.0.3 on 2026-04-04 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_admin_and_barber_accounts(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    AdminAccount = apps.get_model("accounts", "AdminAccount")
    BarberAccount = apps.get_model("accounts", "BarberAccount")
    for u in User.objects.filter(role="ADMIN"):
        if AdminAccount.objects.filter(email__iexact=u.email).exists():
            continue
        AdminAccount.objects.create(
            email=u.email,
            password=u.password,
            is_active=u.is_active,
        )
        u.role = "USER"
        u.save(update_fields=["role"])
    for u in User.objects.filter(role__in=("BARBER_OWNER", "BARBER_STAFF")):
        BarberAccount.objects.get_or_create(user_id=u.pk)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_account_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(migrate_admin_and_barber_accounts, noop_reverse),
    ]
