# Generated by Django 6.0.3 on 2026-04-04 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_admin_barber_accounts'),
        ('barbers', '0004_barberprofile_barber_alter_barberprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberapplication',
            name='barber',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barber_application', to='barbers.barber'),
        ),
        migrations.AlterField(
            model_name='barberapplication',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barber_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User')], db_index=True, default='USER', max_length=20),
        ),
        migrations.DeleteModel(
            name='BarberAccount',
        ),
    ]
