# Generated by Django 6.0.3 on 2026-04-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_barberapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('ANDIJON', 'Andijon viloyati'), ('BUXORO', 'Buxoro viloyati'), ('FARGONA', "Farg'ona viloyati"), ('JIZZAX', 'Jizzax viloyati'), ('QASHQADARYO', 'Qashqadaryo viloyati'), ('NAVOIY', 'Navoiy viloyati'), ('NAMANGAN', 'Namangan viloyati'), ('SAMARQAND', 'Samarqand viloyati'), ('SURXONDARYO', 'Surxondaryo viloyati'), ('SIRDARYO', 'Sirdaryo viloyati'), ('TOSHKENT_SH', 'Toshkent shahri'), ('TOSHKENT_V', 'Toshkent viloyati'), ('XORAZM', 'Xorazm viloyati')], db_index=True, default='', max_length=32),
        ),
    ]
