# Generated by Django 6.0.3 on 2026-06-20 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='region',
            field=models.CharField(choices=[('ANDIJON', 'Andijon viloyati'), ('BUXORO', 'Buxoro viloyati'), ('FARGONA', "Farg'ona viloyati"), ('JIZZAX', 'Jizzax viloyati'), ('QASHQADARYO', 'Qashqadaryo viloyati'), ('NAVOIY', 'Navoiy viloyati'), ('NAMANGAN', 'Namangan viloyati'), ('SAMARQAND', 'Samarqand viloyati'), ('SURXONDARYO', 'Surxondaryo viloyati'), ('SIRDARYO', 'Sirdaryo viloyati'), ('TOSHKENT_SH', 'Toshkent shahri'), ('TOSHKENT_V', 'Toshkent viloyati'), ('XORAZM', 'Xorazm viloyati')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='LaunchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('ANDIJON', 'Andijon viloyati'), ('BUXORO', 'Buxoro viloyati'), ('FARGONA', "Farg'ona viloyati"), ('JIZZAX', 'Jizzax viloyati'), ('QASHQADARYO', 'Qashqadaryo viloyati'), ('NAVOIY', 'Navoiy viloyati'), ('NAMANGAN', 'Namangan viloyati'), ('SAMARQAND', 'Samarqand viloyati'), ('SURXONDARYO', 'Surxondaryo viloyati'), ('SIRDARYO', 'Sirdaryo viloyati'), ('TOSHKENT_SH', 'Toshkent shahri'), ('TOSHKENT_V', 'Toshkent viloyati'), ('XORAZM', 'Xorazm viloyati')], db_index=True, max_length=32)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city_label', models.CharField(blank=True, default='', max_length=128)),
                ('message', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('onboarding', 'Onboarding'), ('address', 'Manzil'), ('home', 'Bosh sahifa')], default='onboarding', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launch_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'region'), name='uniq_launch_interest_user_region')],
            },
        ),
    ]
