# Generated by Django 6.0.3 on 2026-06-20 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_launchinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('relation', models.CharField(choices=[('spouse', "Turmush o'rtog'i"), ('child', 'Farzand'), ('parent', 'Ota-ona'), ('sibling', 'Aka/uka'), ('other', 'Boshqa')], default='other', max_length=16)),
                ('audience', models.CharField(choices=[('men', 'Erkaklar'), ('women', 'Ayollar'), ('unisex', 'Hammasi')], default='unisex', max_length=16)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_jti', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('device_name', models.CharField(blank=True, default='', max_length=128)),
                ('platform', models.CharField(blank=True, default='', max_length=32)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
            },
        ),
    ]
