# Generated by Django 6.0.3 on 2026-03-31 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbers", "0001_initial"),
        ("bookings", "0001_initial"),
        ("salons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="salons.salon",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="salons.salon",
            ),
        ),
        migrations.AddField(
            model_name="bookingline",
            name="barber_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="barbers.barberservice",
            ),
        ),
    ]

