# Generated by Django 6.0.3 on 2026-04-04 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0004_barberprofile_barber_alter_barberprofile_user'),
        ('bookings', '0002_independent_barbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_bookings', to='barbers.barber'),
        ),
        migrations.AlterField(
            model_name='review',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_about', to='barbers.barber'),
        ),
    ]
