# Generated by Django 6.0.3 on 2026-06-20 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_family_sessions_email'),
        ('bookings', '0006_review_barber_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.familymember'),
        ),
    ]
