# Generated by Django 6.0.3 on 2026-07-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_client_impressions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientimpression',
            new_name='bookings_cl_custome_93d04d_idx',
            old_name='bookings_cl_custome_6f0b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewdimensionscore',
            new_name='bookings_re_target_d157c5_idx',
            old_name='bookings_re_target_2f0a3e_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('not_applicable', 'N/A'), ('pending', 'Pending'), ('held', 'Held in escrow'), ('paid', 'Paid'), ('refunded', 'Refunded')], db_index=True, default='not_applicable', max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewdimensionscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
