/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAylanmaRouteImport } from './routes/admin.aylanma'
import { Route as AdminBarbersRouteImport } from './routes/admin.barbers'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBroadcastRouteImport } from './routes/admin.broadcast'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminMorphAiRouteImport } from './routes/admin.morph-ai'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSalonsRouteImport } from './routes/admin.salons'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminStatisticsRouteImport } from './routes/admin.statistics'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminAylanmaIndexRouteImport } from './routes/admin.aylanma.index'
import { Route as AdminBarbersBarberIdRouteImport } from './routes/admin.barbers.$barberId'
import { Route as AdminBookingsBookingIdRouteImport } from './routes/admin.bookings.$bookingId'
import { Route as AdminFinanceIndexRouteImport } from './routes/admin.finance.index'
import { Route as AdminFinanceDepositsRouteImport } from './routes/admin.finance.deposits'
import { Route as AdminFinanceGiftsRouteImport } from './routes/admin.finance.gifts'
import { Route as AdminFinancePayoutsRouteImport } from './routes/admin.finance.payouts'
import { Route as AdminFinancePromotionsRouteImport } from './routes/admin.finance.promotions'
import { Route as AdminFinanceTransactionsRouteImport } from './routes/admin.finance.transactions'
import { Route as AdminMorphAiIndexRouteImport } from './routes/admin.morph-ai.index'
import { Route as AdminMorphAiBudgetRouteImport } from './routes/admin.morph-ai.budget'
import { Route as AdminMorphAiCatalogRouteImport } from './routes/admin.morph-ai.catalog'
import { Route as AdminMorphAiConversionRouteImport } from './routes/admin.morph-ai.conversion'
import { Route as AdminMorphAiErrorsRouteImport } from './routes/admin.morph-ai.errors'
import { Route as AdminMorphAiGalleryRouteImport } from './routes/admin.morph-ai.gallery'
import { Route as AdminMorphAiLimitsRouteImport } from './routes/admin.morph-ai.limits'
import { Route as AdminMorphAiPopularityRouteImport } from './routes/admin.morph-ai.popularity'
import { Route as AdminMorphAiQueueRouteImport } from './routes/admin.morph-ai.queue'
import { Route as AdminMorphAiSettingsRouteImport } from './routes/admin.morph-ai.settings'
import { Route as AdminSalonsSalonIdRouteImport } from './routes/admin.salons.$salonId'
import { Route as AdminServicesAnalyticsRouteImport } from './routes/admin.services.analytics'
import { Route as AdminStatisticsIndexRouteImport } from './routes/admin.statistics.index'
import { Route as AdminStatisticsBarbersRouteImport } from './routes/admin.statistics.barbers'
import { Route as AdminStatisticsBookingsRouteImport } from './routes/admin.statistics.bookings'
import { Route as AdminStatisticsLiveRouteImport } from './routes/admin.statistics.live'
import { Route as AdminStatisticsRevenueRouteImport } from './routes/admin.statistics.revenue'
import { Route as AdminStatisticsSalonsRouteImport } from './routes/admin.statistics.salons'
import { Route as AdminStatisticsUsersRouteImport } from './routes/admin.statistics.users'
import { Route as AdminStatisticsWalletRouteImport } from './routes/admin.statistics.wallet'
import { Route as AdminSubscriptionsSubIdRouteImport } from './routes/admin.subscriptions.$subId'
import { Route as AdminSupportTicketIdRouteImport } from './routes/admin.support.$ticketId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminUsersSignupsRouteImport } from './routes/admin.users.signups'
import { Route as AdminBarbersBarberIdIndexRouteImport } from './routes/admin.barbers.$barberId.index'
import { Route as AdminBarbersBarberIdBookingsRouteImport } from './routes/admin.barbers.$barberId.bookings'
import { Route as AdminBarbersBarberIdReviewsRouteImport } from './routes/admin.barbers.$barberId.reviews'
import { Route as AdminBarbersBarberIdStatsRouteImport } from './routes/admin.barbers.$barberId.stats'
import { Route as AdminMorphAiListKindRouteImport } from './routes/admin.morph-ai.list.$kind'
import { Route as AdminSalonsSalonIdIndexRouteImport } from './routes/admin.salons.$salonId.index'
import { Route as AdminSalonsSalonIdStatsRouteImport } from './routes/admin.salons.$salonId.stats'
import { Route as AdminSalonsSalonIdTeamRouteImport } from './routes/admin.salons.$salonId.team'
import { Route as AdminBarbersBarberIdStatsIndexRouteImport } from './routes/admin.barbers.$barberId.stats.index'
import { Route as AdminBarbersBarberIdStatsGraphsRouteImport } from './routes/admin.barbers.$barberId.stats.graphs'
import { Route as AdminSalonsSalonIdStatsIndexRouteImport } from './routes/admin.salons.$salonId.stats.index'
import { Route as AdminSalonsSalonIdStatsGraphsRouteImport } from './routes/admin.salons.$salonId.stats.graphs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAylanmaRoute = AdminAylanmaRouteImport.update({
  id: '/aylanma',
  path: '/aylanma',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBarbersRoute = AdminBarbersRouteImport.update({
  id: '/barbers',
  path: '/barbers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMorphAiRoute = AdminMorphAiRouteImport.update({
  id: '/morph-ai',
  path: '/morph-ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalonsRoute = AdminSalonsRouteImport.update({
  id: '/salons',
  path: '/salons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAylanmaIndexRoute = AdminAylanmaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAylanmaRoute,
} as any)
const AdminBarbersBarberIdRoute = AdminBarbersBarberIdRouteImport.update({
  id: '/$barberId',
  path: '/$barberId',
  getParentRoute: () => AdminBarbersRoute,
} as any)
const AdminBookingsBookingIdRoute = AdminBookingsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => AdminBookingsRoute,
} as any)
const AdminFinanceIndexRoute = AdminFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinanceDepositsRoute = AdminFinanceDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinanceGiftsRoute = AdminFinanceGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinancePayoutsRoute = AdminFinancePayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinancePromotionsRoute = AdminFinancePromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminFinanceTransactionsRoute =
  AdminFinanceTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AdminFinanceRoute,
  } as any)
const AdminMorphAiIndexRoute = AdminMorphAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMorphAiRoute,
} as any)
const AdminMorphAiBudgetRoute = AdminMorphAiBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AdminMorphAiRoute,
} as any)
const AdminMorphAiCatalogRoute = AdminMorphAiCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminMorphAiRoute,
} as any)
const AdminMorphAiConversionRoute = AdminMorphAiConversionRouteImport.update({
  id: '/conversion',
  path: '/conversion',
  getParentRoute: () => AdminMorphAiRoute,
} as any)
const AdminMorphAiErrorsRoute = AdminMorphAiErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AdminMorphAiRoute,
} as any)
const AdminMorphAiGalleryRoute = AdminMorphAiGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminMorphAiRoute,
} as any)
const AdminMorphAiLimitsRoute = AdminMorphAiLimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => AdminMorphAiRoute,
} as any)
const AdminMorphAiPopularityRoute = AdminMorphAiPopularityRouteImport.update({
  id: '/popularity',
  path: '/popularity',
  getParentRoute: () => AdminMorphAiRoute,
} as any)
const AdminMorphAiQueueRoute = AdminMorphAiQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminMorphAiRoute,
} as any)
const AdminMorphAiSettingsRoute = AdminMorphAiSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminMorphAiRoute,
} as any)
const AdminSalonsSalonIdRoute = AdminSalonsSalonIdRouteImport.update({
  id: '/$salonId',
  path: '/$salonId',
  getParentRoute: () => AdminSalonsRoute,
} as any)
const AdminServicesAnalyticsRoute = AdminServicesAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminServicesRoute,
} as any)
const AdminStatisticsIndexRoute = AdminStatisticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminStatisticsRoute,
} as any)
const AdminStatisticsBarbersRoute = AdminStatisticsBarbersRouteImport.update({
  id: '/barbers',
  path: '/barbers',
  getParentRoute: () => AdminStatisticsRoute,
} as any)
const AdminStatisticsBookingsRoute = AdminStatisticsBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminStatisticsRoute,
} as any)
const AdminStatisticsLiveRoute = AdminStatisticsLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminStatisticsRoute,
} as any)
const AdminStatisticsRevenueRoute = AdminStatisticsRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminStatisticsRoute,
} as any)
const AdminStatisticsSalonsRoute = AdminStatisticsSalonsRouteImport.update({
  id: '/salons',
  path: '/salons',
  getParentRoute: () => AdminStatisticsRoute,
} as any)
const AdminStatisticsUsersRoute = AdminStatisticsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminStatisticsRoute,
} as any)
const AdminStatisticsWalletRoute = AdminStatisticsWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminStatisticsRoute,
} as any)
const AdminSubscriptionsSubIdRoute = AdminSubscriptionsSubIdRouteImport.update({
  id: '/$subId',
  path: '/$subId',
  getParentRoute: () => AdminSubscriptionsRoute,
} as any)
const AdminSupportTicketIdRoute = AdminSupportTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AdminSupportRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersSignupsRoute = AdminUsersSignupsRouteImport.update({
  id: '/signups',
  path: '/signups',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminBarbersBarberIdIndexRoute =
  AdminBarbersBarberIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminBarbersBarberIdRoute,
  } as any)
const AdminBarbersBarberIdBookingsRoute =
  AdminBarbersBarberIdBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AdminBarbersBarberIdRoute,
  } as any)
const AdminBarbersBarberIdReviewsRoute =
  AdminBarbersBarberIdReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AdminBarbersBarberIdRoute,
  } as any)
const AdminBarbersBarberIdStatsRoute =
  AdminBarbersBarberIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AdminBarbersBarberIdRoute,
  } as any)
const AdminMorphAiListKindRoute = AdminMorphAiListKindRouteImport.update({
  id: '/list/$kind',
  path: '/list/$kind',
  getParentRoute: () => AdminMorphAiRoute,
} as any)
const AdminSalonsSalonIdIndexRoute = AdminSalonsSalonIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSalonsSalonIdRoute,
} as any)
const AdminSalonsSalonIdStatsRoute = AdminSalonsSalonIdStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminSalonsSalonIdRoute,
} as any)
const AdminSalonsSalonIdTeamRoute = AdminSalonsSalonIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminSalonsSalonIdRoute,
} as any)
const AdminBarbersBarberIdStatsIndexRoute =
  AdminBarbersBarberIdStatsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminBarbersBarberIdStatsRoute,
  } as any)
const AdminBarbersBarberIdStatsGraphsRoute =
  AdminBarbersBarberIdStatsGraphsRouteImport.update({
    id: '/graphs',
    path: '/graphs',
    getParentRoute: () => AdminBarbersBarberIdStatsRoute,
  } as any)
const AdminSalonsSalonIdStatsIndexRoute =
  AdminSalonsSalonIdStatsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSalonsSalonIdStatsRoute,
  } as any)
const AdminSalonsSalonIdStatsGraphsRoute =
  AdminSalonsSalonIdStatsGraphsRouteImport.update({
    id: '/graphs',
    path: '/graphs',
    getParentRoute: () => AdminSalonsSalonIdStatsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/aylanma': typeof AdminAylanmaRouteWithChildren
  '/admin/barbers': typeof AdminBarbersRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/map': typeof AdminMapRoute
  '/admin/morph-ai': typeof AdminMorphAiRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/salons': typeof AdminSalonsRouteWithChildren
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/statistics': typeof AdminStatisticsRouteWithChildren
  '/admin/subscriptions': typeof AdminSubscriptionsRouteWithChildren
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/barbers/$barberId': typeof AdminBarbersBarberIdRouteWithChildren
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/finance/deposits': typeof AdminFinanceDepositsRoute
  '/admin/finance/gifts': typeof AdminFinanceGiftsRoute
  '/admin/finance/payouts': typeof AdminFinancePayoutsRoute
  '/admin/finance/promotions': typeof AdminFinancePromotionsRoute
  '/admin/finance/transactions': typeof AdminFinanceTransactionsRoute
  '/admin/morph-ai/budget': typeof AdminMorphAiBudgetRoute
  '/admin/morph-ai/catalog': typeof AdminMorphAiCatalogRoute
  '/admin/morph-ai/conversion': typeof AdminMorphAiConversionRoute
  '/admin/morph-ai/errors': typeof AdminMorphAiErrorsRoute
  '/admin/morph-ai/gallery': typeof AdminMorphAiGalleryRoute
  '/admin/morph-ai/limits': typeof AdminMorphAiLimitsRoute
  '/admin/morph-ai/popularity': typeof AdminMorphAiPopularityRoute
  '/admin/morph-ai/queue': typeof AdminMorphAiQueueRoute
  '/admin/morph-ai/settings': typeof AdminMorphAiSettingsRoute
  '/admin/salons/$salonId': typeof AdminSalonsSalonIdRouteWithChildren
  '/admin/services/analytics': typeof AdminServicesAnalyticsRoute
  '/admin/statistics/barbers': typeof AdminStatisticsBarbersRoute
  '/admin/statistics/bookings': typeof AdminStatisticsBookingsRoute
  '/admin/statistics/live': typeof AdminStatisticsLiveRoute
  '/admin/statistics/revenue': typeof AdminStatisticsRevenueRoute
  '/admin/statistics/salons': typeof AdminStatisticsSalonsRoute
  '/admin/statistics/users': typeof AdminStatisticsUsersRoute
  '/admin/statistics/wallet': typeof AdminStatisticsWalletRoute
  '/admin/subscriptions/$subId': typeof AdminSubscriptionsSubIdRoute
  '/admin/support/$ticketId': typeof AdminSupportTicketIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/signups': typeof AdminUsersSignupsRoute
  '/admin/aylanma/': typeof AdminAylanmaIndexRoute
  '/admin/finance/': typeof AdminFinanceIndexRoute
  '/admin/morph-ai/': typeof AdminMorphAiIndexRoute
  '/admin/statistics/': typeof AdminStatisticsIndexRoute
  '/admin/barbers/$barberId/bookings': typeof AdminBarbersBarberIdBookingsRoute
  '/admin/barbers/$barberId/reviews': typeof AdminBarbersBarberIdReviewsRoute
  '/admin/barbers/$barberId/stats': typeof AdminBarbersBarberIdStatsRouteWithChildren
  '/admin/morph-ai/list/$kind': typeof AdminMorphAiListKindRoute
  '/admin/salons/$salonId/stats': typeof AdminSalonsSalonIdStatsRouteWithChildren
  '/admin/salons/$salonId/team': typeof AdminSalonsSalonIdTeamRoute
  '/admin/barbers/$barberId/': typeof AdminBarbersBarberIdIndexRoute
  '/admin/salons/$salonId/': typeof AdminSalonsSalonIdIndexRoute
  '/admin/barbers/$barberId/stats/graphs': typeof AdminBarbersBarberIdStatsGraphsRoute
  '/admin/salons/$salonId/stats/graphs': typeof AdminSalonsSalonIdStatsGraphsRoute
  '/admin/barbers/$barberId/stats/': typeof AdminBarbersBarberIdStatsIndexRoute
  '/admin/salons/$salonId/stats/': typeof AdminSalonsSalonIdStatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/barbers': typeof AdminBarbersRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/salons': typeof AdminSalonsRouteWithChildren
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/subscriptions': typeof AdminSubscriptionsRouteWithChildren
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/finance/deposits': typeof AdminFinanceDepositsRoute
  '/admin/finance/gifts': typeof AdminFinanceGiftsRoute
  '/admin/finance/payouts': typeof AdminFinancePayoutsRoute
  '/admin/finance/promotions': typeof AdminFinancePromotionsRoute
  '/admin/finance/transactions': typeof AdminFinanceTransactionsRoute
  '/admin/morph-ai/budget': typeof AdminMorphAiBudgetRoute
  '/admin/morph-ai/catalog': typeof AdminMorphAiCatalogRoute
  '/admin/morph-ai/conversion': typeof AdminMorphAiConversionRoute
  '/admin/morph-ai/errors': typeof AdminMorphAiErrorsRoute
  '/admin/morph-ai/gallery': typeof AdminMorphAiGalleryRoute
  '/admin/morph-ai/limits': typeof AdminMorphAiLimitsRoute
  '/admin/morph-ai/popularity': typeof AdminMorphAiPopularityRoute
  '/admin/morph-ai/queue': typeof AdminMorphAiQueueRoute
  '/admin/morph-ai/settings': typeof AdminMorphAiSettingsRoute
  '/admin/services/analytics': typeof AdminServicesAnalyticsRoute
  '/admin/statistics/barbers': typeof AdminStatisticsBarbersRoute
  '/admin/statistics/bookings': typeof AdminStatisticsBookingsRoute
  '/admin/statistics/live': typeof AdminStatisticsLiveRoute
  '/admin/statistics/revenue': typeof AdminStatisticsRevenueRoute
  '/admin/statistics/salons': typeof AdminStatisticsSalonsRoute
  '/admin/statistics/users': typeof AdminStatisticsUsersRoute
  '/admin/statistics/wallet': typeof AdminStatisticsWalletRoute
  '/admin/subscriptions/$subId': typeof AdminSubscriptionsSubIdRoute
  '/admin/support/$ticketId': typeof AdminSupportTicketIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/signups': typeof AdminUsersSignupsRoute
  '/admin/aylanma': typeof AdminAylanmaIndexRoute
  '/admin/finance': typeof AdminFinanceIndexRoute
  '/admin/morph-ai': typeof AdminMorphAiIndexRoute
  '/admin/statistics': typeof AdminStatisticsIndexRoute
  '/admin/barbers/$barberId/bookings': typeof AdminBarbersBarberIdBookingsRoute
  '/admin/barbers/$barberId/reviews': typeof AdminBarbersBarberIdReviewsRoute
  '/admin/morph-ai/list/$kind': typeof AdminMorphAiListKindRoute
  '/admin/salons/$salonId/team': typeof AdminSalonsSalonIdTeamRoute
  '/admin/barbers/$barberId': typeof AdminBarbersBarberIdIndexRoute
  '/admin/salons/$salonId': typeof AdminSalonsSalonIdIndexRoute
  '/admin/barbers/$barberId/stats/graphs': typeof AdminBarbersBarberIdStatsGraphsRoute
  '/admin/salons/$salonId/stats/graphs': typeof AdminSalonsSalonIdStatsGraphsRoute
  '/admin/barbers/$barberId/stats': typeof AdminBarbersBarberIdStatsIndexRoute
  '/admin/salons/$salonId/stats': typeof AdminSalonsSalonIdStatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/aylanma': typeof AdminAylanmaRouteWithChildren
  '/admin/barbers': typeof AdminBarbersRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/map': typeof AdminMapRoute
  '/admin/morph-ai': typeof AdminMorphAiRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/salons': typeof AdminSalonsRouteWithChildren
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/statistics': typeof AdminStatisticsRouteWithChildren
  '/admin/subscriptions': typeof AdminSubscriptionsRouteWithChildren
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/barbers/$barberId': typeof AdminBarbersBarberIdRouteWithChildren
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/finance/deposits': typeof AdminFinanceDepositsRoute
  '/admin/finance/gifts': typeof AdminFinanceGiftsRoute
  '/admin/finance/payouts': typeof AdminFinancePayoutsRoute
  '/admin/finance/promotions': typeof AdminFinancePromotionsRoute
  '/admin/finance/transactions': typeof AdminFinanceTransactionsRoute
  '/admin/morph-ai/budget': typeof AdminMorphAiBudgetRoute
  '/admin/morph-ai/catalog': typeof AdminMorphAiCatalogRoute
  '/admin/morph-ai/conversion': typeof AdminMorphAiConversionRoute
  '/admin/morph-ai/errors': typeof AdminMorphAiErrorsRoute
  '/admin/morph-ai/gallery': typeof AdminMorphAiGalleryRoute
  '/admin/morph-ai/limits': typeof AdminMorphAiLimitsRoute
  '/admin/morph-ai/popularity': typeof AdminMorphAiPopularityRoute
  '/admin/morph-ai/queue': typeof AdminMorphAiQueueRoute
  '/admin/morph-ai/settings': typeof AdminMorphAiSettingsRoute
  '/admin/salons/$salonId': typeof AdminSalonsSalonIdRouteWithChildren
  '/admin/services/analytics': typeof AdminServicesAnalyticsRoute
  '/admin/statistics/barbers': typeof AdminStatisticsBarbersRoute
  '/admin/statistics/bookings': typeof AdminStatisticsBookingsRoute
  '/admin/statistics/live': typeof AdminStatisticsLiveRoute
  '/admin/statistics/revenue': typeof AdminStatisticsRevenueRoute
  '/admin/statistics/salons': typeof AdminStatisticsSalonsRoute
  '/admin/statistics/users': typeof AdminStatisticsUsersRoute
  '/admin/statistics/wallet': typeof AdminStatisticsWalletRoute
  '/admin/subscriptions/$subId': typeof AdminSubscriptionsSubIdRoute
  '/admin/support/$ticketId': typeof AdminSupportTicketIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/signups': typeof AdminUsersSignupsRoute
  '/admin/aylanma/': typeof AdminAylanmaIndexRoute
  '/admin/finance/': typeof AdminFinanceIndexRoute
  '/admin/morph-ai/': typeof AdminMorphAiIndexRoute
  '/admin/statistics/': typeof AdminStatisticsIndexRoute
  '/admin/barbers/$barberId/bookings': typeof AdminBarbersBarberIdBookingsRoute
  '/admin/barbers/$barberId/reviews': typeof AdminBarbersBarberIdReviewsRoute
  '/admin/barbers/$barberId/stats': typeof AdminBarbersBarberIdStatsRouteWithChildren
  '/admin/morph-ai/list/$kind': typeof AdminMorphAiListKindRoute
  '/admin/salons/$salonId/stats': typeof AdminSalonsSalonIdStatsRouteWithChildren
  '/admin/salons/$salonId/team': typeof AdminSalonsSalonIdTeamRoute
  '/admin/barbers/$barberId/': typeof AdminBarbersBarberIdIndexRoute
  '/admin/salons/$salonId/': typeof AdminSalonsSalonIdIndexRoute
  '/admin/barbers/$barberId/stats/graphs': typeof AdminBarbersBarberIdStatsGraphsRoute
  '/admin/salons/$salonId/stats/graphs': typeof AdminSalonsSalonIdStatsGraphsRoute
  '/admin/barbers/$barberId/stats/': typeof AdminBarbersBarberIdStatsIndexRoute
  '/admin/salons/$salonId/stats/': typeof AdminSalonsSalonIdStatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/admins'
    | '/admin/audit'
    | '/admin/aylanma'
    | '/admin/barbers'
    | '/admin/bookings'
    | '/admin/broadcast'
    | '/admin/categories'
    | '/admin/finance'
    | '/admin/map'
    | '/admin/morph-ai'
    | '/admin/profile'
    | '/admin/reviews'
    | '/admin/salons'
    | '/admin/services'
    | '/admin/statistics'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/users'
    | '/admin/'
    | '/admin/barbers/$barberId'
    | '/admin/bookings/$bookingId'
    | '/admin/finance/deposits'
    | '/admin/finance/gifts'
    | '/admin/finance/payouts'
    | '/admin/finance/promotions'
    | '/admin/finance/transactions'
    | '/admin/morph-ai/budget'
    | '/admin/morph-ai/catalog'
    | '/admin/morph-ai/conversion'
    | '/admin/morph-ai/errors'
    | '/admin/morph-ai/gallery'
    | '/admin/morph-ai/limits'
    | '/admin/morph-ai/popularity'
    | '/admin/morph-ai/queue'
    | '/admin/morph-ai/settings'
    | '/admin/salons/$salonId'
    | '/admin/services/analytics'
    | '/admin/statistics/barbers'
    | '/admin/statistics/bookings'
    | '/admin/statistics/live'
    | '/admin/statistics/revenue'
    | '/admin/statistics/salons'
    | '/admin/statistics/users'
    | '/admin/statistics/wallet'
    | '/admin/subscriptions/$subId'
    | '/admin/support/$ticketId'
    | '/admin/users/$userId'
    | '/admin/users/signups'
    | '/admin/aylanma/'
    | '/admin/finance/'
    | '/admin/morph-ai/'
    | '/admin/statistics/'
    | '/admin/barbers/$barberId/bookings'
    | '/admin/barbers/$barberId/reviews'
    | '/admin/barbers/$barberId/stats'
    | '/admin/morph-ai/list/$kind'
    | '/admin/salons/$salonId/stats'
    | '/admin/salons/$salonId/team'
    | '/admin/barbers/$barberId/'
    | '/admin/salons/$salonId/'
    | '/admin/barbers/$barberId/stats/graphs'
    | '/admin/salons/$salonId/stats/graphs'
    | '/admin/barbers/$barberId/stats/'
    | '/admin/salons/$salonId/stats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/admins'
    | '/admin/audit'
    | '/admin/barbers'
    | '/admin/bookings'
    | '/admin/broadcast'
    | '/admin/categories'
    | '/admin/map'
    | '/admin/profile'
    | '/admin/reviews'
    | '/admin/salons'
    | '/admin/services'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/users'
    | '/admin'
    | '/admin/bookings/$bookingId'
    | '/admin/finance/deposits'
    | '/admin/finance/gifts'
    | '/admin/finance/payouts'
    | '/admin/finance/promotions'
    | '/admin/finance/transactions'
    | '/admin/morph-ai/budget'
    | '/admin/morph-ai/catalog'
    | '/admin/morph-ai/conversion'
    | '/admin/morph-ai/errors'
    | '/admin/morph-ai/gallery'
    | '/admin/morph-ai/limits'
    | '/admin/morph-ai/popularity'
    | '/admin/morph-ai/queue'
    | '/admin/morph-ai/settings'
    | '/admin/services/analytics'
    | '/admin/statistics/barbers'
    | '/admin/statistics/bookings'
    | '/admin/statistics/live'
    | '/admin/statistics/revenue'
    | '/admin/statistics/salons'
    | '/admin/statistics/users'
    | '/admin/statistics/wallet'
    | '/admin/subscriptions/$subId'
    | '/admin/support/$ticketId'
    | '/admin/users/$userId'
    | '/admin/users/signups'
    | '/admin/aylanma'
    | '/admin/finance'
    | '/admin/morph-ai'
    | '/admin/statistics'
    | '/admin/barbers/$barberId/bookings'
    | '/admin/barbers/$barberId/reviews'
    | '/admin/morph-ai/list/$kind'
    | '/admin/salons/$salonId/team'
    | '/admin/barbers/$barberId'
    | '/admin/salons/$salonId'
    | '/admin/barbers/$barberId/stats/graphs'
    | '/admin/salons/$salonId/stats/graphs'
    | '/admin/barbers/$barberId/stats'
    | '/admin/salons/$salonId/stats'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/admins'
    | '/admin/audit'
    | '/admin/aylanma'
    | '/admin/barbers'
    | '/admin/bookings'
    | '/admin/broadcast'
    | '/admin/categories'
    | '/admin/finance'
    | '/admin/map'
    | '/admin/morph-ai'
    | '/admin/profile'
    | '/admin/reviews'
    | '/admin/salons'
    | '/admin/services'
    | '/admin/statistics'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/users'
    | '/admin/'
    | '/admin/barbers/$barberId'
    | '/admin/bookings/$bookingId'
    | '/admin/finance/deposits'
    | '/admin/finance/gifts'
    | '/admin/finance/payouts'
    | '/admin/finance/promotions'
    | '/admin/finance/transactions'
    | '/admin/morph-ai/budget'
    | '/admin/morph-ai/catalog'
    | '/admin/morph-ai/conversion'
    | '/admin/morph-ai/errors'
    | '/admin/morph-ai/gallery'
    | '/admin/morph-ai/limits'
    | '/admin/morph-ai/popularity'
    | '/admin/morph-ai/queue'
    | '/admin/morph-ai/settings'
    | '/admin/salons/$salonId'
    | '/admin/services/analytics'
    | '/admin/statistics/barbers'
    | '/admin/statistics/bookings'
    | '/admin/statistics/live'
    | '/admin/statistics/revenue'
    | '/admin/statistics/salons'
    | '/admin/statistics/users'
    | '/admin/statistics/wallet'
    | '/admin/subscriptions/$subId'
    | '/admin/support/$ticketId'
    | '/admin/users/$userId'
    | '/admin/users/signups'
    | '/admin/aylanma/'
    | '/admin/finance/'
    | '/admin/morph-ai/'
    | '/admin/statistics/'
    | '/admin/barbers/$barberId/bookings'
    | '/admin/barbers/$barberId/reviews'
    | '/admin/barbers/$barberId/stats'
    | '/admin/morph-ai/list/$kind'
    | '/admin/salons/$salonId/stats'
    | '/admin/salons/$salonId/team'
    | '/admin/barbers/$barberId/'
    | '/admin/salons/$salonId/'
    | '/admin/barbers/$barberId/stats/graphs'
    | '/admin/salons/$salonId/stats/graphs'
    | '/admin/barbers/$barberId/stats/'
    | '/admin/salons/$salonId/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/aylanma': {
      id: '/admin/aylanma'
      path: '/aylanma'
      fullPath: '/admin/aylanma'
      preLoaderRoute: typeof AdminAylanmaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/barbers': {
      id: '/admin/barbers'
      path: '/barbers'
      fullPath: '/admin/barbers'
      preLoaderRoute: typeof AdminBarbersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/morph-ai': {
      id: '/admin/morph-ai'
      path: '/morph-ai'
      fullPath: '/admin/morph-ai'
      preLoaderRoute: typeof AdminMorphAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/salons': {
      id: '/admin/salons'
      path: '/salons'
      fullPath: '/admin/salons'
      preLoaderRoute: typeof AdminSalonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/aylanma/': {
      id: '/admin/aylanma/'
      path: '/'
      fullPath: '/admin/aylanma/'
      preLoaderRoute: typeof AdminAylanmaIndexRouteImport
      parentRoute: typeof AdminAylanmaRoute
    }
    '/admin/barbers/$barberId': {
      id: '/admin/barbers/$barberId'
      path: '/$barberId'
      fullPath: '/admin/barbers/$barberId'
      preLoaderRoute: typeof AdminBarbersBarberIdRouteImport
      parentRoute: typeof AdminBarbersRoute
    }
    '/admin/bookings/$bookingId': {
      id: '/admin/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/admin/bookings/$bookingId'
      preLoaderRoute: typeof AdminBookingsBookingIdRouteImport
      parentRoute: typeof AdminBookingsRoute
    }
    '/admin/finance/': {
      id: '/admin/finance/'
      path: '/'
      fullPath: '/admin/finance/'
      preLoaderRoute: typeof AdminFinanceIndexRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/deposits': {
      id: '/admin/finance/deposits'
      path: '/deposits'
      fullPath: '/admin/finance/deposits'
      preLoaderRoute: typeof AdminFinanceDepositsRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/gifts': {
      id: '/admin/finance/gifts'
      path: '/gifts'
      fullPath: '/admin/finance/gifts'
      preLoaderRoute: typeof AdminFinanceGiftsRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/payouts': {
      id: '/admin/finance/payouts'
      path: '/payouts'
      fullPath: '/admin/finance/payouts'
      preLoaderRoute: typeof AdminFinancePayoutsRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/promotions': {
      id: '/admin/finance/promotions'
      path: '/promotions'
      fullPath: '/admin/finance/promotions'
      preLoaderRoute: typeof AdminFinancePromotionsRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/finance/transactions': {
      id: '/admin/finance/transactions'
      path: '/transactions'
      fullPath: '/admin/finance/transactions'
      preLoaderRoute: typeof AdminFinanceTransactionsRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/morph-ai/': {
      id: '/admin/morph-ai/'
      path: '/'
      fullPath: '/admin/morph-ai/'
      preLoaderRoute: typeof AdminMorphAiIndexRouteImport
      parentRoute: typeof AdminMorphAiRoute
    }
    '/admin/morph-ai/budget': {
      id: '/admin/morph-ai/budget'
      path: '/budget'
      fullPath: '/admin/morph-ai/budget'
      preLoaderRoute: typeof AdminMorphAiBudgetRouteImport
      parentRoute: typeof AdminMorphAiRoute
    }
    '/admin/morph-ai/catalog': {
      id: '/admin/morph-ai/catalog'
      path: '/catalog'
      fullPath: '/admin/morph-ai/catalog'
      preLoaderRoute: typeof AdminMorphAiCatalogRouteImport
      parentRoute: typeof AdminMorphAiRoute
    }
    '/admin/morph-ai/conversion': {
      id: '/admin/morph-ai/conversion'
      path: '/conversion'
      fullPath: '/admin/morph-ai/conversion'
      preLoaderRoute: typeof AdminMorphAiConversionRouteImport
      parentRoute: typeof AdminMorphAiRoute
    }
    '/admin/morph-ai/errors': {
      id: '/admin/morph-ai/errors'
      path: '/errors'
      fullPath: '/admin/morph-ai/errors'
      preLoaderRoute: typeof AdminMorphAiErrorsRouteImport
      parentRoute: typeof AdminMorphAiRoute
    }
    '/admin/morph-ai/gallery': {
      id: '/admin/morph-ai/gallery'
      path: '/gallery'
      fullPath: '/admin/morph-ai/gallery'
      preLoaderRoute: typeof AdminMorphAiGalleryRouteImport
      parentRoute: typeof AdminMorphAiRoute
    }
    '/admin/morph-ai/limits': {
      id: '/admin/morph-ai/limits'
      path: '/limits'
      fullPath: '/admin/morph-ai/limits'
      preLoaderRoute: typeof AdminMorphAiLimitsRouteImport
      parentRoute: typeof AdminMorphAiRoute
    }
    '/admin/morph-ai/popularity': {
      id: '/admin/morph-ai/popularity'
      path: '/popularity'
      fullPath: '/admin/morph-ai/popularity'
      preLoaderRoute: typeof AdminMorphAiPopularityRouteImport
      parentRoute: typeof AdminMorphAiRoute
    }
    '/admin/morph-ai/queue': {
      id: '/admin/morph-ai/queue'
      path: '/queue'
      fullPath: '/admin/morph-ai/queue'
      preLoaderRoute: typeof AdminMorphAiQueueRouteImport
      parentRoute: typeof AdminMorphAiRoute
    }
    '/admin/morph-ai/settings': {
      id: '/admin/morph-ai/settings'
      path: '/settings'
      fullPath: '/admin/morph-ai/settings'
      preLoaderRoute: typeof AdminMorphAiSettingsRouteImport
      parentRoute: typeof AdminMorphAiRoute
    }
    '/admin/salons/$salonId': {
      id: '/admin/salons/$salonId'
      path: '/$salonId'
      fullPath: '/admin/salons/$salonId'
      preLoaderRoute: typeof AdminSalonsSalonIdRouteImport
      parentRoute: typeof AdminSalonsRoute
    }
    '/admin/services/analytics': {
      id: '/admin/services/analytics'
      path: '/analytics'
      fullPath: '/admin/services/analytics'
      preLoaderRoute: typeof AdminServicesAnalyticsRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/admin/statistics/': {
      id: '/admin/statistics/'
      path: '/'
      fullPath: '/admin/statistics/'
      preLoaderRoute: typeof AdminStatisticsIndexRouteImport
      parentRoute: typeof AdminStatisticsRoute
    }
    '/admin/statistics/barbers': {
      id: '/admin/statistics/barbers'
      path: '/barbers'
      fullPath: '/admin/statistics/barbers'
      preLoaderRoute: typeof AdminStatisticsBarbersRouteImport
      parentRoute: typeof AdminStatisticsRoute
    }
    '/admin/statistics/bookings': {
      id: '/admin/statistics/bookings'
      path: '/bookings'
      fullPath: '/admin/statistics/bookings'
      preLoaderRoute: typeof AdminStatisticsBookingsRouteImport
      parentRoute: typeof AdminStatisticsRoute
    }
    '/admin/statistics/live': {
      id: '/admin/statistics/live'
      path: '/live'
      fullPath: '/admin/statistics/live'
      preLoaderRoute: typeof AdminStatisticsLiveRouteImport
      parentRoute: typeof AdminStatisticsRoute
    }
    '/admin/statistics/revenue': {
      id: '/admin/statistics/revenue'
      path: '/revenue'
      fullPath: '/admin/statistics/revenue'
      preLoaderRoute: typeof AdminStatisticsRevenueRouteImport
      parentRoute: typeof AdminStatisticsRoute
    }
    '/admin/statistics/salons': {
      id: '/admin/statistics/salons'
      path: '/salons'
      fullPath: '/admin/statistics/salons'
      preLoaderRoute: typeof AdminStatisticsSalonsRouteImport
      parentRoute: typeof AdminStatisticsRoute
    }
    '/admin/statistics/users': {
      id: '/admin/statistics/users'
      path: '/users'
      fullPath: '/admin/statistics/users'
      preLoaderRoute: typeof AdminStatisticsUsersRouteImport
      parentRoute: typeof AdminStatisticsRoute
    }
    '/admin/statistics/wallet': {
      id: '/admin/statistics/wallet'
      path: '/wallet'
      fullPath: '/admin/statistics/wallet'
      preLoaderRoute: typeof AdminStatisticsWalletRouteImport
      parentRoute: typeof AdminStatisticsRoute
    }
    '/admin/subscriptions/$subId': {
      id: '/admin/subscriptions/$subId'
      path: '/$subId'
      fullPath: '/admin/subscriptions/$subId'
      preLoaderRoute: typeof AdminSubscriptionsSubIdRouteImport
      parentRoute: typeof AdminSubscriptionsRoute
    }
    '/admin/support/$ticketId': {
      id: '/admin/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/admin/support/$ticketId'
      preLoaderRoute: typeof AdminSupportTicketIdRouteImport
      parentRoute: typeof AdminSupportRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/signups': {
      id: '/admin/users/signups'
      path: '/signups'
      fullPath: '/admin/users/signups'
      preLoaderRoute: typeof AdminUsersSignupsRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/barbers/$barberId/': {
      id: '/admin/barbers/$barberId/'
      path: '/'
      fullPath: '/admin/barbers/$barberId/'
      preLoaderRoute: typeof AdminBarbersBarberIdIndexRouteImport
      parentRoute: typeof AdminBarbersBarberIdRoute
    }
    '/admin/barbers/$barberId/bookings': {
      id: '/admin/barbers/$barberId/bookings'
      path: '/bookings'
      fullPath: '/admin/barbers/$barberId/bookings'
      preLoaderRoute: typeof AdminBarbersBarberIdBookingsRouteImport
      parentRoute: typeof AdminBarbersBarberIdRoute
    }
    '/admin/barbers/$barberId/reviews': {
      id: '/admin/barbers/$barberId/reviews'
      path: '/reviews'
      fullPath: '/admin/barbers/$barberId/reviews'
      preLoaderRoute: typeof AdminBarbersBarberIdReviewsRouteImport
      parentRoute: typeof AdminBarbersBarberIdRoute
    }
    '/admin/barbers/$barberId/stats': {
      id: '/admin/barbers/$barberId/stats'
      path: '/stats'
      fullPath: '/admin/barbers/$barberId/stats'
      preLoaderRoute: typeof AdminBarbersBarberIdStatsRouteImport
      parentRoute: typeof AdminBarbersBarberIdRoute
    }
    '/admin/morph-ai/list/$kind': {
      id: '/admin/morph-ai/list/$kind'
      path: '/list/$kind'
      fullPath: '/admin/morph-ai/list/$kind'
      preLoaderRoute: typeof AdminMorphAiListKindRouteImport
      parentRoute: typeof AdminMorphAiRoute
    }
    '/admin/salons/$salonId/': {
      id: '/admin/salons/$salonId/'
      path: '/'
      fullPath: '/admin/salons/$salonId/'
      preLoaderRoute: typeof AdminSalonsSalonIdIndexRouteImport
      parentRoute: typeof AdminSalonsSalonIdRoute
    }
    '/admin/salons/$salonId/stats': {
      id: '/admin/salons/$salonId/stats'
      path: '/stats'
      fullPath: '/admin/salons/$salonId/stats'
      preLoaderRoute: typeof AdminSalonsSalonIdStatsRouteImport
      parentRoute: typeof AdminSalonsSalonIdRoute
    }
    '/admin/salons/$salonId/team': {
      id: '/admin/salons/$salonId/team'
      path: '/team'
      fullPath: '/admin/salons/$salonId/team'
      preLoaderRoute: typeof AdminSalonsSalonIdTeamRouteImport
      parentRoute: typeof AdminSalonsSalonIdRoute
    }
    '/admin/barbers/$barberId/stats/': {
      id: '/admin/barbers/$barberId/stats/'
      path: '/'
      fullPath: '/admin/barbers/$barberId/stats/'
      preLoaderRoute: typeof AdminBarbersBarberIdStatsIndexRouteImport
      parentRoute: typeof AdminBarbersBarberIdStatsRoute
    }
    '/admin/barbers/$barberId/stats/graphs': {
      id: '/admin/barbers/$barberId/stats/graphs'
      path: '/graphs'
      fullPath: '/admin/barbers/$barberId/stats/graphs'
      preLoaderRoute: typeof AdminBarbersBarberIdStatsGraphsRouteImport
      parentRoute: typeof AdminBarbersBarberIdStatsRoute
    }
    '/admin/salons/$salonId/stats/': {
      id: '/admin/salons/$salonId/stats/'
      path: '/'
      fullPath: '/admin/salons/$salonId/stats/'
      preLoaderRoute: typeof AdminSalonsSalonIdStatsIndexRouteImport
      parentRoute: typeof AdminSalonsSalonIdStatsRoute
    }
    '/admin/salons/$salonId/stats/graphs': {
      id: '/admin/salons/$salonId/stats/graphs'
      path: '/graphs'
      fullPath: '/admin/salons/$salonId/stats/graphs'
      preLoaderRoute: typeof AdminSalonsSalonIdStatsGraphsRouteImport
      parentRoute: typeof AdminSalonsSalonIdStatsRoute
    }
  }
}

interface AdminAylanmaRouteChildren {
  AdminAylanmaIndexRoute: typeof AdminAylanmaIndexRoute
}

const AdminAylanmaRouteChildren: AdminAylanmaRouteChildren = {
  AdminAylanmaIndexRoute: AdminAylanmaIndexRoute,
}

const AdminAylanmaRouteWithChildren = AdminAylanmaRoute._addFileChildren(
  AdminAylanmaRouteChildren,
)

interface AdminBarbersBarberIdStatsRouteChildren {
  AdminBarbersBarberIdStatsGraphsRoute: typeof AdminBarbersBarberIdStatsGraphsRoute
  AdminBarbersBarberIdStatsIndexRoute: typeof AdminBarbersBarberIdStatsIndexRoute
}

const AdminBarbersBarberIdStatsRouteChildren: AdminBarbersBarberIdStatsRouteChildren =
  {
    AdminBarbersBarberIdStatsGraphsRoute: AdminBarbersBarberIdStatsGraphsRoute,
    AdminBarbersBarberIdStatsIndexRoute: AdminBarbersBarberIdStatsIndexRoute,
  }

const AdminBarbersBarberIdStatsRouteWithChildren =
  AdminBarbersBarberIdStatsRoute._addFileChildren(
    AdminBarbersBarberIdStatsRouteChildren,
  )

interface AdminBarbersBarberIdRouteChildren {
  AdminBarbersBarberIdBookingsRoute: typeof AdminBarbersBarberIdBookingsRoute
  AdminBarbersBarberIdReviewsRoute: typeof AdminBarbersBarberIdReviewsRoute
  AdminBarbersBarberIdStatsRoute: typeof AdminBarbersBarberIdStatsRouteWithChildren
  AdminBarbersBarberIdIndexRoute: typeof AdminBarbersBarberIdIndexRoute
}

const AdminBarbersBarberIdRouteChildren: AdminBarbersBarberIdRouteChildren = {
  AdminBarbersBarberIdBookingsRoute: AdminBarbersBarberIdBookingsRoute,
  AdminBarbersBarberIdReviewsRoute: AdminBarbersBarberIdReviewsRoute,
  AdminBarbersBarberIdStatsRoute: AdminBarbersBarberIdStatsRouteWithChildren,
  AdminBarbersBarberIdIndexRoute: AdminBarbersBarberIdIndexRoute,
}

const AdminBarbersBarberIdRouteWithChildren =
  AdminBarbersBarberIdRoute._addFileChildren(AdminBarbersBarberIdRouteChildren)

interface AdminBarbersRouteChildren {
  AdminBarbersBarberIdRoute: typeof AdminBarbersBarberIdRouteWithChildren
}

const AdminBarbersRouteChildren: AdminBarbersRouteChildren = {
  AdminBarbersBarberIdRoute: AdminBarbersBarberIdRouteWithChildren,
}

const AdminBarbersRouteWithChildren = AdminBarbersRoute._addFileChildren(
  AdminBarbersRouteChildren,
)

interface AdminBookingsRouteChildren {
  AdminBookingsBookingIdRoute: typeof AdminBookingsBookingIdRoute
}

const AdminBookingsRouteChildren: AdminBookingsRouteChildren = {
  AdminBookingsBookingIdRoute: AdminBookingsBookingIdRoute,
}

const AdminBookingsRouteWithChildren = AdminBookingsRoute._addFileChildren(
  AdminBookingsRouteChildren,
)

interface AdminFinanceRouteChildren {
  AdminFinanceDepositsRoute: typeof AdminFinanceDepositsRoute
  AdminFinanceGiftsRoute: typeof AdminFinanceGiftsRoute
  AdminFinancePayoutsRoute: typeof AdminFinancePayoutsRoute
  AdminFinancePromotionsRoute: typeof AdminFinancePromotionsRoute
  AdminFinanceTransactionsRoute: typeof AdminFinanceTransactionsRoute
  AdminFinanceIndexRoute: typeof AdminFinanceIndexRoute
}

const AdminFinanceRouteChildren: AdminFinanceRouteChildren = {
  AdminFinanceDepositsRoute: AdminFinanceDepositsRoute,
  AdminFinanceGiftsRoute: AdminFinanceGiftsRoute,
  AdminFinancePayoutsRoute: AdminFinancePayoutsRoute,
  AdminFinancePromotionsRoute: AdminFinancePromotionsRoute,
  AdminFinanceTransactionsRoute: AdminFinanceTransactionsRoute,
  AdminFinanceIndexRoute: AdminFinanceIndexRoute,
}

const AdminFinanceRouteWithChildren = AdminFinanceRoute._addFileChildren(
  AdminFinanceRouteChildren,
)

interface AdminMorphAiRouteChildren {
  AdminMorphAiBudgetRoute: typeof AdminMorphAiBudgetRoute
  AdminMorphAiCatalogRoute: typeof AdminMorphAiCatalogRoute
  AdminMorphAiConversionRoute: typeof AdminMorphAiConversionRoute
  AdminMorphAiErrorsRoute: typeof AdminMorphAiErrorsRoute
  AdminMorphAiGalleryRoute: typeof AdminMorphAiGalleryRoute
  AdminMorphAiLimitsRoute: typeof AdminMorphAiLimitsRoute
  AdminMorphAiPopularityRoute: typeof AdminMorphAiPopularityRoute
  AdminMorphAiQueueRoute: typeof AdminMorphAiQueueRoute
  AdminMorphAiSettingsRoute: typeof AdminMorphAiSettingsRoute
  AdminMorphAiIndexRoute: typeof AdminMorphAiIndexRoute
  AdminMorphAiListKindRoute: typeof AdminMorphAiListKindRoute
}

const AdminMorphAiRouteChildren: AdminMorphAiRouteChildren = {
  AdminMorphAiBudgetRoute: AdminMorphAiBudgetRoute,
  AdminMorphAiCatalogRoute: AdminMorphAiCatalogRoute,
  AdminMorphAiConversionRoute: AdminMorphAiConversionRoute,
  AdminMorphAiErrorsRoute: AdminMorphAiErrorsRoute,
  AdminMorphAiGalleryRoute: AdminMorphAiGalleryRoute,
  AdminMorphAiLimitsRoute: AdminMorphAiLimitsRoute,
  AdminMorphAiPopularityRoute: AdminMorphAiPopularityRoute,
  AdminMorphAiQueueRoute: AdminMorphAiQueueRoute,
  AdminMorphAiSettingsRoute: AdminMorphAiSettingsRoute,
  AdminMorphAiIndexRoute: AdminMorphAiIndexRoute,
  AdminMorphAiListKindRoute: AdminMorphAiListKindRoute,
}

const AdminMorphAiRouteWithChildren = AdminMorphAiRoute._addFileChildren(
  AdminMorphAiRouteChildren,
)

interface AdminSalonsSalonIdStatsRouteChildren {
  AdminSalonsSalonIdStatsGraphsRoute: typeof AdminSalonsSalonIdStatsGraphsRoute
  AdminSalonsSalonIdStatsIndexRoute: typeof AdminSalonsSalonIdStatsIndexRoute
}

const AdminSalonsSalonIdStatsRouteChildren: AdminSalonsSalonIdStatsRouteChildren =
  {
    AdminSalonsSalonIdStatsGraphsRoute: AdminSalonsSalonIdStatsGraphsRoute,
    AdminSalonsSalonIdStatsIndexRoute: AdminSalonsSalonIdStatsIndexRoute,
  }

const AdminSalonsSalonIdStatsRouteWithChildren =
  AdminSalonsSalonIdStatsRoute._addFileChildren(
    AdminSalonsSalonIdStatsRouteChildren,
  )

interface AdminSalonsSalonIdRouteChildren {
  AdminSalonsSalonIdStatsRoute: typeof AdminSalonsSalonIdStatsRouteWithChildren
  AdminSalonsSalonIdTeamRoute: typeof AdminSalonsSalonIdTeamRoute
  AdminSalonsSalonIdIndexRoute: typeof AdminSalonsSalonIdIndexRoute
}

const AdminSalonsSalonIdRouteChildren: AdminSalonsSalonIdRouteChildren = {
  AdminSalonsSalonIdStatsRoute: AdminSalonsSalonIdStatsRouteWithChildren,
  AdminSalonsSalonIdTeamRoute: AdminSalonsSalonIdTeamRoute,
  AdminSalonsSalonIdIndexRoute: AdminSalonsSalonIdIndexRoute,
}

const AdminSalonsSalonIdRouteWithChildren =
  AdminSalonsSalonIdRoute._addFileChildren(AdminSalonsSalonIdRouteChildren)

interface AdminSalonsRouteChildren {
  AdminSalonsSalonIdRoute: typeof AdminSalonsSalonIdRouteWithChildren
}

const AdminSalonsRouteChildren: AdminSalonsRouteChildren = {
  AdminSalonsSalonIdRoute: AdminSalonsSalonIdRouteWithChildren,
}

const AdminSalonsRouteWithChildren = AdminSalonsRoute._addFileChildren(
  AdminSalonsRouteChildren,
)

interface AdminServicesRouteChildren {
  AdminServicesAnalyticsRoute: typeof AdminServicesAnalyticsRoute
}

const AdminServicesRouteChildren: AdminServicesRouteChildren = {
  AdminServicesAnalyticsRoute: AdminServicesAnalyticsRoute,
}

const AdminServicesRouteWithChildren = AdminServicesRoute._addFileChildren(
  AdminServicesRouteChildren,
)

interface AdminStatisticsRouteChildren {
  AdminStatisticsBarbersRoute: typeof AdminStatisticsBarbersRoute
  AdminStatisticsBookingsRoute: typeof AdminStatisticsBookingsRoute
  AdminStatisticsLiveRoute: typeof AdminStatisticsLiveRoute
  AdminStatisticsRevenueRoute: typeof AdminStatisticsRevenueRoute
  AdminStatisticsSalonsRoute: typeof AdminStatisticsSalonsRoute
  AdminStatisticsUsersRoute: typeof AdminStatisticsUsersRoute
  AdminStatisticsWalletRoute: typeof AdminStatisticsWalletRoute
  AdminStatisticsIndexRoute: typeof AdminStatisticsIndexRoute
}

const AdminStatisticsRouteChildren: AdminStatisticsRouteChildren = {
  AdminStatisticsBarbersRoute: AdminStatisticsBarbersRoute,
  AdminStatisticsBookingsRoute: AdminStatisticsBookingsRoute,
  AdminStatisticsLiveRoute: AdminStatisticsLiveRoute,
  AdminStatisticsRevenueRoute: AdminStatisticsRevenueRoute,
  AdminStatisticsSalonsRoute: AdminStatisticsSalonsRoute,
  AdminStatisticsUsersRoute: AdminStatisticsUsersRoute,
  AdminStatisticsWalletRoute: AdminStatisticsWalletRoute,
  AdminStatisticsIndexRoute: AdminStatisticsIndexRoute,
}

const AdminStatisticsRouteWithChildren = AdminStatisticsRoute._addFileChildren(
  AdminStatisticsRouteChildren,
)

interface AdminSubscriptionsRouteChildren {
  AdminSubscriptionsSubIdRoute: typeof AdminSubscriptionsSubIdRoute
}

const AdminSubscriptionsRouteChildren: AdminSubscriptionsRouteChildren = {
  AdminSubscriptionsSubIdRoute: AdminSubscriptionsSubIdRoute,
}

const AdminSubscriptionsRouteWithChildren =
  AdminSubscriptionsRoute._addFileChildren(AdminSubscriptionsRouteChildren)

interface AdminSupportRouteChildren {
  AdminSupportTicketIdRoute: typeof AdminSupportTicketIdRoute
}

const AdminSupportRouteChildren: AdminSupportRouteChildren = {
  AdminSupportTicketIdRoute: AdminSupportTicketIdRoute,
}

const AdminSupportRouteWithChildren = AdminSupportRoute._addFileChildren(
  AdminSupportRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersSignupsRoute: typeof AdminUsersSignupsRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersSignupsRoute: AdminUsersSignupsRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminAylanmaRoute: typeof AdminAylanmaRouteWithChildren
  AdminBarbersRoute: typeof AdminBarbersRouteWithChildren
  AdminBookingsRoute: typeof AdminBookingsRouteWithChildren
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminFinanceRoute: typeof AdminFinanceRouteWithChildren
  AdminMapRoute: typeof AdminMapRoute
  AdminMorphAiRoute: typeof AdminMorphAiRouteWithChildren
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSalonsRoute: typeof AdminSalonsRouteWithChildren
  AdminServicesRoute: typeof AdminServicesRouteWithChildren
  AdminStatisticsRoute: typeof AdminStatisticsRouteWithChildren
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRouteWithChildren
  AdminSupportRoute: typeof AdminSupportRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminAylanmaRoute: AdminAylanmaRouteWithChildren,
  AdminBarbersRoute: AdminBarbersRouteWithChildren,
  AdminBookingsRoute: AdminBookingsRouteWithChildren,
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminFinanceRoute: AdminFinanceRouteWithChildren,
  AdminMapRoute: AdminMapRoute,
  AdminMorphAiRoute: AdminMorphAiRouteWithChildren,
  AdminProfileRoute: AdminProfileRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSalonsRoute: AdminSalonsRouteWithChildren,
  AdminServicesRoute: AdminServicesRouteWithChildren,
  AdminStatisticsRoute: AdminStatisticsRouteWithChildren,
  AdminSubscriptionsRoute: AdminSubscriptionsRouteWithChildren,
  AdminSupportRoute: AdminSupportRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
