from django.conf import settings
from django.contrib import admin
from django.http import JsonResponse
from django.urls import include, path, re_path
from rest_framework.routers import DefaultRouter
from media_store.views import serve_media
from control_panel.views import (
    AdminBarberDetailView,
    AdminBarberAnalyticsView,
    AdminBarberListView,
    AdminBarberSegmentStatsView,
    AdminBookingListView,
    AdminBookingDetailView,
    AdminBroadcastListCreateView,
    AdminCategoryDetailView,
    AdminCategoryListCreateView,
    AdminFinanceOverviewView,
    AdminFinanceTransactionsView,
    AdminGiftTransferListView,
    AdminGiftTransferDetailView,
    AdminGiftTransferExportView,
    AdminGiftHoldView,
    AdminGiftReleaseView,
    AdminGiftRefundView,
    AdminGiftDisputeView,
    AdminGiftBulkHoldView,
    AdminGiftVerifyChainsView,
    AdminGiftDesignsAnalyticsView,
    AdminLedgerLookupView,
    AdminLedgerSuggestView,
    AdminWalletAdjustView,
    AdminPlatformIncomeView,
    AdminPlatformTurnoverView,
    AdminPayoutMarkPaidView,
    AdminPayoutRejectView,
    AdminPayoutsView,
    AdminBarberPromotionApproveView,
    AdminBarberPromotionListView,
    AdminBarberPromotionRejectView,
    AdminReportExportView,
    AdminAuditLogListView,
    AdminServicesView,
    AdminServiceDetailView,
    AdminServiceUsageView,
    AdminRuntimeServiceDetailView,
    AdminSupportTicketDetailView,
    AdminSupportTicketListView,
    AdminSupportTicketRepliesView,
    AdminAdminAccountDetailView,
    AdminAdminAccountListCreateView,
    AdminReviewListView,
    AdminSalonAnalyticsView,
    UserSupportTicketDetailView,
    UserSupportTicketReplyView,
    AdminSalonDetailView,
    AdminSalonListView,
    AdminStatsView,
    AdminUserDetailView,
    AdminUserListView,
    AdminUserSignupAnalyticsView,
    UserSupportTicketListCreateView,
)
from control_panel.statistics_views import (
    AdminStatisticsBookingsView,
    AdminStatisticsExportView,
    AdminStatisticsLiveView,
    AdminStatisticsOverviewView,
    AdminStatisticsRevenueView,
    AdminStatisticsSalonsView,
    AdminStatisticsUsersView,
    AdminStatisticsWalletView,
)
from agents.views import (
    AdminAgentAylanmaHubView,
    AdminAgentHubView,
    AdminAgentPayoutListView,
    AdminAgentPayoutMarkPaidView,
    AdminAgentPayoutRejectView,
    AdminAgentSalonsHubView,
    AdminAgentStatsView,
    AdminFieldAgentDetailExtendedView,
    AdminFieldAgentDetailView,
    AdminFieldAgentListCreateView,
    AgentInviteView,
    AgentMeView,
    AgentPayoutRequestView,
    AgentSalonsView,
    AgentTokenRefreshView,
    AgentTokenView,
    AgentWalletView,
)
from agents.code_check import AgentCodeCheckView

from accounts.address_views import (
    UserAddressDetailView,
    UserAddressListCreateView,
    UserAddressSetDefaultView,
)
from accounts.email_views import (
    UserEmailSendCodeView,
    UserEmailVerifyLinkView,
    UserEmailVerifyView,
)
from accounts.family_views import FamilyMemberDetailView, FamilyMemberListCreateView
from accounts.referral_views import MyReferralView
from subscriptions.views import (
    SubscriptionCareAccessView,
    SubscriptionCheckoutView,
    SubscriptionConfirmView,
    SubscriptionMeView,
    SubscriptionPlansView,
    SubscriptionPromoPreviewView,
)
from subscriptions.admin_views import (
    AdminSubscriptionActivateView,
    AdminSubscriptionAnalyticsView,
    AdminSubscriptionDeactivateView,
    AdminSubscriptionDetailView,
    AdminSubscriptionEventsView,
    AdminSubscriptionGrantView,
    AdminSubscriptionListView,
    AdminSubscriptionPaymentsView,
    AdminSubscriptionStatsView,
    AdminSubscriptionUsageListView,
)
from accounts.session_views import (
    UserSessionListView,
    UserSessionRevokeOthersView,
    UserSessionRevokeView,
    UserTokenRefreshView,
)
from accounts.launch_interest_views import LaunchInterestCreateView
from accounts.views import (
    BarberCheckAvailabilityView,
    BarberRegisterJoinSalonView,
    BarberRegisterView,
    MeView,
    UserSearchView,
    UzRegionsView,
)
from accounts.views_google_auth import GoogleLoginView
from accounts.views_phone_auth import (
    PhoneChangePasswordView,
    PhoneCheckView,
    PhonePasswordLoginView,
    PhoneSendCodeView,
    PhoneSetPasswordView,
    PhoneVerifyView,
)
from accounts.views_admin_auth import AdminMeView, AdminTokenRefreshView, AdminTokenView
from bookings.views import (
    AnalyticsView,
    BookingAvailabilityMonthView,
    BookingAvailabilityView,
    BookingViewSet,
    IndependentClientsView,
    NotificationListView,
    NotificationMarkAllReadView,
    NotificationMarkReadView,
    ReviewViewSet,
    SalonClientsView,
    SalonPortfolioView,
)
from barbers.marketing_api import BarberMarketingBoostView
from barbers.customer_invite_views import (
    BarberCustomerInviteView,
    BarberCustomerOutreachCancelView,
    BarberCustomerOutreachCreateView,
)
from barbers.shop_subscription_views import (
    BarberShopCheckoutView,
    BarberShopClaimAgentTrialView,
    BarberShopConfirmView,
    BarberShopMeView,
    BarberShopPlansView,
)
from control_panel.customer_invite_admin import (
    AdminBarberCustomerInviteDetailView,
    AdminBarberCustomerInviteListView,
    AdminBarberCustomerInviteStatsView,
    AdminBarberInviteLeaderboardView,
)
from barbers.payout_api import (
    BarberPayoutBalanceView,
    BarberPayoutDetailsView,
    BarberPayoutListView,
    BarberPayoutRequestView,
)
from barbers.views import (
    BarberPublicViewSet,
    MyBarberExpenseViewSet,
    MyBarberFinanceSummaryView,
    MyBarberGoalViewSet,
    MyBarberInventoryMovementViewSet,
    MyBarberInventoryViewSet,
    BarberSearchView,
    IndependentAvailabilityView,
    IndependentAvailabilityMonthView,
    MyBarberProfileView,
    MyBarberBookingSettingsView,
    MyBarberPromoViewSet,
    MyBarberReviewsView,
    MyBarberCatalogServiceView,
    MyBarberSettingsView,
    MyBarberServiceRecommendationsView,
    MyBarberScheduleExceptionViewSet,
    MyBarberServiceViewSet,
    MyBarberSupportTicketViewSet,
    MyBarberWorkPhotoViewSet,
    MyBarberWorkingHoursViewSet,
)
from barbers.views_barber_auth import (
    BarberEmailResendView,
    BarberEmailVerifyView,
    LegacyBarberSendOtpEmailCompatView,
    BarberMeView,
    BarberOnboardingStatusView,
    BarberTokenRefreshView,
    BarberTokenView,
)
from salons.views import (
    BarberScheduleExceptionViewSet,
    BarberScheduleViewSet,
    FavoriteSalonDetailView,
    FavoriteSalonListCreateView,
    SalonMembershipViewSet,
    SalonViewSet,
)
from salons.amenity_views import AmenityCatalogView, BarberSalonAmenitiesView
from ai.explore_gen_views import (
    ExploreGenDownloadView,
    ExploreGenGenerateView,
    ExploreGenPersonaLabelView,
    ExploreGenPublishView,
    ExploreGenStatusView,
)
from ai.assets_studio_views import (
    AssetsStudioDownloadView,
    AssetsStudioGenerateView,
    AssetsStudioSelectView,
    AssetsStudioStatusView,
)
from ai.admin_views import (
    AdminMorphAiAnalyticsView,
    AdminMorphAiBudgetView,
    AdminMorphAiCatalogDetailView,
    AdminMorphAiCatalogListCreateView,
    AdminMorphAiConversionView,
    AdminMorphAiErrorsView,
    AdminMorphAiExportView,
    AdminMorphAiGalleryView,
    AdminMorphAiLimitsView,
    AdminMorphAiListExportView,
    AdminMorphAiListView,
    AdminMorphAiPopularityView,
    AdminMorphAiQueueView,
    AdminMorphAiSettingsView,
)
from ai.views import (
    AiBarberCardView,
    AiFaceCheckView,
    AiStyleAnalyzeView,
    AiStyleHistoryListCreateView,
    AiStyleStudioCatalogView,
    AiStyleStudioEditView,
    AiStyleTryOnJobView,
    AiStyleTryOnView,
    ExplorePersonaListView,
    HairstyleDetailView,
    HairstyleListView,
    MorphAiGenerationListCreateView,
    MorphAiLookShareCreateView,
    MorphAiLookShareDetailView,
    MorphAiLookShareViewPingView,
)
from chat.views import ConversationListCreateView, ConversationMarkReadView, ConversationMessagesView
from geo.views import CurrencyRatesView, GeocodeView, MapConfigView, ReverseGeocodeView, ValidateLocationView
from notifications.push_views import BarberPushTokenView
from wallet.card_deposit_views import (
    AdminWalletDepositApproveView,
    AdminWalletDepositRejectView,
    AdminWalletDepositsView,
    WalletCardDepositClaimView,
    WalletCardDepositInitView,
    WalletCardDepositListView,
    WalletReceivingCardView,
)
from wallet.qr_pay_views import (
    AdminQrPaymentDetailView,
    AdminQrPaymentListView,
    BarberQrPayPaymentsView,
    BarberQrPayProfileView,
    BarberQrPayRequestCreateView,
    WalletQrPayResolveView,
    WalletQrPayView,
)
from wallet.admin_accounts_views import (
    AdminBarberAccountDetailView,
    AdminBarberAccountLockView,
    AdminBarberAccountsView,
)
from wallet.payment_confirm import PaymentConfirmView
from wallet.payment_views import PaymentCheckoutView, PaymentProvidersView
from wallet.views import (
    AdminWalletTopUpView,
    WalletGiftDesignsView,
    WalletGiftReceivedView,
    WalletGiftSendView,
    WalletMeView,
    WalletRecipientSearchView,
    WalletTopUpView,
    WalletTransactionsView,
)


def health(_request):
    from config.redis_health import redis_health_payload

    redis = redis_health_payload()
    return JsonResponse(
        {
            "ok": True,
            "redis": redis,
            "realtime": {
                "ready": redis.get("realtime_ready", False),
                "mode": "redis" if redis.get("realtime_ready") else "polling",
            },
        }
    )


router = DefaultRouter()
router.register(r"salons", SalonViewSet, basename="salon")
router.register(r"memberships", SalonMembershipViewSet, basename="membership")
router.register(r"schedules", BarberScheduleViewSet, basename="schedule")
router.register(
    r"schedule-exceptions",
    BarberScheduleExceptionViewSet,
    basename="schedule-exception",
)
router.register(r"bookings", BookingViewSet, basename="booking")
router.register(r"reviews", ReviewViewSet, basename="review")
router.register(r"barbers", BarberPublicViewSet, basename="barber")
router.register(r"barber/services", MyBarberServiceViewSet, basename="barber-service")
router.register(r"barber/work-photos", MyBarberWorkPhotoViewSet, basename="barber-work-photos")
router.register(r"barber/working-hours", MyBarberWorkingHoursViewSet, basename="barber-working-hours")
router.register(
    r"barber/schedule-exceptions",
    MyBarberScheduleExceptionViewSet,
    basename="barber-schedule-exception",
)
router.register(r"barber/inventory", MyBarberInventoryViewSet, basename="barber-inventory")
router.register(
    r"barber/inventory-movements",
    MyBarberInventoryMovementViewSet,
    basename="barber-inventory-movements",
)
router.register(r"barber/expenses", MyBarberExpenseViewSet, basename="barber-expenses")
router.register(r"barber/goals", MyBarberGoalViewSet, basename="barber-goals")
router.register(r"barber/promos", MyBarberPromoViewSet, basename="barber-promos")
router.register(r"barber/support", MyBarberSupportTicketViewSet, basename="barber-support")
# Shared API routes (mounted at both /api/v1/ and /api/ for compatibility).
api_routes = [
    path("admin/stats/", AdminStatsView.as_view()),
    path("admin/statistics/live/", AdminStatisticsLiveView.as_view()),
    path("admin/statistics/overview/", AdminStatisticsOverviewView.as_view()),
    path("admin/statistics/revenue/", AdminStatisticsRevenueView.as_view()),
    path("admin/statistics/users/", AdminStatisticsUsersView.as_view()),
    path("admin/statistics/salons/", AdminStatisticsSalonsView.as_view()),
    path("admin/statistics/wallet/", AdminStatisticsWalletView.as_view()),
    path("admin/statistics/bookings/", AdminStatisticsBookingsView.as_view()),
    path("admin/statistics/export/<str:export_type>/", AdminStatisticsExportView.as_view()),
    path("admin/morph-ai/", AdminMorphAiAnalyticsView.as_view()),
    path("admin/morph-ai/errors/", AdminMorphAiErrorsView.as_view()),
    path("admin/morph-ai/popularity/", AdminMorphAiPopularityView.as_view()),
    path("admin/morph-ai/conversion/", AdminMorphAiConversionView.as_view()),
    path("admin/morph-ai/budget/", AdminMorphAiBudgetView.as_view()),
    path("admin/morph-ai/limits/", AdminMorphAiLimitsView.as_view()),
    path("admin/morph-ai/queue/", AdminMorphAiQueueView.as_view()),
    path("admin/morph-ai/gallery/", AdminMorphAiGalleryView.as_view()),
    path("admin/morph-ai/settings/", AdminMorphAiSettingsView.as_view()),
    path("admin/morph-ai/export/", AdminMorphAiExportView.as_view()),
    path("admin/morph-ai/list/<str:kind>/export/", AdminMorphAiListExportView.as_view()),
    path("admin/morph-ai/list/<str:kind>/", AdminMorphAiListView.as_view()),
    path("admin/morph-ai/catalog/", AdminMorphAiCatalogListCreateView.as_view()),
    path("admin/morph-ai/catalog/<str:style_id>/", AdminMorphAiCatalogDetailView.as_view()),
    path("admin/subscriptions/stats/", AdminSubscriptionStatsView.as_view()),
    path("admin/subscriptions/analytics/", AdminSubscriptionAnalyticsView.as_view()),
    path("admin/subscriptions/", AdminSubscriptionListView.as_view()),
    path("admin/subscriptions/payments/", AdminSubscriptionPaymentsView.as_view()),
    path("admin/subscriptions/events/", AdminSubscriptionEventsView.as_view()),
    path("admin/subscriptions/usage/", AdminSubscriptionUsageListView.as_view()),
    path("admin/subscriptions/grant/", AdminSubscriptionGrantView.as_view()),
    path("admin/subscriptions/<uuid:pk>/", AdminSubscriptionDetailView.as_view()),
    path("admin/subscriptions/<uuid:pk>/deactivate/", AdminSubscriptionDeactivateView.as_view()),
    path("admin/subscriptions/<uuid:pk>/activate/", AdminSubscriptionActivateView.as_view()),
    path("admin/users/signup-analytics/", AdminUserSignupAnalyticsView.as_view()),
    path("admin/users/", AdminUserListView.as_view()),
    path("admin/users/<int:pk>/", AdminUserDetailView.as_view()),
    path("admin/salons/", AdminSalonListView.as_view()),
    path("admin/salons/<int:pk>/analytics/", AdminSalonAnalyticsView.as_view()),
    path("admin/salons/<int:pk>/", AdminSalonDetailView.as_view()),
    path("admin/barbers/", AdminBarberListView.as_view()),
    path("admin/barbers/segment-stats/", AdminBarberSegmentStatsView.as_view()),
    path("admin/barbers/<int:pk>/analytics/", AdminBarberAnalyticsView.as_view()),
    path("admin/barbers/<int:pk>/customer-invites/", AdminBarberCustomerInviteDetailView.as_view()),
    path("admin/barbers/<int:pk>/", AdminBarberDetailView.as_view()),
    path("admin/customer-invites/stats/", AdminBarberCustomerInviteStatsView.as_view()),
    path("admin/customer-invites/leaderboard/", AdminBarberInviteLeaderboardView.as_view()),
    path("admin/customer-invites/", AdminBarberCustomerInviteListView.as_view()),
    path("admin/bookings/", AdminBookingListView.as_view()),
    path("admin/bookings/<int:pk>/", AdminBookingDetailView.as_view()),
    path("admin/reviews/", AdminReviewListView.as_view()),
    path("admin/categories/", AdminCategoryListCreateView.as_view()),
    path("admin/categories/<int:pk>/", AdminCategoryDetailView.as_view()),
    path("admin/services/", AdminServicesView.as_view()),
    path("admin/services/usage/", AdminServiceUsageView.as_view()),
    path("admin/services/<str:pk>/", AdminServiceDetailView.as_view()),
    path("admin/service-assignments/<str:kind>/<int:pk>/", AdminRuntimeServiceDetailView.as_view()),
    path("admin/finance/overview/", AdminFinanceOverviewView.as_view()),
    path("admin/finance/platform-income/", AdminPlatformIncomeView.as_view()),
    path("admin/finance/platform-turnover/", AdminPlatformTurnoverView.as_view()),
    path("admin/finance/gifts/", AdminGiftTransferListView.as_view()),
    path("admin/finance/gifts/export/", AdminGiftTransferExportView.as_view()),
    path("admin/finance/gifts/bulk-hold/", AdminGiftBulkHoldView.as_view()),
    path("admin/finance/gifts/<uuid:pk>/", AdminGiftTransferDetailView.as_view()),
    path("admin/finance/gifts/<uuid:pk>/hold/", AdminGiftHoldView.as_view()),
    path("admin/finance/gifts/<uuid:pk>/release/", AdminGiftReleaseView.as_view()),
    path("admin/finance/gifts/<uuid:pk>/refund/", AdminGiftRefundView.as_view()),
    path("admin/finance/gifts/<uuid:pk>/dispute/", AdminGiftDisputeView.as_view()),
    path("admin/finance/gifts/<uuid:pk>/verify-chains/", AdminGiftVerifyChainsView.as_view()),
    path("admin/finance/qr-payments/", AdminQrPaymentListView.as_view()),
    path("admin/finance/qr-payments/<uuid:pk>/", AdminQrPaymentDetailView.as_view()),
    path("admin/accounts/", AdminBarberAccountsView.as_view()),
    path("admin/accounts/<int:barber_id>/", AdminBarberAccountDetailView.as_view()),
    path("admin/accounts/<int:barber_id>/lock/", AdminBarberAccountLockView.as_view()),
    path("admin/hisob-raqam/", AdminBarberAccountsView.as_view()),
    path("admin/hisob-raqam/<int:barber_id>/", AdminBarberAccountDetailView.as_view()),
    path("admin/finance/gift-designs/", AdminGiftDesignsAnalyticsView.as_view()),
    path("admin/ledger/suggest/", AdminLedgerSuggestView.as_view()),
    path("admin/ledger/lookup/", AdminLedgerLookupView.as_view()),
    path("admin/wallet/adjust/", AdminWalletAdjustView.as_view()),
    path("admin/finance/transactions/", AdminFinanceTransactionsView.as_view()),
    path("admin/finance/payouts/", AdminPayoutsView.as_view()),
    path("admin/finance/payouts/<int:pk>/paid/", AdminPayoutMarkPaidView.as_view()),
    path("admin/finance/payouts/<int:pk>/reject/", AdminPayoutRejectView.as_view()),
    path("admin/payouts/", AdminPayoutsView.as_view()),
    path("admin/payouts/<int:pk>/paid/", AdminPayoutMarkPaidView.as_view()),
    path("admin/payouts/<int:pk>/reject/", AdminPayoutRejectView.as_view()),
    path("admin/marketing/promotions/", AdminBarberPromotionListView.as_view()),
    path("admin/marketing/promotions/<int:pk>/approve/", AdminBarberPromotionApproveView.as_view()),
    path("admin/marketing/promotions/<int:pk>/reject/", AdminBarberPromotionRejectView.as_view()),
    path("admin/reports/<str:report_type>/", AdminReportExportView.as_view()),
    path("admin/audit/", AdminAuditLogListView.as_view()),
    path("admin/support/tickets/", AdminSupportTicketListView.as_view()),
    path("admin/support/tickets/<int:pk>/", AdminSupportTicketDetailView.as_view()),
    path("admin/support/tickets/<int:pk>/replies/", AdminSupportTicketRepliesView.as_view()),
    path("admin/broadcast/", AdminBroadcastListCreateView.as_view()),
    path("admin/admins/", AdminAdminAccountListCreateView.as_view()),
    path("admin/admins/<int:pk>/", AdminAdminAccountDetailView.as_view()),
    path("admin/agents/", AdminFieldAgentListCreateView.as_view()),
    path("admin/agents/stats/", AdminAgentStatsView.as_view()),
    path("admin/agents/hub/", AdminAgentHubView.as_view()),
    path("admin/agents/salons-hub/", AdminAgentSalonsHubView.as_view()),
    path("admin/agents/aylanma/", AdminAgentAylanmaHubView.as_view()),
    path("admin/agents/payouts/", AdminAgentPayoutListView.as_view()),
    path("admin/agents/payouts/<int:pk>/paid/", AdminAgentPayoutMarkPaidView.as_view()),
    path("admin/agents/payouts/<int:pk>/reject/", AdminAgentPayoutRejectView.as_view()),
    path("admin/agents/<int:pk>/detail/", AdminFieldAgentDetailExtendedView.as_view()),
    path("admin/agents/<int:pk>/", AdminFieldAgentDetailView.as_view()),
    path("agent/auth/token/", AgentTokenView.as_view()),
    path("agent/auth/token/refresh/", AgentTokenRefreshView.as_view()),
    path("agent/me/", AgentMeView.as_view()),
    path("agent/salons/", AgentSalonsView.as_view()),
    path("agent/invite/", AgentInviteView.as_view()),
    path("agent/wallet/", AgentWalletView.as_view()),
    path("agent/payouts/request/", AgentPayoutRequestView.as_view()),
    path("regions/", UzRegionsView.as_view()),
    path("geo/map-config/", MapConfigView.as_view()),
    path("geo/geocode/", GeocodeView.as_view()),
    path("geo/reverse/", ReverseGeocodeView.as_view()),
    path("geo/validate/", ValidateLocationView.as_view()),
    path("currencies/", CurrencyRatesView.as_view()),
    path("launch-interest/", LaunchInterestCreateView.as_view()),
    path("auth/google/", GoogleLoginView.as_view()),
    path("auth/phone/send-code/", PhoneSendCodeView.as_view()),
    path("auth/phone/verify/", PhoneVerifyView.as_view()),
    path("auth/phone/check/", PhoneCheckView.as_view()),
    path("auth/phone/password-login/", PhonePasswordLoginView.as_view()),
    path("auth/phone/set-password/", PhoneSetPasswordView.as_view()),
    path("auth/phone/change-password/", PhoneChangePasswordView.as_view()),
    path("ai/style-analyze/", AiStyleAnalyzeView.as_view()),
    path("ai/style-tryon/", AiStyleTryOnView.as_view()),
    path("ai/style-tryon/<str:job_id>/", AiStyleTryOnJobView.as_view()),
    path("ai/style-studio/", AiStyleStudioEditView.as_view()),
    path("ai/style-studio/catalog/", AiStyleStudioCatalogView.as_view()),
    path("ai/face-check/", AiFaceCheckView.as_view()),
    path("ai/barber-card/", AiBarberCardView.as_view()),
    path("ai/style-history/", AiStyleHistoryListCreateView.as_view()),
    path("ai/generations/", MorphAiGenerationListCreateView.as_view()),
    path("ai/look-share/", MorphAiLookShareCreateView.as_view()),
    path("ai/look-share/<uuid:share_id>/", MorphAiLookShareDetailView.as_view()),
    path("ai/look-share/<uuid:share_id>/view/", MorphAiLookShareViewPingView.as_view()),
    path("ai/dev/explore-gen/", ExploreGenStatusView.as_view()),
    path("ai/dev/explore-gen/generate/", ExploreGenGenerateView.as_view()),
    path("ai/dev/explore-gen/download/", ExploreGenDownloadView.as_view()),
    path("ai/dev/explore-gen/publish/", ExploreGenPublishView.as_view()),
    path("ai/dev/explore-gen/persona-label/", ExploreGenPersonaLabelView.as_view()),
    path("ai/dev/explore-gen/assets/", AssetsStudioStatusView.as_view()),
    path("ai/dev/explore-gen/assets/generate/", AssetsStudioGenerateView.as_view()),
    path("ai/dev/explore-gen/assets/select/", AssetsStudioSelectView.as_view()),
    path("ai/dev/explore-gen/assets/download/", AssetsStudioDownloadView.as_view()),
    path("explore/personas/", ExplorePersonaListView.as_view()),
    path("hairstyles/", HairstyleListView.as_view()),
    path("hairstyles/<str:style_id>/", HairstyleDetailView.as_view()),
    path("auth/barber-register/", BarberRegisterView.as_view()),
    path("auth/barber-register-join-salon/", BarberRegisterJoinSalonView.as_view()),
    path("auth/barber-check-availability/", BarberCheckAvailabilityView.as_view()),
    path("auth/agent-code-check/", AgentCodeCheckView.as_view()),
    path("auth/token/refresh/", UserTokenRefreshView.as_view()),
    path("admin/auth/token/", AdminTokenView.as_view()),
    path("admin/auth/token/refresh/", AdminTokenRefreshView.as_view()),
    path("admin/auth/me/", AdminMeView.as_view()),
    path("auth/email/verify-link/", UserEmailVerifyLinkView.as_view()),
    path("users/me/email/send-code/", UserEmailSendCodeView.as_view()),
    path("users/me/email/verify/", UserEmailVerifyView.as_view()),
    path("users/me/sessions/", UserSessionListView.as_view()),
    path("users/me/sessions/revoke-others/", UserSessionRevokeOthersView.as_view()),
    path("users/me/sessions/<int:pk>/", UserSessionRevokeView.as_view()),
    path("users/family/", FamilyMemberListCreateView.as_view()),
    path("users/family/<int:pk>/", FamilyMemberDetailView.as_view()),
    path("users/me/referral/", MyReferralView.as_view()),
    path("subscriptions/plans/", SubscriptionPlansView.as_view()),
    path("subscriptions/promo-preview/", SubscriptionPromoPreviewView.as_view()),
    path("subscriptions/me/", SubscriptionMeView.as_view()),
    path("subscriptions/checkout/", SubscriptionCheckoutView.as_view()),
    path("subscriptions/confirm/", SubscriptionConfirmView.as_view()),
    path("subscriptions/care-access/", SubscriptionCareAccessView.as_view()),
    path("users/me/", MeView.as_view()),
    path("users/addresses/", UserAddressListCreateView.as_view()),
    path("users/addresses/<int:pk>/", UserAddressDetailView.as_view()),
    path("users/addresses/<int:pk>/set-default/", UserAddressSetDefaultView.as_view()),
    path("users/search/", UserSearchView.as_view()),
    path("barbers/search/", BarberSearchView.as_view()),
    path("barber/auth/token/", BarberTokenView.as_view()),
    path("barber/auth/token/refresh/", BarberTokenRefreshView.as_view()),
    # Legacy partner auth endpoint (older deployed bundles).
    path("accounts/auth/barber/send-otp/email/", LegacyBarberSendOtpEmailCompatView.as_view()),
    path("barber/auth/verify-email/", BarberEmailVerifyView.as_view()),
    path("barber/auth/resend-verification-email/", BarberEmailResendView.as_view()),
    path("barber/auth/me/", BarberMeView.as_view()),
    path("barber/onboarding/status/", BarberOnboardingStatusView.as_view()),
    path("barber/profile/", MyBarberProfileView.as_view()),
    path("barber/booking-settings/", MyBarberBookingSettingsView.as_view()),
    path("barber/catalog-services/", MyBarberCatalogServiceView.as_view()),
    path("barber/settings/", MyBarberSettingsView.as_view()),
    path("barber/push-token/", BarberPushTokenView.as_view()),
    path("barber/service-recommendations/", MyBarberServiceRecommendationsView.as_view()),
    path("barber/reviews/", MyBarberReviewsView.as_view()),
    path("barber/finance/summary/", MyBarberFinanceSummaryView.as_view()),
    path("barber/payouts/", BarberPayoutListView.as_view()),
    path("barber/payouts/balance/", BarberPayoutBalanceView.as_view()),
    path("barber/payouts/request/", BarberPayoutRequestView.as_view()),
    path("barber/payouts/details/", BarberPayoutDetailsView.as_view()),
    path("barber/qr-pay/profile/", BarberQrPayProfileView.as_view()),
    path("barber/qr-pay/requests/", BarberQrPayRequestCreateView.as_view()),
    path("barber/qr-pay/payments/", BarberQrPayPaymentsView.as_view()),
    path("barber/marketing/boost/", BarberMarketingBoostView.as_view()),
    path("barber/subscription/plans/", BarberShopPlansView.as_view()),
    path("barber/subscription/me/", BarberShopMeView.as_view()),
    path("barber/subscription/checkout/", BarberShopCheckoutView.as_view()),
    path("barber/subscription/confirm/", BarberShopConfirmView.as_view()),
    path("barber/subscription/claim-agent-trial/", BarberShopClaimAgentTrialView.as_view()),
    path("barber/customer-invites/", BarberCustomerInviteView.as_view()),
    path("barber/customer-invites/outreach/", BarberCustomerOutreachCreateView.as_view()),
    path(
        "barber/customer-invites/outreach/<int:pk>/cancel/",
        BarberCustomerOutreachCancelView.as_view(),
    ),
    path("amenities/", AmenityCatalogView.as_view()),
    path("barber/amenities/", BarberSalonAmenitiesView.as_view()),
    path("favorites/salons/", FavoriteSalonListCreateView.as_view()),
    path("favorites/salons/<int:salon_id>/", FavoriteSalonDetailView.as_view()),
    path("notifications/", NotificationListView.as_view()),
    path("notifications/<int:pk>/read/", NotificationMarkReadView.as_view()),
    path("notifications/mark-all-read/", NotificationMarkAllReadView.as_view()),
    path("analytics/", AnalyticsView.as_view()),
    path("analytics/clients/", SalonClientsView.as_view()),
    path("analytics/clients/independent/", IndependentClientsView.as_view()),
    path("bookings/availability/", BookingAvailabilityView.as_view()),
    path("bookings/availability/month/", BookingAvailabilityMonthView.as_view()),
    path("barbers/availability/", IndependentAvailabilityView.as_view()),
    path("barbers/availability/month/", IndependentAvailabilityMonthView.as_view()),
    path("salons/<int:salon_id>/portfolio/", SalonPortfolioView.as_view()),
    # Chat (text-only): barber ↔ user
    path("chat/conversations/", ConversationListCreateView.as_view()),
    path(
        "chat/conversations/<uuid:conversation_id>/messages/",
        ConversationMessagesView.as_view(),
    ),
    path(
        "chat/conversations/<uuid:conversation_id>/read/",
        ConversationMarkReadView.as_view(),
    ),
    path("support/tickets/", UserSupportTicketListCreateView.as_view()),
    path("support/tickets/<int:pk>/", UserSupportTicketDetailView.as_view()),
    path("support/tickets/<int:pk>/replies/", UserSupportTicketReplyView.as_view()),
    path("wallet/me/", WalletMeView.as_view()),
    path("wallet/transactions/", WalletTransactionsView.as_view()),
    path("wallet/top-up/", WalletTopUpView.as_view()),
    path("wallet/top-up/receiving-card/", WalletReceivingCardView.as_view()),
    path("wallet/top-up/card/init/", WalletCardDepositInitView.as_view()),
    path("wallet/top-up/card/<uuid:deposit_id>/claim/", WalletCardDepositClaimView.as_view()),
    path("wallet/top-up/card/deposits/", WalletCardDepositListView.as_view()),
    path("wallet/gift/designs/", WalletGiftDesignsView.as_view()),
    path("wallet/gift/send/", WalletGiftSendView.as_view()),
    path("wallet/gift/received/", WalletGiftReceivedView.as_view()),
    path("wallet/qr-pay/resolve/", WalletQrPayResolveView.as_view()),
    path("wallet/qr-pay/", WalletQrPayView.as_view()),
    path("wallet/recipients/search/", WalletRecipientSearchView.as_view()),
    path("payments/providers/", PaymentProvidersView.as_view()),
    path("payments/checkout/", PaymentCheckoutView.as_view()),
    path("payments/confirm/", PaymentConfirmView.as_view()),
    path("admin/wallet/top-up/", AdminWalletTopUpView.as_view()),
    path("admin/wallet/deposits/", AdminWalletDepositsView.as_view()),
    path("admin/wallet/deposits/<uuid:deposit_id>/approve/", AdminWalletDepositApproveView.as_view()),
    path("admin/wallet/deposits/<uuid:deposit_id>/reject/", AdminWalletDepositRejectView.as_view()),
    path("", include(router.urls)),
]

urlpatterns = [
    path("health/", health),
    path("api/v1/", include(api_routes)),
    path("api/", include(api_routes)),
]

# Django admin faqat maxfiy URL (asosiy boshqaruv Next.js /admin da)
if settings.DEBUG:
    urlpatterns.insert(0, path("django-sys-admin/", admin.site.urls))

# Media: disk (volume) yoki Postgres StoredMedia — redeployda yo‘qolmasin.
urlpatterns += [
    re_path(r"^media/(?P<path>.*)$", serve_media),
]
