# Generated by Django 6.0.3 on 2026-06-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='wallet_ledg_wallet__9a50b7_idx',
            old_name='wallet_ledg_wallet__a1b2c3_idx',
        ),
    ]
