# Generated by Django 6.0.3 on 2026-07-14 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_wallet_ledg_wallet__a1b2c3_idx_wallet_ledg_wallet__9a50b7_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifttransfer',
            name='design_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='gifttransfer',
            name='design_fee_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_as_design_fee', to='wallet.ledgerentry'),
        ),
        migrations.AddField(
            model_name='gifttransfer',
            name='design_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='gifttransfer',
            name='total_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('topup', 'Top-up'), ('gift_out', 'Gift sent'), ('gift_in', 'Gift received'), ('gift_design_fee', 'Gift card design fee'), ('booking_pay', 'Booking payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], db_index=True, max_length=32),
        ),
    ]
