# Generated by Django 6.0.3 on 2026-07-21 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_ledger_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCardDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('awaiting_payment', "To'lov kutilmoqda"), ('claimed', "To'ladim deb yuborildi"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('expired', "Muddati o'tgan"), ('cancelled', 'Bekor qilingan')], db_index=True, default='awaiting_payment', max_length=24)),
                ('transaction_ref', models.CharField(db_index=True, max_length=24, unique=True)),
                ('merchant_ref', models.CharField(db_index=True, max_length=64)),
                ('receiving_card_number', models.CharField(max_length=32)),
                ('receiving_card_masked', models.CharField(max_length=32)),
                ('receiving_cardholder', models.CharField(max_length=255)),
                ('receiving_bank', models.CharField(blank=True, default='', max_length=128)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('claimed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_admin_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reviewed_by_admin_email', models.CharField(blank=True, default='', max_length=255)),
                ('review_note', models.CharField(blank=True, default='', max_length=500)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_deposit', to='wallet.ledgerentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_deposits', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_deposits', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='wallet_manu_status_f9eb9f_idx'), models.Index(fields=['user', 'status'], name='wallet_manu_user_id_2b2124_idx')],
            },
        ),
    ]
