# Generated by Django 6.0.3 on 2026-07-23 03:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0022_barber_business_kind'),
        ('wallet', '0008_qr_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('booking_in', 'Booking release'), ('qr_in', 'QR payment in'), ('payout_out', 'Payout request'), ('payout_refund', 'Payout rejected refund'), ('opening', 'Opening balance'), ('adjustment', 'Adjustment'), ('refund_out', 'Booking refund clawback')], db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_type', models.CharField(blank=True, default='', max_length=64)),
                ('reference_id', models.CharField(blank=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('prev_hash', models.CharField(max_length=64)),
                ('entry_hash', models.CharField(db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarberWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=19, unique=True)),
                ('account_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='qrpayment',
            new_name='wallet_qrpa_barber__62cd0f_idx',
            old_name='wallet_qrpa_barber__idx',
        ),
        migrations.RenameIndex(
            model_name='qrpayment',
            new_name='wallet_qrpa_payer_i_148f00_idx',
            old_name='wallet_qrpa_payer__idx',
        ),
        migrations.RenameIndex(
            model_name='qrpayment',
            new_name='wallet_qrpa_status_93c1bf_idx',
            old_name='wallet_qrpa_status_idx',
        ),
        migrations.AddField(
            model_name='barberwallet',
            name='barber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mysaloon_wallet', to='barbers.barber'),
        ),
        migrations.AddField(
            model_name='barberledgerentry',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='wallet.barberwallet'),
        ),
        migrations.AddIndex(
            model_name='barberledgerentry',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_barb_wallet__9cb151_idx'),
        ),
        migrations.AddIndex(
            model_name='barberledgerentry',
            index=models.Index(fields=['entry_type', 'created_at'], name='wallet_barb_entry_t_a1c984_idx'),
        ),
    ]
