# Generated by Django 6.0.6 on 2026-07-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_barber_wallet_and_escrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('booking_in', 'Booking release'), ('qr_in', 'QR payment in'), ('payout_out', 'Payout request'), ('payout_refund', 'Payout rejected refund'), ('opening', 'Opening balance'), ('adjustment', 'Adjustment'), ('refund_out', 'Booking refund clawback'), ('subscription_out', 'Shop subscription')], db_index=True, max_length=32),
        ),
    ]
