# Generated by Django 6.0.3 on 2026-03-31 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarberWorkingHours",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weekday", models.PositiveSmallIntegerField()),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                ("is_day_off", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="barbers.barberprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
                "unique_together": {("profile", "weekday")},
            },
        ),
    ]

