# Generated by Django 6.0.3 on 2026-04-25 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0007_barber_onboarding_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='region',
            field=models.CharField(blank=True, choices=[('ANDIJON', 'Andijon viloyati'), ('BUXORO', 'Buxoro viloyati'), ('FARGONA', "Farg'ona viloyati"), ('JIZZAX', 'Jizzax viloyati'), ('QASHQADARYO', 'Qashqadaryo viloyati'), ('NAVOIY', 'Navoiy viloyati'), ('NAMANGAN', 'Namangan viloyati'), ('SAMARQAND', 'Samarqand viloyati'), ('SURXONDARYO', 'Surxondaryo viloyati'), ('SIRDARYO', 'Sirdaryo viloyati'), ('TOSHKENT_SH', 'Toshkent shahri'), ('TOSHKENT_V', 'Toshkent viloyati'), ('XORAZM', 'Xorazm viloyati')], db_index=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='BarberSignupSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_salon', models.BooleanField(default=False)),
                ('shop_name', models.CharField(blank=True, default='', max_length=255)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('staff_count_at_signup', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup_snapshot', to='barbers.barber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
