# Generated by Django 6.0.3 on 2026-04-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0008_alter_barber_region_barbersignupsnapshot'),
        ('salons', '0005_category_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberservice',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='barber_services', to='salons.category'),
        ),
    ]
