# Generated by Django 6.0.3 on 2026-05-14 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbers", "0012_barber_email_verified_at"),
        ("salons", "0008_catalogservice_service_catalog_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="barberservice",
            name="catalog_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_barber_services",
                to="salons.catalogservice",
            ),
        ),
    ]
