# Generated by Django 6.0.3 on 2026-05-14 01:12

from __future__ import annotations

import re
from urllib.parse import quote

from django.db import migrations


CATEGORY_ROWS = [
    {"name": "Soch", "icon": "CUT", "order": 0},
    {"name": "Soqol", "icon": "BRD", "order": 1},
    {"name": "Kombo", "icon": "SET", "order": 2},
    {"name": "Parvarish", "icon": "CARE", "order": 3},
    {"name": "Bolalar", "icon": "KID", "order": 4},
]

SERVICE_ROWS = [
    {"name": "Soch olish", "category": "Soch", "duration": 30, "description": "Klassik kundalik soch olish."},
    {"name": "Fade soch", "category": "Soch", "duration": 40, "description": "Past va yuqori fade bilan zamonaviy kesim."},
    {"name": "Machine cut", "category": "Soch", "duration": 20, "description": "Mashinka bilan tez va toza kesim."},
    {"name": "Texture styling", "category": "Soch", "duration": 45, "description": "Texturali finish va styling bilan kesim."},
    {"name": "Bolalar sochi", "category": "Bolalar", "duration": 30, "description": "Bolalar uchun yengil va qulay kesim."},
    {"name": "Soqol trim", "category": "Soqol", "duration": 20, "description": "Soqolni tenglashtirish va kontur berish."},
    {"name": "Ustara soqol", "category": "Soqol", "duration": 30, "description": "Issiq sochiq va ustara bilan silliq soqol."},
    {"name": "Murt trim", "category": "Soqol", "duration": 15, "description": "Murtni tozalash va shakl berish."},
    {"name": "Soch + soqol", "category": "Kombo", "duration": 55, "description": "Eng ko'p tanlanadigan to'liq combo xizmat."},
    {"name": "Premium combo", "category": "Kombo", "duration": 75, "description": "Soch, soqol va premium finish bir paketda."},
    {"name": "Hot towel shave", "category": "Soqol", "duration": 35, "description": "Issiq sochiq bilan premium soqol xizmati."},
    {"name": "Head wash styling", "category": "Parvarish", "duration": 25, "description": "Bosh yuvish va yakuniy styling."},
    {"name": "Keratin care", "category": "Parvarish", "duration": 50, "description": "Sochni silliqlash va yumshatish uchun keratin care."},
    {"name": "Hair coloring", "category": "Parvarish", "duration": 60, "description": "Soch rangini yangilash yoki tonlash."},
    {"name": "Face mask care", "category": "Parvarish", "duration": 25, "description": "Yuzni tozalash va niqob bilan parvarish."},
    {"name": "Scalp massage", "category": "Parvarish", "duration": 20, "description": "Bosh terisi uchun relaks massaj."},
    {"name": "Eyebrow cleanup", "category": "Parvarish", "duration": 15, "description": "Qosh atrofini tozalash va tekislash."},
    {"name": "Beard coloring", "category": "Soqol", "duration": 35, "description": "Soqol rangini tekislash va yangilash."},
    {"name": "Wedding styling", "category": "Kombo", "duration": 70, "description": "Muhim kunlar uchun silliq styling paketi."},
    {"name": "VIP grooming", "category": "Kombo", "duration": 90, "description": "Barbershopdagi eng to'liq premium xizmat."},
]

PALETTE = (
    ("#0f172a", "#2563eb"),
    ("#1f2937", "#7c3aed"),
    ("#3f3f46", "#ec4899"),
    ("#3f3f46", "#f97316"),
    ("#14532d", "#16a34a"),
    ("#1e293b", "#06b6d4"),
)


def _slugify(value: str) -> str:
    value = value.lower().strip()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-") or "service"


def _normalize_name(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", (value or "").lower())


def _build_image(name: str, index: int) -> str:
    primary, accent = PALETTE[index % len(PALETTE)]
    title = name[:26]
    svg = f"""
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 520">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="{primary}" />
      <stop offset="100%" stop-color="{accent}" />
    </linearGradient>
  </defs>
  <rect width="800" height="520" rx="36" fill="url(#bg)" />
  <circle cx="650" cy="120" r="120" fill="rgba(255,255,255,0.10)" />
  <circle cx="720" cy="420" r="110" fill="rgba(255,255,255,0.08)" />
  <rect x="72" y="78" width="156" height="48" rx="24" fill="rgba(255,255,255,0.14)" />
  <text x="100" y="110" font-family="Arial,sans-serif" font-size="24" fill="#ffffff">MB</text>
  <text x="72" y="284" font-family="Arial,sans-serif" font-size="56" font-weight="700" fill="#ffffff">{title}</text>
  <text x="72" y="334" font-family="Arial,sans-serif" font-size="24" fill="rgba(255,255,255,0.82)">MyBarber katalog</text>
  <path d="M548 170c24 0 43 19 43 43 0 10-4 20-10 28l-87 114c-8 11-20 16-33 16s-25-5-33-16l-87-114a43 43 0 0 1 33-71c16 0 30 9 37 22l12 22 12-22c7-13 21-22 37-22Z" fill="rgba(255,255,255,0.18)" />
  <path d="M425 203l-54 70m42-110-68 88m110 10 80-103m-54 134 84-109" stroke="#ffffff" stroke-width="18" stroke-linecap="round" />
</svg>
""".strip()
    return f"data:image/svg+xml;utf8,{quote(svg)}"


def _match_catalog(row_name: str, normalized_map: dict[str, object]):
    normalized = _normalize_name(row_name)
    if not normalized:
        return None
    if normalized in normalized_map:
        return normalized_map[normalized]

    matches = []
    for key, value in normalized_map.items():
        if normalized in key or key in normalized:
            matches.append((len(key), value))
    if not matches:
        return None
    matches.sort(key=lambda item: item[0], reverse=True)
    return matches[0][1]


def seed_catalog_services(apps, schema_editor):
    Category = apps.get_model("salons", "Category")
    CatalogService = apps.get_model("salons", "CatalogService")
    Service = apps.get_model("salons", "Service")
    BarberService = apps.get_model("barbers", "BarberService")

    category_map = {}
    for row in CATEGORY_ROWS:
        category, _ = Category.objects.get_or_create(
            name=row["name"],
            defaults={
                "icon": row["icon"],
                "order": row["order"],
                "is_active": True,
            },
        )
        category_map[row["name"]] = category

    catalog_map = {}
    for index, row in enumerate(SERVICE_ROWS):
        catalog, _ = CatalogService.objects.get_or_create(
            name=row["name"],
            defaults={
                "slug": _slugify(row["name"]),
                "description": row["description"],
                "image_url": _build_image(row["name"], index),
                "duration_minutes": row["duration"],
                "is_active": True,
                "sort_order": index,
            },
        )
        if not catalog.image_url:
            catalog.image_url = _build_image(catalog.name, index)
        if not catalog.slug:
            catalog.slug = _slugify(catalog.name)
        catalog.description = row["description"]
        catalog.duration_minutes = row["duration"]
        catalog.sort_order = index
        catalog.is_active = True
        catalog.save()
        catalog.categories.set([category_map[row["category"]]])
        catalog_map[_normalize_name(catalog.name)] = catalog

    for row in Service.objects.select_related("catalog_service").all():
        if row.catalog_service_id:
            continue
        catalog = _match_catalog(row.name, catalog_map)
        if catalog is None:
            continue
        row.catalog_service_id = catalog.id
        row.name = catalog.name
        row.duration_minutes = catalog.duration_minutes
        row.save(update_fields=["catalog_service", "name", "duration_minutes"])
        row.categories.set(catalog.categories.all())

    for row in BarberService.objects.select_related("catalog_service").all():
        if row.catalog_service_id:
            continue
        catalog = _match_catalog(row.name, catalog_map)
        if catalog is None:
            continue
        row.catalog_service_id = catalog.id
        row.name = catalog.name
        row.duration_minutes = catalog.duration_minutes
        row.save(update_fields=["catalog_service", "name", "duration_minutes"])
        row.categories.set(catalog.categories.all())


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("barbers", "0013_barberservice_catalog_service"),
        ("salons", "0008_catalogservice_service_catalog_service"),
    ]

    operations = [
        migrations.RunPython(seed_catalog_services, noop_reverse),
    ]
