# Generated by Django 6.0.3 on 2026-06-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0016_barber_promotion_payout_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='email_verification_invite_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Tasdiq havolasi avtomatik yuborilgan vaqt (profil sozlamalari tugaganida, bir marta).', null=True),
        ),
    ]
