# Generated by Django 6.0.6 on 2026-06-27 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0017_alter_barber_email_verification_invite_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_day_off', models.BooleanField(default=False)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('breaks', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='barbers.barberprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
