# Generated by Django 6.0.3 on 2026-07-26 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_field_agent_referral'),
        ('barbers', '0022_barber_business_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='referred_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_barbers', to='agents.fieldagent'),
        ),
    ]
