# Generated by Django 6.0.6 on 2026-07-24 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0023_barber_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='customer_invite_code',
            field=models.CharField(blank=True, db_index=True, help_text="Sartaroshning mijozlarni MySaloon'ga chaqirish kodi.", max_length=12, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BarberCustomerOutreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('phone', 'Telefon'), ('in_person', 'Jonli'), ('sms', 'SMS'), ('other', 'Boshqa')], db_index=True, default='telegram', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('joined', "Qo'shildi"), ('cancelled', 'Bekor')], db_index=True, default='pending', max_length=16)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_outreaches', to='barbers.barber')),
                ('joined_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_outreach_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BarberCustomerInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_used', models.CharField(db_index=True, max_length=12)),
                ('source', models.CharField(choices=[('link', 'Havola'), ('manual_code', 'Kod'), ('outreach', 'Outreach match')], db_index=True, default='link', max_length=16)),
                ('customer_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_phone', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invites', to='barbers.barber')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_invite_attribution', to=settings.AUTH_USER_MODEL)),
                ('outreach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='barbers.barbercustomeroutreach')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='barbercustomeroutreach',
            index=models.Index(fields=['barber', 'status', '-created_at'], name='barbers_bar_barber__78e101_idx'),
        ),
        migrations.AddIndex(
            model_name='barbercustomeroutreach',
            index=models.Index(fields=['barber', 'phone'], name='barbers_bar_barber__4d180a_idx'),
        ),
        migrations.AddIndex(
            model_name='barbercustomerinvite',
            index=models.Index(fields=['barber', '-created_at'], name='barbers_bar_barber__144923_idx'),
        ),
        migrations.AddIndex(
            model_name='barbercustomerinvite',
            index=models.Index(fields=['created_at'], name='barbers_bar_created_a302b5_idx'),
        ),
    ]
