# Generated by Django 6.0.6 on 2026-07-24 14:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0024_barber_customer_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberShopSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_code', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor'), ('deactivated', "O'chirilgan")], db_index=True, default='pending', max_length=16)),
                ('source', models.CharField(choices=[('wallet', 'Hisob raqam'), ('click', 'Click'), ('payme', 'Payme'), ('admin', 'Admin')], db_index=True, max_length=32)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('price_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entitlements', models.JSONField(blank=True, default=dict)),
                ('payment_provider', models.CharField(blank=True, default='', max_length=16)),
                ('payment_order_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('payment_transaction_id', models.CharField(blank=True, default='', max_length=128)),
                ('wallet_entry_id', models.CharField(blank=True, default='', max_length=64)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_subscriptions', to='barbers.barber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarberShopSubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('actor', models.CharField(blank=True, default='system', max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_subscription_events', to='barbers.barber')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='barbers.barbershopsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarberShopSubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_code', models.CharField(db_index=True, max_length=32)),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider', models.CharField(db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarilgan')], db_index=True, default='pending', max_length=16)),
                ('order_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('checkout_url', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_subscription_payments', to='barbers.barber')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='barbers.barbershopsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='barbershopsubscription',
            index=models.Index(fields=['barber', 'status', '-ends_at'], name='barbers_bar_barber__b11bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='barbershopsubscription',
            index=models.Index(fields=['status', 'ends_at'], name='barbers_bar_status_b27e38_idx'),
        ),
        migrations.AddIndex(
            model_name='barbershopsubscription',
            index=models.Index(fields=['plan_code', 'status'], name='barbers_bar_plan_co_af9b46_idx'),
        ),
    ]
