# Generated by Django 6.0.3 on 2026-07-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0023_field_agent_referral'),
        ('barbers', '0025_barber_shop_subscription'),
    ]

    operations = [
    ]
