# Generated by Django 6.0.3 on 2026-07-26 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_finance'),
        ('barbers', '0026_merge_20260726_1210'),
        ('salons', '0018_merge_20260726_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershopsubscription',
            name='source',
            field=models.CharField(choices=[('wallet', 'Hisob raqam'), ('click', 'Click'), ('payme', 'Payme'), ('admin', 'Admin'), ('agent_trial', 'Agent trial')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='PartnerTrialGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_key', models.CharField(db_index=True, max_length=255)),
                ('phone_key', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('code_used', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('source', models.CharField(choices=[('signup', "Ro'yxatdan o'tish"), ('claim', 'Obuna sahifasi'), ('admin', 'Admin')], db_index=True, max_length=16)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('trial_value_uzs', models.PositiveIntegerField(default=99990)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('granted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_trial_grants', to='agents.fieldagent')),
                ('barber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_trial_grant', to='barbers.barber')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_trial_grants', to='salons.salon')),
                ('shop_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_trial_grants', to='barbers.barbershopsubscription')),
            ],
            options={
                'ordering': ['-granted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('email_key', ''), _negated=True), fields=('email_key',), name='uniq_partner_trial_email_key'), models.UniqueConstraint(condition=models.Q(('phone_key', ''), _negated=True), fields=('phone_key',), name='uniq_partner_trial_phone_key')],
            },
        ),
    ]
