# Generated by Django 6.0.3 on 2026-07-26 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0027_partner_trial_grant_and_agent_trial_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnertrialgrant',
            name='barber',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_trial_grant', to='barbers.barber'),
        ),
    ]
