# Generated by Django 6.0.3 on 2026-07-20 02:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_code', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan'), ('deactivated', "O'chirilgan")], db_index=True, default='pending', max_length=16)),
                ('source', models.CharField(choices=[('wallet', 'Hamyon'), ('click', 'Click'), ('payme', 'Payme'), ('referral_trial', 'Referal sinov'), ('admin', 'Admin')], db_index=True, max_length=32)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('price_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auto_renew', models.BooleanField(default=False)),
                ('entitlements', models.JSONField(blank=True, default=dict)),
                ('payment_provider', models.CharField(blank=True, default='', max_length=16)),
                ('payment_order_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('payment_transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('wallet_entry_id', models.CharField(blank=True, default='', max_length=64)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_reason', models.CharField(blank=True, default='', max_length=255)),
                ('deactivated_by', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_code', models.CharField(db_index=True, max_length=32)),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider', models.CharField(db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarilgan')], db_index=True, default='pending', max_length=16)),
                ('order_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('checkout_url', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.usersubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('checkout', 'Checkout'), ('payment_paid', "To'lov tasdiqlandi"), ('activated', 'Faollashtirildi'), ('renewed', 'Yangilandi'), ('expired', 'Muddati tugadi'), ('cancelled', 'Bekor'), ('deactivated', "O'chirildi"), ('reactivated', 'Qayta yoqildi'), ('usage', 'Foydalanish'), ('limit_hit', 'Limit tugadi'), ('referral_trial', 'Referal sinov'), ('admin_grant', 'Admin berdi'), ('admin_note', 'Admin izoh')], db_index=True, max_length=32)),
                ('actor', models.CharField(blank=True, default='system', max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_events', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='subscriptions.usersubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralTrialGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_count_at_grant', models.PositiveIntegerField(default=0)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_trial_grant', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_grants', to='subscriptions.usersubscription')),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsagePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('morph_ai_used', models.PositiveIntegerField(default=0)),
                ('morph_studio_used', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_usage_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-period_start'], name='subscriptio_user_id_f8d790_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'period_start'), name='uniq_subscription_usage_user_period')],
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status', '-ends_at'], name='subscriptio_user_id_f8c18e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'ends_at'], name='subscriptio_status_4c9d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['plan_code', 'status'], name='subscriptio_plan_co_d24995_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['action', '-created_at'], name='subscriptio_action_667f03_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['user', '-created_at'], name='subscriptio_user_id_972750_idx'),
        ),
    ]
