/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as GiftcardRouteImport } from './routes/giftcard'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FavoriteStylistsRouteImport } from './routes/favorite-stylists'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiStyleRouteImport } from './routes/ai-style'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletTopUpRouteImport } from './routes/wallet_.top-up'
import { Route as SalonIdRouteImport } from './routes/salon.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as BookingSalonIdRouteImport } from './routes/booking.$salonId'
import { Route as AccountPreferencesRouteImport } from './routes/account.preferences'
import { Route as AccountPaymentsRouteImport } from './routes/account.payments'
import { Route as AccountHouseholdRouteImport } from './routes/account.household'
import { Route as AccountActivityRouteImport } from './routes/account.activity'
import { Route as BookingBarberBarberIdRouteImport } from './routes/booking.barber.$barberId'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftcardRoute = GiftcardRouteImport.update({
  id: '/giftcard',
  path: '/giftcard',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriteStylistsRoute = FavoriteStylistsRouteImport.update({
  id: '/favorite-stylists',
  path: '/favorite-stylists',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStyleRoute = AiStyleRouteImport.update({
  id: '/ai-style',
  path: '/ai-style',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletTopUpRoute = WalletTopUpRouteImport.update({
  id: '/wallet_/top-up',
  path: '/wallet/top-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonIdRoute = SalonIdRouteImport.update({
  id: '/salon/$id',
  path: '/salon/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatRoute,
} as any)
const BookingSalonIdRoute = BookingSalonIdRouteImport.update({
  id: '/booking/$salonId',
  path: '/booking/$salonId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPreferencesRoute = AccountPreferencesRouteImport.update({
  id: '/account/preferences',
  path: '/account/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPaymentsRoute = AccountPaymentsRouteImport.update({
  id: '/account/payments',
  path: '/account/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountHouseholdRoute = AccountHouseholdRouteImport.update({
  id: '/account/household',
  path: '/account/household',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountActivityRoute = AccountActivityRouteImport.update({
  id: '/account/activity',
  path: '/account/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBarberBarberIdRoute = BookingBarberBarberIdRouteImport.update({
  id: '/booking/barber/$barberId',
  path: '/booking/barber/$barberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/ai-style': typeof AiStyleRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRouteWithChildren
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/family': typeof FamilyRoute
  '/favorite-stylists': typeof FavoriteStylistsRoute
  '/favorites': typeof FavoritesRoute
  '/giftcard': typeof GiftcardRoute
  '/loyalty': typeof LoyaltyRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/today': typeof TodayRoute
  '/wallet': typeof WalletRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/household': typeof AccountHouseholdRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/booking/$salonId': typeof BookingSalonIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/salon/$id': typeof SalonIdRoute
  '/wallet/top-up': typeof WalletTopUpRoute
  '/booking/barber/$barberId': typeof BookingBarberBarberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/ai-style': typeof AiStyleRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRouteWithChildren
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/family': typeof FamilyRoute
  '/favorite-stylists': typeof FavoriteStylistsRoute
  '/favorites': typeof FavoritesRoute
  '/giftcard': typeof GiftcardRoute
  '/loyalty': typeof LoyaltyRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/today': typeof TodayRoute
  '/wallet': typeof WalletRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/household': typeof AccountHouseholdRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/booking/$salonId': typeof BookingSalonIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/salon/$id': typeof SalonIdRoute
  '/wallet/top-up': typeof WalletTopUpRoute
  '/booking/barber/$barberId': typeof BookingBarberBarberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/ai-style': typeof AiStyleRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRouteWithChildren
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/family': typeof FamilyRoute
  '/favorite-stylists': typeof FavoriteStylistsRoute
  '/favorites': typeof FavoritesRoute
  '/giftcard': typeof GiftcardRoute
  '/loyalty': typeof LoyaltyRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/today': typeof TodayRoute
  '/wallet': typeof WalletRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/household': typeof AccountHouseholdRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/booking/$salonId': typeof BookingSalonIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/salon/$id': typeof SalonIdRoute
  '/wallet_/top-up': typeof WalletTopUpRoute
  '/booking/barber/$barberId': typeof BookingBarberBarberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/ai-style'
    | '/auth'
    | '/bookings'
    | '/chat'
    | '/compare'
    | '/explore'
    | '/family'
    | '/favorite-stylists'
    | '/favorites'
    | '/giftcard'
    | '/loyalty'
    | '/map'
    | '/notifications'
    | '/offers'
    | '/payment-methods'
    | '/privacy'
    | '/profile'
    | '/reels'
    | '/reviews'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/today'
    | '/wallet'
    | '/account/activity'
    | '/account/household'
    | '/account/payments'
    | '/account/preferences'
    | '/booking/$salonId'
    | '/chat/$id'
    | '/salon/$id'
    | '/wallet/top-up'
    | '/booking/barber/$barberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/ai-style'
    | '/auth'
    | '/bookings'
    | '/chat'
    | '/compare'
    | '/explore'
    | '/family'
    | '/favorite-stylists'
    | '/favorites'
    | '/giftcard'
    | '/loyalty'
    | '/map'
    | '/notifications'
    | '/offers'
    | '/payment-methods'
    | '/privacy'
    | '/profile'
    | '/reels'
    | '/reviews'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/today'
    | '/wallet'
    | '/account/activity'
    | '/account/household'
    | '/account/payments'
    | '/account/preferences'
    | '/booking/$salonId'
    | '/chat/$id'
    | '/salon/$id'
    | '/wallet/top-up'
    | '/booking/barber/$barberId'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/ai-style'
    | '/auth'
    | '/bookings'
    | '/chat'
    | '/compare'
    | '/explore'
    | '/family'
    | '/favorite-stylists'
    | '/favorites'
    | '/giftcard'
    | '/loyalty'
    | '/map'
    | '/notifications'
    | '/offers'
    | '/payment-methods'
    | '/privacy'
    | '/profile'
    | '/reels'
    | '/reviews'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/today'
    | '/wallet'
    | '/account/activity'
    | '/account/household'
    | '/account/payments'
    | '/account/preferences'
    | '/booking/$salonId'
    | '/chat/$id'
    | '/salon/$id'
    | '/wallet_/top-up'
    | '/booking/barber/$barberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRoute
  AiStyleRoute: typeof AiStyleRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  ChatRoute: typeof ChatRouteWithChildren
  CompareRoute: typeof CompareRoute
  ExploreRoute: typeof ExploreRoute
  FamilyRoute: typeof FamilyRoute
  FavoriteStylistsRoute: typeof FavoriteStylistsRoute
  FavoritesRoute: typeof FavoritesRoute
  GiftcardRoute: typeof GiftcardRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReelsRoute: typeof ReelsRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SupportRoute: typeof SupportRoute
  TodayRoute: typeof TodayRoute
  WalletRoute: typeof WalletRoute
  AccountActivityRoute: typeof AccountActivityRoute
  AccountHouseholdRoute: typeof AccountHouseholdRoute
  AccountPaymentsRoute: typeof AccountPaymentsRoute
  AccountPreferencesRoute: typeof AccountPreferencesRoute
  BookingSalonIdRoute: typeof BookingSalonIdRoute
  SalonIdRoute: typeof SalonIdRoute
  WalletTopUpRoute: typeof WalletTopUpRoute
  BookingBarberBarberIdRoute: typeof BookingBarberBarberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giftcard': {
      id: '/giftcard'
      path: '/giftcard'
      fullPath: '/giftcard'
      preLoaderRoute: typeof GiftcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite-stylists': {
      id: '/favorite-stylists'
      path: '/favorite-stylists'
      fullPath: '/favorite-stylists'
      preLoaderRoute: typeof FavoriteStylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-style': {
      id: '/ai-style'
      path: '/ai-style'
      fullPath: '/ai-style'
      preLoaderRoute: typeof AiStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet_/top-up': {
      id: '/wallet_/top-up'
      path: '/wallet/top-up'
      fullPath: '/wallet/top-up'
      preLoaderRoute: typeof WalletTopUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon/$id': {
      id: '/salon/$id'
      path: '/salon/$id'
      fullPath: '/salon/$id'
      preLoaderRoute: typeof SalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/booking/$salonId': {
      id: '/booking/$salonId'
      path: '/booking/$salonId'
      fullPath: '/booking/$salonId'
      preLoaderRoute: typeof BookingSalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/preferences': {
      id: '/account/preferences'
      path: '/account/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof AccountPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/payments': {
      id: '/account/payments'
      path: '/account/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AccountPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/household': {
      id: '/account/household'
      path: '/account/household'
      fullPath: '/account/household'
      preLoaderRoute: typeof AccountHouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/activity': {
      id: '/account/activity'
      path: '/account/activity'
      fullPath: '/account/activity'
      preLoaderRoute: typeof AccountActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/barber/$barberId': {
      id: '/booking/barber/$barberId'
      path: '/booking/barber/$barberId'
      fullPath: '/booking/barber/$barberId'
      preLoaderRoute: typeof BookingBarberBarberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatIdRoute: typeof ChatIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIdRoute: ChatIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
  AiStyleRoute: AiStyleRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  ChatRoute: ChatRouteWithChildren,
  CompareRoute: CompareRoute,
  ExploreRoute: ExploreRoute,
  FamilyRoute: FamilyRoute,
  FavoriteStylistsRoute: FavoriteStylistsRoute,
  FavoritesRoute: FavoritesRoute,
  GiftcardRoute: GiftcardRoute,
  LoyaltyRoute: LoyaltyRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReelsRoute: ReelsRoute,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SupportRoute: SupportRoute,
  TodayRoute: TodayRoute,
  WalletRoute: WalletRoute,
  AccountActivityRoute: AccountActivityRoute,
  AccountHouseholdRoute: AccountHouseholdRoute,
  AccountPaymentsRoute: AccountPaymentsRoute,
  AccountPreferencesRoute: AccountPreferencesRoute,
  BookingSalonIdRoute: BookingSalonIdRoute,
  SalonIdRoute: SalonIdRoute,
  WalletTopUpRoute: WalletTopUpRoute,
  BookingBarberBarberIdRoute: BookingBarberBarberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
