"""Yangi Explore erkak uslublari — 20 ta (Irland to'ldirish)."""

from __future__ import annotations

# Klassik 12 dan tashqari yangi to'lqin — sluglar MEN_CATALOG ga qo'shiladi.
NEW_MEN_HAIRSTYLE_SEED: list[dict] = [
    {
        "style_id": "men-crew-cut",
        "slug": "crew-cut",
        "audience": "men",
        "category": "barber",
        "title": "Crew Cut",
        "title_uz": "Crew Cut",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/crew-cut.webp",
        "description_uz": "Klassik crew cut — tepada biroz uzunroq, yonlar qisqa, sportiv va toza.",
        "tags": ["short", "classic", "military"],
        "age_groups": ["teen", "young", "adult", "mature"],
        "sort_order": 12,
    },
    {
        "style_id": "men-high-fade",
        "slug": "high-fade",
        "audience": "men",
        "category": "barber",
        "title": "High Fade",
        "title_uz": "High Fade",
        "face_shapes": ["oval", "square"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/high-fade.webp",
        "description_uz": "Yuqori fade — keskin kontrast, tepada tekstura, jasur zamonaviy uslub.",
        "tags": ["fade", "bold", "modern"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 13,
    },
    {
        "style_id": "men-taper-cut",
        "slug": "taper-cut",
        "audience": "men",
        "category": "barber",
        "title": "Taper Cut",
        "title_uz": "Taper Cut",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/taper-cut.webp",
        "description_uz": "Yumshoq taper — tabiiy o'tish, professional va kundalik ko'rinish.",
        "tags": ["taper", "classic", "neat"],
        "age_groups": ["young", "adult", "mature"],
        "sort_order": 14,
    },
    {
        "style_id": "men-quiff",
        "slug": "quiff",
        "audience": "men",
        "category": "barber",
        "title": "Quiff",
        "title_uz": "Quiff",
        "face_shapes": ["oval", "square"],
        "hair_length": "medium",
        "image_path": "/hairstyles/men/personas/irland/quiff.webp",
        "description_uz": "Quiff — oldinga va yuqoriga ko'tarilgan hajm, yonlar fade, dadil siluet.",
        "tags": ["volume", "modern", "bold"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 15,
    },
    {
        "style_id": "men-ivy-league",
        "slug": "ivy-league",
        "audience": "men",
        "category": "barber",
        "title": "Ivy League",
        "title_uz": "Ivy League",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/ivy-league.webp",
        "description_uz": "Ivy League — qisqa tepada tarash mumkin, nazokatli kollej klassikasi.",
        "tags": ["classic", "preppy", "neat"],
        "age_groups": ["young", "adult", "mature"],
        "sort_order": 16,
    },
    {
        "style_id": "men-caesar-cut",
        "slug": "caesar-cut",
        "audience": "men",
        "category": "barber",
        "title": "Caesar Cut",
        "title_uz": "Caesar Cut",
        "face_shapes": ["oval", "round", "square"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/caesar-cut.webp",
        "description_uz": "Caesar — gorizontal old chelka, tekis qisqa uzunlik, Rim klassikasi.",
        "tags": ["short", "classic", "fringe"],
        "age_groups": ["teen", "young", "adult", "mature"],
        "sort_order": 17,
    },
    {
        "style_id": "men-bro-flow",
        "slug": "bro-flow",
        "audience": "men",
        "category": "barber",
        "title": "Bro Flow",
        "title_uz": "Bro Flow",
        "face_shapes": ["oval", "square"],
        "hair_length": "medium",
        "image_path": "/hairstyles/men/personas/irland/bro-flow.webp",
        "description_uz": "Bro flow — o'rta uzunlikda orqaga oqadigan soch, sportiv va erkin.",
        "tags": ["flow", "medium", "casual"],
        "age_groups": ["teen", "young"],
        "sort_order": 18,
    },
    {
        "style_id": "men-curtain-fringe",
        "slug": "curtain-fringe",
        "audience": "men",
        "category": "barber",
        "title": "Curtain Fringe",
        "title_uz": "Curtain Fringe",
        "face_shapes": ["oval", "round"],
        "hair_length": "medium",
        "image_path": "/hairstyles/men/personas/irland/curtain-fringe.webp",
        "description_uz": "Curtain fringe — o'rtadan ochilgan chelka, yumshoq oqim, 90s revival.",
        "tags": ["fringe", "trendy", "medium"],
        "age_groups": ["teen", "young"],
        "sort_order": 19,
    },
    {
        "style_id": "men-textured-fringe",
        "slug": "textured-fringe",
        "audience": "men",
        "category": "barber",
        "title": "Textured Fringe",
        "title_uz": "Textured Fringe",
        "face_shapes": ["oval", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/textured-fringe.webp",
        "description_uz": "Teksturali chelka — oldinga tushgan soch, fade yonlar, yosh va dinamik.",
        "tags": ["fringe", "textured", "modern"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 20,
    },
    {
        "style_id": "men-drop-fade",
        "slug": "drop-fade",
        "audience": "men",
        "category": "barber",
        "title": "Drop Fade",
        "title_uz": "Drop Fade",
        "face_shapes": ["oval", "square"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/drop-fade.webp",
        "description_uz": "Drop fade — quloq orqasida pastga tushadigan fade chizig'i, premium barber.",
        "tags": ["fade", "precision", "modern"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 21,
    },
    {
        "style_id": "men-burst-fade",
        "slug": "burst-fade",
        "audience": "men",
        "category": "barber",
        "title": "Burst Fade",
        "title_uz": "Burst Fade",
        "face_shapes": ["oval", "square"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/burst-fade.webp",
        "description_uz": "Burst fade — quloq atrofida yumaloq fade, tepada hajm yoki jingalak.",
        "tags": ["fade", "bold", "trendy"],
        "age_groups": ["teen", "young"],
        "sort_order": 22,
    },
    {
        "style_id": "men-high-and-tight",
        "slug": "high-and-tight",
        "audience": "men",
        "category": "barber",
        "title": "High and Tight",
        "title_uz": "High and Tight",
        "face_shapes": ["oval", "square"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/high-and-tight.webp",
        "description_uz": "High and tight — juda qisqa yonlar, qisqa tepa, harbiy tartib.",
        "tags": ["short", "military", "minimal"],
        "age_groups": ["young", "adult", "mature"],
        "sort_order": 23,
    },
    {
        "style_id": "men-classic-taper",
        "slug": "classic-taper",
        "audience": "men",
        "category": "barber",
        "title": "Classic Taper",
        "title_uz": "Classic Taper",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/classic-taper.webp",
        "description_uz": "Klassik taper — yumshoq yonlar, tartibli tepa, ofisga mos.",
        "tags": ["classic", "professional", "neat"],
        "age_groups": ["young", "adult", "mature"],
        "sort_order": 24,
    },
    {
        "style_id": "men-soft-quiff",
        "slug": "soft-quiff",
        "audience": "men",
        "category": "barber",
        "title": "Soft Quiff",
        "title_uz": "Soft Quiff",
        "face_shapes": ["oval", "round"],
        "hair_length": "medium",
        "image_path": "/hairstyles/men/personas/irland/soft-quiff.webp",
        "description_uz": "Yumshoq quiff — engil hajm oldinga, tabiiy tekstura, kundalik shik.",
        "tags": ["quiff", "soft", "modern"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 25,
    },
    {
        "style_id": "men-forward-fringe",
        "slug": "forward-fringe",
        "audience": "men",
        "category": "barber",
        "title": "Forward Fringe",
        "title_uz": "Forward Fringe",
        "face_shapes": ["oval", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/forward-fringe.webp",
        "description_uz": "Forward fringe — peshonaga tushgan qisqa chelka, fade yonlar.",
        "tags": ["fringe", "modern", "youth"],
        "age_groups": ["teen", "young"],
        "sort_order": 26,
    },
    {
        "style_id": "men-layered-medium",
        "slug": "layered-medium",
        "audience": "men",
        "category": "barber",
        "title": "Layered Medium",
        "title_uz": "Layered Medium",
        "face_shapes": ["oval", "square"],
        "hair_length": "medium",
        "image_path": "/hairstyles/men/personas/irland/layered-medium.webp",
        "description_uz": "O'rta qatlamli soch — harakat va hajm, yumshoq uchlar.",
        "tags": ["layers", "medium", "textured"],
        "age_groups": ["young", "adult"],
        "sort_order": 27,
    },
    {
        "style_id": "men-comb-over-fade",
        "slug": "comb-over-fade",
        "audience": "men",
        "category": "barber",
        "title": "Comb Over Fade",
        "title_uz": "Comb Over Fade",
        "face_shapes": ["oval", "square"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/comb-over-fade.webp",
        "description_uz": "Comb over + fade — yonboshga taralgan tepa, toza fade yonlar.",
        "tags": ["comb-over", "fade", "classic"],
        "age_groups": ["young", "adult", "mature"],
        "sort_order": 28,
    },
    {
        "style_id": "men-faux-hawk",
        "slug": "faux-hawk",
        "audience": "men",
        "category": "barber",
        "title": "Faux Hawk",
        "title_uz": "Faux Hawk",
        "face_shapes": ["oval", "square"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/faux-hawk.webp",
        "description_uz": "Faux hawk — markazda biroz balandroq chiziq, yonlar qisqa, edgy.",
        "tags": ["bold", "modern", "edgy"],
        "age_groups": ["teen", "young"],
        "sort_order": 29,
    },
    {
        "style_id": "men-messy-fringe",
        "slug": "messy-fringe",
        "audience": "men",
        "category": "barber",
        "title": "Messy Fringe",
        "title_uz": "Messy Fringe",
        "face_shapes": ["oval", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/messy-fringe.webp",
        "description_uz": "Messy fringe — erkin chalkash chelka, mat tekstura, casual vibe.",
        "tags": ["messy", "fringe", "casual"],
        "age_groups": ["teen", "young"],
        "sort_order": 30,
    },
    {
        "style_id": "men-disconnected-crop",
        "slug": "disconnected-crop",
        "audience": "men",
        "category": "barber",
        "title": "Disconnected Crop",
        "title_uz": "Disconnected Crop",
        "face_shapes": ["oval", "square"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/disconnected-crop.webp",
        "description_uz": "Disconnected crop — tepada crop, yonlar keskin uzilgan, kontrast kuchli.",
        "tags": ["crop", "disconnected", "bold"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 31,
    },
]

NEW_MEN_STYLE_SLUGS: tuple[str, ...] = tuple(row["slug"] for row in NEW_MEN_HAIRSTYLE_SEED)

NEW_MEN_STYLE_PROMPTS: dict[str, str] = {
    "crew-cut": "classic crew cut slightly longer on top short tapered sides neat military-inspired",
    "high-fade": "high fade haircut tall fade line short textured top sharp lineup",
    "taper-cut": "classic taper cut soft natural blend short neat top professional",
    "quiff": "modern quiff volume swept up and forward faded sides strong silhouette",
    "ivy-league": "ivy league haircut short top longer than crew cut neat partable sides tapered",
    "caesar-cut": "caesar cut short horizontal fringe flat top length even all over classic",
    "bro-flow": "bro flow medium length hair flowing back off the face soft layers athletic",
    "curtain-fringe": "curtain fringe middle part soft curtains falling either side of face medium length",
    "textured-fringe": "textured fringe short faded sides choppy forward fringe matte texture",
    "drop-fade": "drop fade curved fade line dropping behind the ear short textured top",
    "burst-fade": "burst fade circular fade around the ear short or curly top preserved",
    "high-and-tight": "high and tight very short sides short cropped top clean military look",
    "classic-taper": "classic gentleman taper neat short sides softly blended tidy top",
    "soft-quiff": "soft quiff gentle lift at the front natural texture low fade sides",
    "forward-fringe": "forward fringe short fringe falling onto forehead faded sides modern",
    "layered-medium": "medium layered men's haircut movement through layers soft ends",
    "comb-over-fade": "comb over fade side-swept top clean mid fade sides polished",
    "faux-hawk": "faux hawk ridge of longer hair down the center short tapered sides edgy",
    "messy-fringe": "messy fringe tousled forward fringe textured top casual matte finish",
    "disconnected-crop": "disconnected crop textured crop on top hard disconnect to short sides",
}
