"""Boshlang'ich Explore soch uslublari — faqat persona assetlari mavjud bo'lganlar."""

from __future__ import annotations

# Yosh guruhlari: kids (10–12), teen (13–17), young (18–29), adult (30–44), mature (45+)

HAIRSTYLE_SEED: list[dict] = [
    {
        "style_id": "men-mid-fade",
        "slug": "mid-fade",
        "audience": "men",
        "category": "barber",
        "title": "Mid Fade",
        "title_uz": "Mid Fade",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/evro/mid-fade.webp",
        "description_uz": "O'rta balandlikdagi fade — yuz konturini yumshatadi, zamonaviy va toza ko'rinish.",
        "tags": ["fade", "modern", "barber"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 0,
    },
    {
        "style_id": "men-skin-fade",
        "slug": "skin-fade",
        "audience": "men",
        "category": "barber",
        "title": "Skin Fade",
        "title_uz": "Skin Fade",
        "face_shapes": ["oval", "square"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/evro/skin-fade.webp",
        "description_uz": "Zero fade — keskin siluet, jasur va zamonaviy uslub.",
        "tags": ["fade", "bold"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 1,
    },
    {
        "style_id": "men-buzz-cut",
        "slug": "buzz-cut",
        "audience": "men",
        "category": "barber",
        "title": "Buzz Cut",
        "title_uz": "Buzz Cut",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/evro/buzz-cut.webp",
        "description_uz": "Qisqa va amaliy — minimal parvarish, sportiv ko'rinish.",
        "tags": ["short", "minimal"],
        "age_groups": ["kids", "teen", "young", "adult", "mature"],
        "sort_order": 2,
    },
    {
        "style_id": "men-textured-crop",
        "slug": "textured-crop",
        "audience": "men",
        "category": "barber",
        "title": "Textured Crop",
        "title_uz": "Textured Crop",
        "face_shapes": ["oval", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/evro/textured-crop.webp",
        "description_uz": "Teksturali crop — hajm tepada, yonlar qisqa, yosh va zamonaviy.",
        "tags": ["crop", "textured", "modern"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 3,
    },
]
