"""Boshlang'ich Explore soch uslublari — faqat persona assetlari mavjud bo'lganlar."""

from __future__ import annotations

# Yosh guruhlari: kids (10–12), teen (13–17), young (18–29), adult (30–44), mature (45+)

HAIRSTYLE_SEED: list[dict] = [
    {
        "style_id": "men-mid-fade",
        "slug": "mid-fade",
        "audience": "men",
        "category": "barber",
        "title": "Mid Fade",
        "title_uz": "Mid Fade",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/mid-fade.webp",
        "description_uz": "O'rta balandlikdagi fade — yuz konturini yumshatadi, zamonaviy va toza ko'rinish.",
        "tags": ["fade", "modern", "barber"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 0,
    },
    {
        "style_id": "men-skin-fade",
        "slug": "skin-fade",
        "audience": "men",
        "category": "barber",
        "title": "Skin Fade",
        "title_uz": "Skin Fade",
        "face_shapes": ["oval", "square"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/skin-fade.webp",
        "description_uz": "Zero fade — keskin siluet, jasur va zamonaviy uslub.",
        "tags": ["fade", "bold"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 1,
    },
    {
        "style_id": "men-buzz-cut",
        "slug": "buzz-cut",
        "audience": "men",
        "category": "barber",
        "title": "Buzz Cut",
        "title_uz": "Buzz Cut",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/buzz-cut.webp",
        "description_uz": "Qisqa va amaliy — minimal parvarish, sportiv ko'rinish.",
        "tags": ["short", "minimal"],
        "age_groups": ["kids", "teen", "young", "adult", "mature"],
        "sort_order": 2,
    },
    {
        "style_id": "men-textured-crop",
        "slug": "textured-crop",
        "audience": "men",
        "category": "barber",
        "title": "Textured Crop",
        "title_uz": "Textured Crop",
        "face_shapes": ["oval", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/textured-crop.webp",
        "description_uz": "Teksturali crop — hajm tepada, yonlar qisqa, yosh va zamonaviy.",
        "tags": ["crop", "textured", "modern"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 3,
    },
    {
        "style_id": "men-low-fade",
        "slug": "low-fade",
        "audience": "men",
        "category": "barber",
        "title": "Low Fade",
        "title_uz": "Low Fade",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/low-fade.webp",
        "description_uz": "Past fade — tabiiy o'tish, tartibli va nazokatli ko'rinish.",
        "tags": ["fade", "classic", "barber"],
        "age_groups": ["teen", "young", "adult", "mature"],
        "sort_order": 4,
    },
    {
        "style_id": "men-pompadour",
        "slug": "pompadour",
        "audience": "men",
        "category": "barber",
        "title": "Pompadour",
        "title_uz": "Pompadur",
        "face_shapes": ["oval", "square"],
        "hair_length": "medium",
        "image_path": "/hairstyles/men/personas/irland/pompadour.webp",
        "description_uz": "Pompadur — tepada hajm yuqoriga taralgan, yonlar fade, dadil klassika.",
        "tags": ["volume", "classic", "bold"],
        "age_groups": ["young", "adult"],
        "sort_order": 5,
    },
    {
        "style_id": "men-undercut",
        "slug": "undercut",
        "audience": "men",
        "category": "barber",
        "title": "Undercut",
        "title_uz": "Undercut",
        "face_shapes": ["oval", "square"],
        "hair_length": "medium",
        "image_path": "/hairstyles/men/personas/irland/undercut.webp",
        "description_uz": "Undercut — qisqa yonlar, uzun tepa, keskin kontrast va zamonaviy uslub.",
        "tags": ["undercut", "modern", "bold"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 6,
    },
    {
        "style_id": "men-side-part",
        "slug": "side-part",
        "audience": "men",
        "category": "barber",
        "title": "Side Part",
        "title_uz": "Side Part",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/side-part.webp",
        "description_uz": "Klassik side part — toza yonbosh ajratma, tartibli va professional ko'rinish.",
        "tags": ["classic", "professional", "neat"],
        "age_groups": ["young", "adult", "mature"],
        "sort_order": 7,
    },
    {
        "style_id": "men-french-crop",
        "slug": "french-crop",
        "audience": "men",
        "category": "barber",
        "title": "French Crop",
        "title_uz": "French Crop",
        "face_shapes": ["oval", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/personas/irland/french-crop.webp",
        "description_uz": "French crop — qisqa old chelka, fade yonlar, kam parvarish, zamonaviy.",
        "tags": ["crop", "modern", "low-maintenance"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 8,
    },
    {
        "style_id": "men-slick-back",
        "slug": "slick-back",
        "audience": "men",
        "category": "barber",
        "title": "Slick Back",
        "title_uz": "Slick Back",
        "face_shapes": ["oval", "square"],
        "hair_length": "medium",
        "image_path": "/hairstyles/men/personas/irland/slick-back.webp",
        "description_uz": "Slick back — orqaga taralgan soch, pomada yaltirog'i, nafis va dadil.",
        "tags": ["classic", "sleek", "bold"],
        "age_groups": ["young", "adult", "mature"],
        "sort_order": 9,
    },
    {
        "style_id": "men-curly-top-fade",
        "slug": "curly-top-fade",
        "audience": "men",
        "category": "barber",
        "title": "Curly Top Fade",
        "title_uz": "Curly Top Fade",
        "face_shapes": ["oval", "round"],
        "hair_length": "medium",
        "image_path": "/hairstyles/men/personas/irland/curly-top-fade.webp",
        "description_uz": "Jingalak tepa + fade — tabiiy jingalaklar tepada, yonlar toza fade.",
        "tags": ["curly", "fade", "modern"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 10,
    },
    {
        "style_id": "men-modern-mullet",
        "slug": "modern-mullet",
        "audience": "men",
        "category": "barber",
        "title": "Modern Mullet",
        "title_uz": "Modern Mullet",
        "face_shapes": ["oval", "square"],
        "hair_length": "medium",
        "image_path": "/hairstyles/men/personas/irland/modern-mullet.webp",
        "description_uz": "Zamonaviy mullet — qisqa old, fade yonlar, uzunroq orqa, trend uslub.",
        "tags": ["mullet", "trendy", "bold"],
        "age_groups": ["teen", "young"],
        "sort_order": 11,
    },
]
