"""Boshlang'ich Explore soch uslublari — migration va seed command uchun."""

from __future__ import annotations

# Yosh guruhlari: kids (10–12), teen (13–17), young (18–29), adult (30–44), mature (45+)

HAIRSTYLE_SEED: list[dict] = [
    {
        "style_id": "men-mid-fade",
        "slug": "mid-fade",
        "audience": "men",
        "category": "barber",
        "title": "Mid Fade",
        "title_uz": "Mid Fade",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/mid-fade.webp",
        "description_uz": "O'rta balandlikdagi fade — yuz konturini yumshatadi, zamonaviy va toza ko'rinish.",
        "tags": ["fade", "modern", "barber"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 0,
    },
    {
        "style_id": "men-low-fade",
        "slug": "low-fade",
        "audience": "men",
        "category": "barber",
        "title": "Low Fade",
        "title_uz": "Low Fade",
        "face_shapes": ["oval", "square"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/low-fade.webp",
        "description_uz": "Past fade — tabiiy o'tish, kundalik parvarish oson.",
        "tags": ["fade", "classic"],
        "age_groups": ["teen", "young", "adult", "mature"],
        "sort_order": 1,
    },
    {
        "style_id": "men-skin-fade",
        "slug": "skin-fade",
        "audience": "men",
        "category": "barber",
        "title": "Skin Fade",
        "title_uz": "Skin Fade",
        "face_shapes": ["oval", "square"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/skin-fade.webp",
        "description_uz": "Zero fade — keskin siluet, jasur va zamonaviy uslub.",
        "tags": ["fade", "bold"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 2,
    },
    {
        "style_id": "men-buzz-cut",
        "slug": "buzz-cut",
        "audience": "men",
        "category": "barber",
        "title": "Buzz Cut",
        "title_uz": "Buzz Cut",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/buzz-cut.webp",
        "description_uz": "Qisqa va amaliy — minimal parvarish, sportiv ko'rinish.",
        "tags": ["short", "minimal"],
        "age_groups": ["kids", "teen", "young", "adult", "mature"],
        "sort_order": 3,
    },
    {
        "style_id": "men-textured-crop",
        "slug": "textured-crop",
        "audience": "men",
        "category": "barber",
        "title": "Textured Crop",
        "title_uz": "Textured Crop",
        "face_shapes": ["oval", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/textured-crop.webp",
        "description_uz": "Teksturali crop — hajm tepada, yonlar qisqa, yosh va zamonaviy.",
        "tags": ["crop", "textured", "modern"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 4,
    },
    {
        "style_id": "men-pompadour",
        "slug": "pompadour",
        "audience": "men",
        "category": "barber",
        "title": "Pompadour",
        "title_uz": "Pompadour",
        "face_shapes": ["oval", "square"],
        "hair_length": "medium",
        "image_path": "/hairstyles/men/pompadour.webp",
        "description_uz": "Tepada hajm — klassik va nafis, burchak yuz uchun ajoyib balans.",
        "tags": ["volume", "classic"],
        "age_groups": ["young", "adult"],
        "sort_order": 5,
    },
    {
        "style_id": "men-undercut",
        "slug": "undercut",
        "audience": "men",
        "category": "barber",
        "title": "Undercut",
        "title_uz": "Undercut",
        "face_shapes": ["oval", "square"],
        "hair_length": "medium",
        "image_path": "/hairstyles/men/undercut.webp",
        "description_uz": "Yonlar qisqa, tepa uzunroq — kontrastli zamonaviy uslub.",
        "tags": ["undercut", "contrast"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 6,
    },
    {
        "style_id": "men-side-part",
        "slug": "side-part",
        "audience": "men",
        "category": "barber",
        "title": "Classic Side Part",
        "title_uz": "Klassik side part",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/side-part.webp",
        "description_uz": "Klassik yon chiziq — doimiy trend, rasmiy va kundalik uchun mos.",
        "tags": ["classic", "neat"],
        "age_groups": ["kids", "teen", "young", "adult", "mature"],
        "sort_order": 7,
    },
    {
        "style_id": "men-french-crop",
        "slug": "french-crop",
        "audience": "men",
        "category": "barber",
        "title": "French Crop",
        "title_uz": "French Crop",
        "face_shapes": ["oval", "round", "square"],
        "hair_length": "short",
        "image_path": "/hairstyles/men/french-crop.webp",
        "description_uz": "Qisqa old chiziq — yosh ko'rinish, oson ushlash.",
        "tags": ["crop", "fringe"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 8,
    },
    {
        "style_id": "men-slick-back",
        "slug": "slick-back",
        "audience": "men",
        "category": "barber",
        "title": "Slick Back",
        "title_uz": "Slick Back",
        "face_shapes": ["oval", "square"],
        "hair_length": "medium",
        "image_path": "/hairstyles/men/slick-back.webp",
        "description_uz": "Orqaga taralgan soch — nafis va ishonchli ko'rinish.",
        "tags": ["slick", "formal"],
        "age_groups": ["young", "adult", "mature"],
        "sort_order": 9,
    },
    {
        "style_id": "men-curly-top-fade",
        "slug": "curly-top-fade",
        "audience": "men",
        "category": "barber",
        "title": "Curly Top Fade",
        "title_uz": "Curly Top Fade",
        "face_shapes": ["oval", "round"],
        "hair_length": "medium",
        "image_path": "/hairstyles/men/curly-top-fade.webp",
        "description_uz": "Tepada jingalak soch + fade yonlar — tabiiy hajm va struktura.",
        "tags": ["curly", "fade"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 10,
    },
    {
        "style_id": "men-modern-mullet",
        "slug": "modern-mullet",
        "audience": "men",
        "category": "barber",
        "title": "Modern Mullet",
        "title_uz": "Modern Mullet",
        "face_shapes": ["oval", "square"],
        "hair_length": "long",
        "image_path": "/hairstyles/men/modern-mullet.webp",
        "description_uz": "Zamonaviy mullet — old qisqa, orqa uzunroq, trend uslub.",
        "tags": ["mullet", "trend"],
        "age_groups": ["teen", "young"],
        "sort_order": 11,
    },
    {
        "style_id": "women-soft-bob",
        "slug": "soft-bob",
        "audience": "women",
        "category": "beauty",
        "title": "Soft Bob",
        "title_uz": "Soft Bob",
        "face_shapes": ["oval", "round", "square"],
        "hair_length": "medium",
        "image_path": "/hairstyles/women/soft-bob.webp",
        "description_uz": "Yumshoq bob — yuz ramkasini chiroyli beradi, har qanday vaziyatga mos.",
        "tags": ["bob", "soft"],
        "age_groups": ["teen", "young", "adult", "mature"],
        "sort_order": 0,
    },
    {
        "style_id": "women-long-layers",
        "slug": "long-layers",
        "audience": "women",
        "category": "beauty",
        "title": "Long Layers",
        "title_uz": "Uzun qatlamlar",
        "face_shapes": ["oval", "round"],
        "hair_length": "long",
        "image_path": "/hairstyles/women/long-layers.webp",
        "description_uz": "Uzun qatlamlar — hajm va harakat, yuzni uzaytiradi.",
        "tags": ["layers", "long"],
        "age_groups": ["teen", "young", "adult", "mature"],
        "sort_order": 1,
    },
    {
        "style_id": "women-balayage",
        "slug": "balayage",
        "audience": "women",
        "category": "beauty",
        "title": "Balayage",
        "title_uz": "Balayage",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "long",
        "image_path": "/hairstyles/women/balayage.webp",
        "description_uz": "Tabiiy rang o'tishlari — yorug'lik va chuqurlik muvozanati.",
        "tags": ["color", "balayage"],
        "age_groups": ["young", "adult"],
        "sort_order": 2,
    },
    {
        "style_id": "women-pixie-cut",
        "slug": "pixie-cut",
        "audience": "women",
        "category": "beauty",
        "title": "Pixie Cut",
        "title_uz": "Pixie Cut",
        "face_shapes": ["oval", "square"],
        "hair_length": "short",
        "image_path": "/hairstyles/women/pixie-cut.webp",
        "description_uz": "Qisqa pixie — jasur va zamonaviy, yuz xususiyatlarini ta'kidlaydi.",
        "tags": ["short", "pixie"],
        "age_groups": ["adult", "mature"],
        "sort_order": 3,
    },
    {
        "style_id": "women-beach-waves",
        "slug": "beach-waves",
        "audience": "women",
        "category": "beauty",
        "title": "Beach Waves",
        "title_uz": "Beach Waves",
        "face_shapes": ["oval", "round"],
        "hair_length": "medium",
        "image_path": "/hairstyles/women/beach-waves.webp",
        "description_uz": "Tabiiy to'lqinlar — yengil va romantik ko'rinish.",
        "tags": ["waves", "casual"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 4,
    },
    {
        "style_id": "women-straight-lob",
        "slug": "straight-lob",
        "audience": "women",
        "category": "beauty",
        "title": "Straight Lob",
        "title_uz": "Straight Lob",
        "face_shapes": ["oval", "round", "square"],
        "hair_length": "medium",
        "image_path": "/hairstyles/women/straight-lob.webp",
        "description_uz": "To'g'ri lob — zamonaviy va silliq, yuz shaklini muvozanatlaydi.",
        "tags": ["lob", "straight"],
        "age_groups": ["teen", "young", "adult", "mature"],
        "sort_order": 5,
    },
    {
        "style_id": "women-curtain-bangs",
        "slug": "curtain-bangs",
        "audience": "women",
        "category": "beauty",
        "title": "Curtain Bangs",
        "title_uz": "Curtain Bangs",
        "face_shapes": ["oval", "round", "square"],
        "hair_length": "medium",
        "image_path": "/hairstyles/women/curtain-bangs.webp",
        "description_uz": "Parda bang — yuzni yumshatadi, trend va universal uslub.",
        "tags": ["bangs", "trend"],
        "age_groups": ["teen", "young", "adult"],
        "sort_order": 6,
    },
    {
        "style_id": "women-shag-cut",
        "slug": "shag-cut",
        "audience": "women",
        "category": "beauty",
        "title": "Shag Cut",
        "title_uz": "Shag Cut",
        "face_shapes": ["oval", "round"],
        "hair_length": "medium",
        "image_path": "/hairstyles/women/shag-cut.webp",
        "description_uz": "Qatlamlangan shag — hajm va tekstura, 70-yillar zamonaviy talqini.",
        "tags": ["shag", "layers"],
        "age_groups": ["young", "adult"],
        "sort_order": 7,
    },
    {
        "style_id": "women-braids",
        "slug": "braids",
        "audience": "women",
        "category": "beauty",
        "title": "Braids",
        "title_uz": "O'rilmalar",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "long",
        "image_path": "/hairstyles/women/braids.webp",
        "description_uz": "O'rilmalar — amaliy va nafis, maxsus kunlar uchun ajoyib tanlov.",
        "tags": ["braids", "styled"],
        "age_groups": ["kids", "teen", "young", "adult"],
        "sort_order": 8,
    },
    {
        "style_id": "women-updo-bun",
        "slug": "updo-bun",
        "audience": "women",
        "category": "beauty",
        "title": "Updo Bun",
        "title_uz": "Updo / Bun",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "medium",
        "image_path": "/hairstyles/women/updo-bun.webp",
        "description_uz": "Yig'ilgan soch — toza va nafis, bayram va rasmiy tadbirlar uchun.",
        "tags": ["updo", "elegant"],
        "age_groups": ["teen", "young", "adult", "mature"],
        "sort_order": 9,
    },
    {
        "style_id": "women-blunt-cut",
        "slug": "blunt-cut",
        "audience": "women",
        "category": "beauty",
        "title": "Blunt Cut",
        "title_uz": "Blunt Cut",
        "face_shapes": ["oval", "round"],
        "hair_length": "medium",
        "image_path": "/hairstyles/women/blunt-cut.webp",
        "description_uz": "To'g'ri kesim — aniq chegaralar, zamonaviy minimalist ko'rinish.",
        "tags": ["blunt", "clean"],
        "age_groups": ["teen", "young", "adult", "mature"],
        "sort_order": 10,
    },
    {
        "style_id": "women-highlights",
        "slug": "highlights",
        "audience": "women",
        "category": "beauty",
        "title": "Highlights",
        "title_uz": "Highlights",
        "face_shapes": ["oval", "square", "round"],
        "hair_length": "medium",
        "image_path": "/hairstyles/women/highlights.webp",
        "description_uz": "Yorug'lik streaklari — yuzni yoritadi, hajm illuziyasi beradi.",
        "tags": ["color", "highlights"],
        "age_groups": ["young", "adult", "mature"],
        "sort_order": 11,
    },
]
