/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BarberRouteImport } from './routes/barber'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BarberIndexRouteImport } from './routes/barber.index'
import { Route as SalonJoinRouteImport } from './routes/salon.join'
import { Route as SalonCreateRouteImport } from './routes/salon.create'
import { Route as MybarberSetupRouteImport } from './routes/mybarber.setup'
import { Route as IndependentSetupRouteImport } from './routes/independent.setup'
import { Route as BarberVerifyEmailRouteImport } from './routes/barber.verify-email'
import { Route as BarberStatsRouteImport } from './routes/barber.stats'
import { Route as BarberSettingsRouteImport } from './routes/barber.settings'
import { Route as BarberServicesRouteImport } from './routes/barber.services'
import { Route as BarberReviewsRouteImport } from './routes/barber.reviews'
import { Route as BarberProfileRouteImport } from './routes/barber.profile'
import { Route as BarberPortfolioRouteImport } from './routes/barber.portfolio'
import { Route as BarberNotificationsRouteImport } from './routes/barber.notifications'
import { Route as BarberMarketingRouteImport } from './routes/barber.marketing'
import { Route as BarberInventoryRouteImport } from './routes/barber.inventory'
import { Route as BarberHelpRouteImport } from './routes/barber.help'
import { Route as BarberGoalsRouteImport } from './routes/barber.goals'
import { Route as BarberExpensesRouteImport } from './routes/barber.expenses'
import { Route as BarberEarningsRouteImport } from './routes/barber.earnings'
import { Route as BarberClientsRouteImport } from './routes/barber.clients'
import { Route as BarberChatRouteImport } from './routes/barber.chat'
import { Route as BarberCalendarRouteImport } from './routes/barber.calendar'
import { Route as BarberBookingsRouteImport } from './routes/barber.bookings'
import { Route as BarberActivationRouteImport } from './routes/barber.activation'
import { Route as SalonJoinIndexRouteImport } from './routes/salon.join.index'
import { Route as BarberSalonViewIndexRouteImport } from './routes/barber.salon-view.index'
import { Route as SalonJoinSetupRouteImport } from './routes/salon.join.setup'
import { Route as BarberSalonViewTeamRouteImport } from './routes/barber.salon-view.team'
import { Route as BarberSalonViewReviewsRouteImport } from './routes/barber.salon-view.reviews'
import { Route as BarberSalonViewMembersRouteImport } from './routes/barber.salon-view.members'
import { Route as BarberSalonViewGalleryRouteImport } from './routes/barber.salon-view.gallery'

const BarberRoute = BarberRouteImport.update({
  id: '/barber',
  path: '/barber',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberIndexRoute = BarberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BarberRoute,
} as any)
const SalonJoinRoute = SalonJoinRouteImport.update({
  id: '/salon/join',
  path: '/salon/join',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonCreateRoute = SalonCreateRouteImport.update({
  id: '/salon/create',
  path: '/salon/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MybarberSetupRoute = MybarberSetupRouteImport.update({
  id: '/mybarber/setup',
  path: '/mybarber/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndependentSetupRoute = IndependentSetupRouteImport.update({
  id: '/independent/setup',
  path: '/independent/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberVerifyEmailRoute = BarberVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => BarberRoute,
} as any)
const BarberStatsRoute = BarberStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSettingsRoute = BarberSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BarberRoute,
} as any)
const BarberServicesRoute = BarberServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => BarberRoute,
} as any)
const BarberReviewsRoute = BarberReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => BarberRoute,
} as any)
const BarberProfileRoute = BarberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BarberRoute,
} as any)
const BarberPortfolioRoute = BarberPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => BarberRoute,
} as any)
const BarberNotificationsRoute = BarberNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => BarberRoute,
} as any)
const BarberMarketingRoute = BarberMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => BarberRoute,
} as any)
const BarberInventoryRoute = BarberInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => BarberRoute,
} as any)
const BarberHelpRoute = BarberHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => BarberRoute,
} as any)
const BarberGoalsRoute = BarberGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => BarberRoute,
} as any)
const BarberExpensesRoute = BarberExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => BarberRoute,
} as any)
const BarberEarningsRoute = BarberEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => BarberRoute,
} as any)
const BarberClientsRoute = BarberClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => BarberRoute,
} as any)
const BarberChatRoute = BarberChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => BarberRoute,
} as any)
const BarberCalendarRoute = BarberCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => BarberRoute,
} as any)
const BarberBookingsRoute = BarberBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => BarberRoute,
} as any)
const BarberActivationRoute = BarberActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => BarberRoute,
} as any)
const SalonJoinIndexRoute = SalonJoinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalonJoinRoute,
} as any)
const BarberSalonViewIndexRoute = BarberSalonViewIndexRouteImport.update({
  id: '/salon-view/',
  path: '/salon-view/',
  getParentRoute: () => BarberRoute,
} as any)
const SalonJoinSetupRoute = SalonJoinSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => SalonJoinRoute,
} as any)
const BarberSalonViewTeamRoute = BarberSalonViewTeamRouteImport.update({
  id: '/salon-view/team',
  path: '/salon-view/team',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSalonViewReviewsRoute = BarberSalonViewReviewsRouteImport.update({
  id: '/salon-view/reviews',
  path: '/salon-view/reviews',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSalonViewMembersRoute = BarberSalonViewMembersRouteImport.update({
  id: '/salon-view/members',
  path: '/salon-view/members',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSalonViewGalleryRoute = BarberSalonViewGalleryRouteImport.update({
  id: '/salon-view/gallery',
  path: '/salon-view/gallery',
  getParentRoute: () => BarberRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/barber': typeof BarberRouteWithChildren
  '/barber/activation': typeof BarberActivationRoute
  '/barber/bookings': typeof BarberBookingsRoute
  '/barber/calendar': typeof BarberCalendarRoute
  '/barber/chat': typeof BarberChatRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/earnings': typeof BarberEarningsRoute
  '/barber/expenses': typeof BarberExpensesRoute
  '/barber/goals': typeof BarberGoalsRoute
  '/barber/help': typeof BarberHelpRoute
  '/barber/inventory': typeof BarberInventoryRoute
  '/barber/marketing': typeof BarberMarketingRoute
  '/barber/notifications': typeof BarberNotificationsRoute
  '/barber/portfolio': typeof BarberPortfolioRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/reviews': typeof BarberReviewsRoute
  '/barber/services': typeof BarberServicesRoute
  '/barber/settings': typeof BarberSettingsRoute
  '/barber/stats': typeof BarberStatsRoute
  '/barber/verify-email': typeof BarberVerifyEmailRoute
  '/independent/setup': typeof IndependentSetupRoute
  '/mybarber/setup': typeof MybarberSetupRoute
  '/salon/create': typeof SalonCreateRoute
  '/salon/join': typeof SalonJoinRouteWithChildren
  '/barber/': typeof BarberIndexRoute
  '/barber/salon-view/gallery': typeof BarberSalonViewGalleryRoute
  '/barber/salon-view/members': typeof BarberSalonViewMembersRoute
  '/barber/salon-view/reviews': typeof BarberSalonViewReviewsRoute
  '/barber/salon-view/team': typeof BarberSalonViewTeamRoute
  '/salon/join/setup': typeof SalonJoinSetupRoute
  '/barber/salon-view/': typeof BarberSalonViewIndexRoute
  '/salon/join/': typeof SalonJoinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/barber/activation': typeof BarberActivationRoute
  '/barber/bookings': typeof BarberBookingsRoute
  '/barber/calendar': typeof BarberCalendarRoute
  '/barber/chat': typeof BarberChatRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/earnings': typeof BarberEarningsRoute
  '/barber/expenses': typeof BarberExpensesRoute
  '/barber/goals': typeof BarberGoalsRoute
  '/barber/help': typeof BarberHelpRoute
  '/barber/inventory': typeof BarberInventoryRoute
  '/barber/marketing': typeof BarberMarketingRoute
  '/barber/notifications': typeof BarberNotificationsRoute
  '/barber/portfolio': typeof BarberPortfolioRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/reviews': typeof BarberReviewsRoute
  '/barber/services': typeof BarberServicesRoute
  '/barber/settings': typeof BarberSettingsRoute
  '/barber/stats': typeof BarberStatsRoute
  '/barber/verify-email': typeof BarberVerifyEmailRoute
  '/independent/setup': typeof IndependentSetupRoute
  '/mybarber/setup': typeof MybarberSetupRoute
  '/salon/create': typeof SalonCreateRoute
  '/barber': typeof BarberIndexRoute
  '/barber/salon-view/gallery': typeof BarberSalonViewGalleryRoute
  '/barber/salon-view/members': typeof BarberSalonViewMembersRoute
  '/barber/salon-view/reviews': typeof BarberSalonViewReviewsRoute
  '/barber/salon-view/team': typeof BarberSalonViewTeamRoute
  '/salon/join/setup': typeof SalonJoinSetupRoute
  '/barber/salon-view': typeof BarberSalonViewIndexRoute
  '/salon/join': typeof SalonJoinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/barber': typeof BarberRouteWithChildren
  '/barber/activation': typeof BarberActivationRoute
  '/barber/bookings': typeof BarberBookingsRoute
  '/barber/calendar': typeof BarberCalendarRoute
  '/barber/chat': typeof BarberChatRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/earnings': typeof BarberEarningsRoute
  '/barber/expenses': typeof BarberExpensesRoute
  '/barber/goals': typeof BarberGoalsRoute
  '/barber/help': typeof BarberHelpRoute
  '/barber/inventory': typeof BarberInventoryRoute
  '/barber/marketing': typeof BarberMarketingRoute
  '/barber/notifications': typeof BarberNotificationsRoute
  '/barber/portfolio': typeof BarberPortfolioRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/reviews': typeof BarberReviewsRoute
  '/barber/services': typeof BarberServicesRoute
  '/barber/settings': typeof BarberSettingsRoute
  '/barber/stats': typeof BarberStatsRoute
  '/barber/verify-email': typeof BarberVerifyEmailRoute
  '/independent/setup': typeof IndependentSetupRoute
  '/mybarber/setup': typeof MybarberSetupRoute
  '/salon/create': typeof SalonCreateRoute
  '/salon/join': typeof SalonJoinRouteWithChildren
  '/barber/': typeof BarberIndexRoute
  '/barber/salon-view/gallery': typeof BarberSalonViewGalleryRoute
  '/barber/salon-view/members': typeof BarberSalonViewMembersRoute
  '/barber/salon-view/reviews': typeof BarberSalonViewReviewsRoute
  '/barber/salon-view/team': typeof BarberSalonViewTeamRoute
  '/salon/join/setup': typeof SalonJoinSetupRoute
  '/barber/salon-view/': typeof BarberSalonViewIndexRoute
  '/salon/join/': typeof SalonJoinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/barber'
    | '/barber/activation'
    | '/barber/bookings'
    | '/barber/calendar'
    | '/barber/chat'
    | '/barber/clients'
    | '/barber/earnings'
    | '/barber/expenses'
    | '/barber/goals'
    | '/barber/help'
    | '/barber/inventory'
    | '/barber/marketing'
    | '/barber/notifications'
    | '/barber/portfolio'
    | '/barber/profile'
    | '/barber/reviews'
    | '/barber/services'
    | '/barber/settings'
    | '/barber/stats'
    | '/barber/verify-email'
    | '/independent/setup'
    | '/mybarber/setup'
    | '/salon/create'
    | '/salon/join'
    | '/barber/'
    | '/barber/salon-view/gallery'
    | '/barber/salon-view/members'
    | '/barber/salon-view/reviews'
    | '/barber/salon-view/team'
    | '/salon/join/setup'
    | '/barber/salon-view/'
    | '/salon/join/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/barber/activation'
    | '/barber/bookings'
    | '/barber/calendar'
    | '/barber/chat'
    | '/barber/clients'
    | '/barber/earnings'
    | '/barber/expenses'
    | '/barber/goals'
    | '/barber/help'
    | '/barber/inventory'
    | '/barber/marketing'
    | '/barber/notifications'
    | '/barber/portfolio'
    | '/barber/profile'
    | '/barber/reviews'
    | '/barber/services'
    | '/barber/settings'
    | '/barber/stats'
    | '/barber/verify-email'
    | '/independent/setup'
    | '/mybarber/setup'
    | '/salon/create'
    | '/barber'
    | '/barber/salon-view/gallery'
    | '/barber/salon-view/members'
    | '/barber/salon-view/reviews'
    | '/barber/salon-view/team'
    | '/salon/join/setup'
    | '/barber/salon-view'
    | '/salon/join'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/barber'
    | '/barber/activation'
    | '/barber/bookings'
    | '/barber/calendar'
    | '/barber/chat'
    | '/barber/clients'
    | '/barber/earnings'
    | '/barber/expenses'
    | '/barber/goals'
    | '/barber/help'
    | '/barber/inventory'
    | '/barber/marketing'
    | '/barber/notifications'
    | '/barber/portfolio'
    | '/barber/profile'
    | '/barber/reviews'
    | '/barber/services'
    | '/barber/settings'
    | '/barber/stats'
    | '/barber/verify-email'
    | '/independent/setup'
    | '/mybarber/setup'
    | '/salon/create'
    | '/salon/join'
    | '/barber/'
    | '/barber/salon-view/gallery'
    | '/barber/salon-view/members'
    | '/barber/salon-view/reviews'
    | '/barber/salon-view/team'
    | '/salon/join/setup'
    | '/barber/salon-view/'
    | '/salon/join/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BarberRoute: typeof BarberRouteWithChildren
  IndependentSetupRoute: typeof IndependentSetupRoute
  MybarberSetupRoute: typeof MybarberSetupRoute
  SalonCreateRoute: typeof SalonCreateRoute
  SalonJoinRoute: typeof SalonJoinRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/barber': {
      id: '/barber'
      path: '/barber'
      fullPath: '/barber'
      preLoaderRoute: typeof BarberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/': {
      id: '/barber/'
      path: '/'
      fullPath: '/barber/'
      preLoaderRoute: typeof BarberIndexRouteImport
      parentRoute: typeof BarberRoute
    }
    '/salon/join': {
      id: '/salon/join'
      path: '/salon/join'
      fullPath: '/salon/join'
      preLoaderRoute: typeof SalonJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon/create': {
      id: '/salon/create'
      path: '/salon/create'
      fullPath: '/salon/create'
      preLoaderRoute: typeof SalonCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mybarber/setup': {
      id: '/mybarber/setup'
      path: '/mybarber/setup'
      fullPath: '/mybarber/setup'
      preLoaderRoute: typeof MybarberSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/independent/setup': {
      id: '/independent/setup'
      path: '/independent/setup'
      fullPath: '/independent/setup'
      preLoaderRoute: typeof IndependentSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/verify-email': {
      id: '/barber/verify-email'
      path: '/verify-email'
      fullPath: '/barber/verify-email'
      preLoaderRoute: typeof BarberVerifyEmailRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/stats': {
      id: '/barber/stats'
      path: '/stats'
      fullPath: '/barber/stats'
      preLoaderRoute: typeof BarberStatsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/settings': {
      id: '/barber/settings'
      path: '/settings'
      fullPath: '/barber/settings'
      preLoaderRoute: typeof BarberSettingsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/services': {
      id: '/barber/services'
      path: '/services'
      fullPath: '/barber/services'
      preLoaderRoute: typeof BarberServicesRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/reviews': {
      id: '/barber/reviews'
      path: '/reviews'
      fullPath: '/barber/reviews'
      preLoaderRoute: typeof BarberReviewsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/profile': {
      id: '/barber/profile'
      path: '/profile'
      fullPath: '/barber/profile'
      preLoaderRoute: typeof BarberProfileRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/portfolio': {
      id: '/barber/portfolio'
      path: '/portfolio'
      fullPath: '/barber/portfolio'
      preLoaderRoute: typeof BarberPortfolioRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/notifications': {
      id: '/barber/notifications'
      path: '/notifications'
      fullPath: '/barber/notifications'
      preLoaderRoute: typeof BarberNotificationsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/marketing': {
      id: '/barber/marketing'
      path: '/marketing'
      fullPath: '/barber/marketing'
      preLoaderRoute: typeof BarberMarketingRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/inventory': {
      id: '/barber/inventory'
      path: '/inventory'
      fullPath: '/barber/inventory'
      preLoaderRoute: typeof BarberInventoryRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/help': {
      id: '/barber/help'
      path: '/help'
      fullPath: '/barber/help'
      preLoaderRoute: typeof BarberHelpRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/goals': {
      id: '/barber/goals'
      path: '/goals'
      fullPath: '/barber/goals'
      preLoaderRoute: typeof BarberGoalsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/expenses': {
      id: '/barber/expenses'
      path: '/expenses'
      fullPath: '/barber/expenses'
      preLoaderRoute: typeof BarberExpensesRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/earnings': {
      id: '/barber/earnings'
      path: '/earnings'
      fullPath: '/barber/earnings'
      preLoaderRoute: typeof BarberEarningsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/clients': {
      id: '/barber/clients'
      path: '/clients'
      fullPath: '/barber/clients'
      preLoaderRoute: typeof BarberClientsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/chat': {
      id: '/barber/chat'
      path: '/chat'
      fullPath: '/barber/chat'
      preLoaderRoute: typeof BarberChatRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/calendar': {
      id: '/barber/calendar'
      path: '/calendar'
      fullPath: '/barber/calendar'
      preLoaderRoute: typeof BarberCalendarRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/bookings': {
      id: '/barber/bookings'
      path: '/bookings'
      fullPath: '/barber/bookings'
      preLoaderRoute: typeof BarberBookingsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/activation': {
      id: '/barber/activation'
      path: '/activation'
      fullPath: '/barber/activation'
      preLoaderRoute: typeof BarberActivationRouteImport
      parentRoute: typeof BarberRoute
    }
    '/salon/join/': {
      id: '/salon/join/'
      path: '/'
      fullPath: '/salon/join/'
      preLoaderRoute: typeof SalonJoinIndexRouteImport
      parentRoute: typeof SalonJoinRoute
    }
    '/barber/salon-view/': {
      id: '/barber/salon-view/'
      path: '/salon-view'
      fullPath: '/barber/salon-view/'
      preLoaderRoute: typeof BarberSalonViewIndexRouteImport
      parentRoute: typeof BarberRoute
    }
    '/salon/join/setup': {
      id: '/salon/join/setup'
      path: '/setup'
      fullPath: '/salon/join/setup'
      preLoaderRoute: typeof SalonJoinSetupRouteImport
      parentRoute: typeof SalonJoinRoute
    }
    '/barber/salon-view/team': {
      id: '/barber/salon-view/team'
      path: '/salon-view/team'
      fullPath: '/barber/salon-view/team'
      preLoaderRoute: typeof BarberSalonViewTeamRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/salon-view/reviews': {
      id: '/barber/salon-view/reviews'
      path: '/salon-view/reviews'
      fullPath: '/barber/salon-view/reviews'
      preLoaderRoute: typeof BarberSalonViewReviewsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/salon-view/members': {
      id: '/barber/salon-view/members'
      path: '/salon-view/members'
      fullPath: '/barber/salon-view/members'
      preLoaderRoute: typeof BarberSalonViewMembersRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/salon-view/gallery': {
      id: '/barber/salon-view/gallery'
      path: '/salon-view/gallery'
      fullPath: '/barber/salon-view/gallery'
      preLoaderRoute: typeof BarberSalonViewGalleryRouteImport
      parentRoute: typeof BarberRoute
    }
  }
}

interface BarberRouteChildren {
  BarberActivationRoute: typeof BarberActivationRoute
  BarberBookingsRoute: typeof BarberBookingsRoute
  BarberCalendarRoute: typeof BarberCalendarRoute
  BarberChatRoute: typeof BarberChatRoute
  BarberClientsRoute: typeof BarberClientsRoute
  BarberEarningsRoute: typeof BarberEarningsRoute
  BarberExpensesRoute: typeof BarberExpensesRoute
  BarberGoalsRoute: typeof BarberGoalsRoute
  BarberHelpRoute: typeof BarberHelpRoute
  BarberInventoryRoute: typeof BarberInventoryRoute
  BarberMarketingRoute: typeof BarberMarketingRoute
  BarberNotificationsRoute: typeof BarberNotificationsRoute
  BarberPortfolioRoute: typeof BarberPortfolioRoute
  BarberProfileRoute: typeof BarberProfileRoute
  BarberReviewsRoute: typeof BarberReviewsRoute
  BarberServicesRoute: typeof BarberServicesRoute
  BarberSettingsRoute: typeof BarberSettingsRoute
  BarberStatsRoute: typeof BarberStatsRoute
  BarberVerifyEmailRoute: typeof BarberVerifyEmailRoute
  BarberIndexRoute: typeof BarberIndexRoute
  BarberSalonViewGalleryRoute: typeof BarberSalonViewGalleryRoute
  BarberSalonViewMembersRoute: typeof BarberSalonViewMembersRoute
  BarberSalonViewReviewsRoute: typeof BarberSalonViewReviewsRoute
  BarberSalonViewTeamRoute: typeof BarberSalonViewTeamRoute
  BarberSalonViewIndexRoute: typeof BarberSalonViewIndexRoute
}

const BarberRouteChildren: BarberRouteChildren = {
  BarberActivationRoute: BarberActivationRoute,
  BarberBookingsRoute: BarberBookingsRoute,
  BarberCalendarRoute: BarberCalendarRoute,
  BarberChatRoute: BarberChatRoute,
  BarberClientsRoute: BarberClientsRoute,
  BarberEarningsRoute: BarberEarningsRoute,
  BarberExpensesRoute: BarberExpensesRoute,
  BarberGoalsRoute: BarberGoalsRoute,
  BarberHelpRoute: BarberHelpRoute,
  BarberInventoryRoute: BarberInventoryRoute,
  BarberMarketingRoute: BarberMarketingRoute,
  BarberNotificationsRoute: BarberNotificationsRoute,
  BarberPortfolioRoute: BarberPortfolioRoute,
  BarberProfileRoute: BarberProfileRoute,
  BarberReviewsRoute: BarberReviewsRoute,
  BarberServicesRoute: BarberServicesRoute,
  BarberSettingsRoute: BarberSettingsRoute,
  BarberStatsRoute: BarberStatsRoute,
  BarberVerifyEmailRoute: BarberVerifyEmailRoute,
  BarberIndexRoute: BarberIndexRoute,
  BarberSalonViewGalleryRoute: BarberSalonViewGalleryRoute,
  BarberSalonViewMembersRoute: BarberSalonViewMembersRoute,
  BarberSalonViewReviewsRoute: BarberSalonViewReviewsRoute,
  BarberSalonViewTeamRoute: BarberSalonViewTeamRoute,
  BarberSalonViewIndexRoute: BarberSalonViewIndexRoute,
}

const BarberRouteWithChildren =
  BarberRoute._addFileChildren(BarberRouteChildren)

interface SalonJoinRouteChildren {
  SalonJoinSetupRoute: typeof SalonJoinSetupRoute
  SalonJoinIndexRoute: typeof SalonJoinIndexRoute
}

const SalonJoinRouteChildren: SalonJoinRouteChildren = {
  SalonJoinSetupRoute: SalonJoinSetupRoute,
  SalonJoinIndexRoute: SalonJoinIndexRoute,
}

const SalonJoinRouteWithChildren = SalonJoinRoute._addFileChildren(
  SalonJoinRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BarberRoute: BarberRouteWithChildren,
  IndependentSetupRoute: IndependentSetupRoute,
  MybarberSetupRoute: MybarberSetupRoute,
  SalonCreateRoute: SalonCreateRoute,
  SalonJoinRoute: SalonJoinRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
