/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BarberRouteImport } from './routes/barber'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as AgentAylanmaRouteImport } from './routes/agent.aylanma'
import { Route as AgentInviteRouteImport } from './routes/agent.invite'
import { Route as AgentLoginRouteImport } from './routes/agent.login'
import { Route as AgentPayoutRouteImport } from './routes/agent.payout'
import { Route as AgentSalonsRouteImport } from './routes/agent.salons'
import { Route as BarberIndexRouteImport } from './routes/barber.index'
import { Route as BarberActivationRouteImport } from './routes/barber.activation'
import { Route as BarberAmenitiesRouteImport } from './routes/barber.amenities'
import { Route as BarberBookingsRouteImport } from './routes/barber.bookings'
import { Route as BarberCalendarRouteImport } from './routes/barber.calendar'
import { Route as BarberChatRouteImport } from './routes/barber.chat'
import { Route as BarberClientsRouteImport } from './routes/barber.clients'
import { Route as BarberEarningsRouteImport } from './routes/barber.earnings'
import { Route as BarberExpensesRouteImport } from './routes/barber.expenses'
import { Route as BarberGoalsRouteImport } from './routes/barber.goals'
import { Route as BarberHelpRouteImport } from './routes/barber.help'
import { Route as BarberInventoryRouteImport } from './routes/barber.inventory'
import { Route as BarberInvitesRouteImport } from './routes/barber.invites'
import { Route as BarberMarketingRouteImport } from './routes/barber.marketing'
import { Route as BarberNotificationsRouteImport } from './routes/barber.notifications'
import { Route as BarberPortfolioRouteImport } from './routes/barber.portfolio'
import { Route as BarberProfileRouteImport } from './routes/barber.profile'
import { Route as BarberQrPayRouteImport } from './routes/barber.qr-pay'
import { Route as BarberReviewsRouteImport } from './routes/barber.reviews'
import { Route as BarberScheduleRouteImport } from './routes/barber.schedule'
import { Route as BarberServicesRouteImport } from './routes/barber.services'
import { Route as BarberSettingsRouteImport } from './routes/barber.settings'
import { Route as BarberStatsRouteImport } from './routes/barber.stats'
import { Route as BarberSubscriptionRouteImport } from './routes/barber.subscription'
import { Route as BarberWithdrawalsRouteImport } from './routes/barber.withdrawals'
import { Route as IndependentSetupRouteImport } from './routes/independent.setup'
import { Route as MybarberSetupRouteImport } from './routes/mybarber.setup'
import { Route as SalonCreateRouteImport } from './routes/salon.create'
import { Route as SalonJoinRouteImport } from './routes/salon.join'
import { Route as BarberBookingsBookingIdRouteImport } from './routes/barber.bookings.$bookingId'
import { Route as BarberSalonViewIndexRouteImport } from './routes/barber.salon-view.index'
import { Route as BarberSalonViewEditRouteImport } from './routes/barber.salon-view.edit'
import { Route as BarberSalonViewGalleryRouteImport } from './routes/barber.salon-view.gallery'
import { Route as BarberSalonViewMembersRouteImport } from './routes/barber.salon-view.members'
import { Route as BarberSalonViewReviewsRouteImport } from './routes/barber.salon-view.reviews'
import { Route as BarberSalonViewTeamRouteImport } from './routes/barber.salon-view.team'
import { Route as BarberStatsIndexRouteImport } from './routes/barber.stats.index'
import { Route as BarberStatsGraphsRouteImport } from './routes/barber.stats.graphs'
import { Route as SalonJoinIndexRouteImport } from './routes/salon.join.index'
import { Route as SalonJoinSetupRouteImport } from './routes/salon.join.setup'
import { Route as BarberBookingsBookingIdIndexRouteImport } from './routes/barber.bookings.$bookingId.index'
import { Route as BarberBookingsBookingIdCheckInRouteImport } from './routes/barber.bookings.$bookingId.check-in'
import { Route as BarberBookingsBookingIdSessionRouteImport } from './routes/barber.bookings.$bookingId.session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberRoute = BarberRouteImport.update({
  id: '/barber',
  path: '/barber',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAylanmaRoute = AgentAylanmaRouteImport.update({
  id: '/aylanma',
  path: '/aylanma',
  getParentRoute: () => AgentRoute,
} as any)
const AgentInviteRoute = AgentInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AgentRoute,
} as any)
const AgentLoginRoute = AgentLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AgentRoute,
} as any)
const AgentPayoutRoute = AgentPayoutRouteImport.update({
  id: '/payout',
  path: '/payout',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSalonsRoute = AgentSalonsRouteImport.update({
  id: '/salons',
  path: '/salons',
  getParentRoute: () => AgentRoute,
} as any)
const BarberIndexRoute = BarberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BarberRoute,
} as any)
const BarberActivationRoute = BarberActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => BarberRoute,
} as any)
const BarberAmenitiesRoute = BarberAmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => BarberRoute,
} as any)
const BarberBookingsRoute = BarberBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => BarberRoute,
} as any)
const BarberCalendarRoute = BarberCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => BarberRoute,
} as any)
const BarberChatRoute = BarberChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => BarberRoute,
} as any)
const BarberClientsRoute = BarberClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => BarberRoute,
} as any)
const BarberEarningsRoute = BarberEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => BarberRoute,
} as any)
const BarberExpensesRoute = BarberExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => BarberRoute,
} as any)
const BarberGoalsRoute = BarberGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => BarberRoute,
} as any)
const BarberHelpRoute = BarberHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => BarberRoute,
} as any)
const BarberInventoryRoute = BarberInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => BarberRoute,
} as any)
const BarberInvitesRoute = BarberInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => BarberRoute,
} as any)
const BarberMarketingRoute = BarberMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => BarberRoute,
} as any)
const BarberNotificationsRoute = BarberNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => BarberRoute,
} as any)
const BarberPortfolioRoute = BarberPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => BarberRoute,
} as any)
const BarberProfileRoute = BarberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BarberRoute,
} as any)
const BarberQrPayRoute = BarberQrPayRouteImport.update({
  id: '/qr-pay',
  path: '/qr-pay',
  getParentRoute: () => BarberRoute,
} as any)
const BarberReviewsRoute = BarberReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => BarberRoute,
} as any)
const BarberScheduleRoute = BarberScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => BarberRoute,
} as any)
const BarberServicesRoute = BarberServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSettingsRoute = BarberSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BarberRoute,
} as any)
const BarberStatsRoute = BarberStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSubscriptionRoute = BarberSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => BarberRoute,
} as any)
const BarberWithdrawalsRoute = BarberWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => BarberRoute,
} as any)
const IndependentSetupRoute = IndependentSetupRouteImport.update({
  id: '/independent/setup',
  path: '/independent/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MybarberSetupRoute = MybarberSetupRouteImport.update({
  id: '/mybarber/setup',
  path: '/mybarber/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonCreateRoute = SalonCreateRouteImport.update({
  id: '/salon/create',
  path: '/salon/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonJoinRoute = SalonJoinRouteImport.update({
  id: '/salon/join',
  path: '/salon/join',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberBookingsBookingIdRoute = BarberBookingsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => BarberBookingsRoute,
} as any)
const BarberSalonViewIndexRoute = BarberSalonViewIndexRouteImport.update({
  id: '/salon-view/',
  path: '/salon-view/',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSalonViewEditRoute = BarberSalonViewEditRouteImport.update({
  id: '/salon-view/edit',
  path: '/salon-view/edit',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSalonViewGalleryRoute = BarberSalonViewGalleryRouteImport.update({
  id: '/salon-view/gallery',
  path: '/salon-view/gallery',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSalonViewMembersRoute = BarberSalonViewMembersRouteImport.update({
  id: '/salon-view/members',
  path: '/salon-view/members',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSalonViewReviewsRoute = BarberSalonViewReviewsRouteImport.update({
  id: '/salon-view/reviews',
  path: '/salon-view/reviews',
  getParentRoute: () => BarberRoute,
} as any)
const BarberSalonViewTeamRoute = BarberSalonViewTeamRouteImport.update({
  id: '/salon-view/team',
  path: '/salon-view/team',
  getParentRoute: () => BarberRoute,
} as any)
const BarberStatsIndexRoute = BarberStatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BarberStatsRoute,
} as any)
const BarberStatsGraphsRoute = BarberStatsGraphsRouteImport.update({
  id: '/graphs',
  path: '/graphs',
  getParentRoute: () => BarberStatsRoute,
} as any)
const SalonJoinIndexRoute = SalonJoinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalonJoinRoute,
} as any)
const SalonJoinSetupRoute = SalonJoinSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => SalonJoinRoute,
} as any)
const BarberBookingsBookingIdIndexRoute =
  BarberBookingsBookingIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BarberBookingsBookingIdRoute,
  } as any)
const BarberBookingsBookingIdCheckInRoute =
  BarberBookingsBookingIdCheckInRouteImport.update({
    id: '/check-in',
    path: '/check-in',
    getParentRoute: () => BarberBookingsBookingIdRoute,
  } as any)
const BarberBookingsBookingIdSessionRoute =
  BarberBookingsBookingIdSessionRouteImport.update({
    id: '/session',
    path: '/session',
    getParentRoute: () => BarberBookingsBookingIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/auth': typeof AuthRoute
  '/barber': typeof BarberRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/agent/aylanma': typeof AgentAylanmaRoute
  '/agent/invite': typeof AgentInviteRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/payout': typeof AgentPayoutRoute
  '/agent/salons': typeof AgentSalonsRoute
  '/barber/activation': typeof BarberActivationRoute
  '/barber/amenities': typeof BarberAmenitiesRoute
  '/barber/bookings': typeof BarberBookingsRouteWithChildren
  '/barber/calendar': typeof BarberCalendarRoute
  '/barber/chat': typeof BarberChatRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/earnings': typeof BarberEarningsRoute
  '/barber/expenses': typeof BarberExpensesRoute
  '/barber/goals': typeof BarberGoalsRoute
  '/barber/help': typeof BarberHelpRoute
  '/barber/inventory': typeof BarberInventoryRoute
  '/barber/invites': typeof BarberInvitesRoute
  '/barber/marketing': typeof BarberMarketingRoute
  '/barber/notifications': typeof BarberNotificationsRoute
  '/barber/portfolio': typeof BarberPortfolioRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/qr-pay': typeof BarberQrPayRoute
  '/barber/reviews': typeof BarberReviewsRoute
  '/barber/schedule': typeof BarberScheduleRoute
  '/barber/services': typeof BarberServicesRoute
  '/barber/settings': typeof BarberSettingsRoute
  '/barber/stats': typeof BarberStatsRouteWithChildren
  '/barber/subscription': typeof BarberSubscriptionRoute
  '/barber/withdrawals': typeof BarberWithdrawalsRoute
  '/independent/setup': typeof IndependentSetupRoute
  '/mybarber/setup': typeof MybarberSetupRoute
  '/salon/create': typeof SalonCreateRoute
  '/salon/join': typeof SalonJoinRouteWithChildren
  '/agent/': typeof AgentIndexRoute
  '/barber/': typeof BarberIndexRoute
  '/barber/bookings/$bookingId': typeof BarberBookingsBookingIdRouteWithChildren
  '/barber/salon-view/edit': typeof BarberSalonViewEditRoute
  '/barber/salon-view/gallery': typeof BarberSalonViewGalleryRoute
  '/barber/salon-view/members': typeof BarberSalonViewMembersRoute
  '/barber/salon-view/reviews': typeof BarberSalonViewReviewsRoute
  '/barber/salon-view/team': typeof BarberSalonViewTeamRoute
  '/barber/stats/graphs': typeof BarberStatsGraphsRoute
  '/salon/join/setup': typeof SalonJoinSetupRoute
  '/barber/salon-view/': typeof BarberSalonViewIndexRoute
  '/barber/stats/': typeof BarberStatsIndexRoute
  '/salon/join/': typeof SalonJoinIndexRoute
  '/barber/bookings/$bookingId/check-in': typeof BarberBookingsBookingIdCheckInRoute
  '/barber/bookings/$bookingId/session': typeof BarberBookingsBookingIdSessionRoute
  '/barber/bookings/$bookingId/': typeof BarberBookingsBookingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check-email': typeof CheckEmailRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/agent/aylanma': typeof AgentAylanmaRoute
  '/agent/invite': typeof AgentInviteRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/payout': typeof AgentPayoutRoute
  '/agent/salons': typeof AgentSalonsRoute
  '/barber/activation': typeof BarberActivationRoute
  '/barber/amenities': typeof BarberAmenitiesRoute
  '/barber/bookings': typeof BarberBookingsRouteWithChildren
  '/barber/calendar': typeof BarberCalendarRoute
  '/barber/chat': typeof BarberChatRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/earnings': typeof BarberEarningsRoute
  '/barber/expenses': typeof BarberExpensesRoute
  '/barber/goals': typeof BarberGoalsRoute
  '/barber/help': typeof BarberHelpRoute
  '/barber/inventory': typeof BarberInventoryRoute
  '/barber/invites': typeof BarberInvitesRoute
  '/barber/marketing': typeof BarberMarketingRoute
  '/barber/notifications': typeof BarberNotificationsRoute
  '/barber/portfolio': typeof BarberPortfolioRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/qr-pay': typeof BarberQrPayRoute
  '/barber/reviews': typeof BarberReviewsRoute
  '/barber/schedule': typeof BarberScheduleRoute
  '/barber/services': typeof BarberServicesRoute
  '/barber/settings': typeof BarberSettingsRoute
  '/barber/subscription': typeof BarberSubscriptionRoute
  '/barber/withdrawals': typeof BarberWithdrawalsRoute
  '/independent/setup': typeof IndependentSetupRoute
  '/mybarber/setup': typeof MybarberSetupRoute
  '/salon/create': typeof SalonCreateRoute
  '/agent': typeof AgentIndexRoute
  '/barber': typeof BarberIndexRoute
  '/barber/salon-view/edit': typeof BarberSalonViewEditRoute
  '/barber/salon-view/gallery': typeof BarberSalonViewGalleryRoute
  '/barber/salon-view/members': typeof BarberSalonViewMembersRoute
  '/barber/salon-view/reviews': typeof BarberSalonViewReviewsRoute
  '/barber/salon-view/team': typeof BarberSalonViewTeamRoute
  '/barber/stats/graphs': typeof BarberStatsGraphsRoute
  '/salon/join/setup': typeof SalonJoinSetupRoute
  '/barber/salon-view': typeof BarberSalonViewIndexRoute
  '/barber/stats': typeof BarberStatsIndexRoute
  '/salon/join': typeof SalonJoinIndexRoute
  '/barber/bookings/$bookingId/check-in': typeof BarberBookingsBookingIdCheckInRoute
  '/barber/bookings/$bookingId/session': typeof BarberBookingsBookingIdSessionRoute
  '/barber/bookings/$bookingId': typeof BarberBookingsBookingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/auth': typeof AuthRoute
  '/barber': typeof BarberRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/agent/aylanma': typeof AgentAylanmaRoute
  '/agent/invite': typeof AgentInviteRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/payout': typeof AgentPayoutRoute
  '/agent/salons': typeof AgentSalonsRoute
  '/barber/activation': typeof BarberActivationRoute
  '/barber/amenities': typeof BarberAmenitiesRoute
  '/barber/bookings': typeof BarberBookingsRouteWithChildren
  '/barber/calendar': typeof BarberCalendarRoute
  '/barber/chat': typeof BarberChatRoute
  '/barber/clients': typeof BarberClientsRoute
  '/barber/earnings': typeof BarberEarningsRoute
  '/barber/expenses': typeof BarberExpensesRoute
  '/barber/goals': typeof BarberGoalsRoute
  '/barber/help': typeof BarberHelpRoute
  '/barber/inventory': typeof BarberInventoryRoute
  '/barber/invites': typeof BarberInvitesRoute
  '/barber/marketing': typeof BarberMarketingRoute
  '/barber/notifications': typeof BarberNotificationsRoute
  '/barber/portfolio': typeof BarberPortfolioRoute
  '/barber/profile': typeof BarberProfileRoute
  '/barber/qr-pay': typeof BarberQrPayRoute
  '/barber/reviews': typeof BarberReviewsRoute
  '/barber/schedule': typeof BarberScheduleRoute
  '/barber/services': typeof BarberServicesRoute
  '/barber/settings': typeof BarberSettingsRoute
  '/barber/stats': typeof BarberStatsRouteWithChildren
  '/barber/subscription': typeof BarberSubscriptionRoute
  '/barber/withdrawals': typeof BarberWithdrawalsRoute
  '/independent/setup': typeof IndependentSetupRoute
  '/mybarber/setup': typeof MybarberSetupRoute
  '/salon/create': typeof SalonCreateRoute
  '/salon/join': typeof SalonJoinRouteWithChildren
  '/agent/': typeof AgentIndexRoute
  '/barber/': typeof BarberIndexRoute
  '/barber/bookings/$bookingId': typeof BarberBookingsBookingIdRouteWithChildren
  '/barber/salon-view/edit': typeof BarberSalonViewEditRoute
  '/barber/salon-view/gallery': typeof BarberSalonViewGalleryRoute
  '/barber/salon-view/members': typeof BarberSalonViewMembersRoute
  '/barber/salon-view/reviews': typeof BarberSalonViewReviewsRoute
  '/barber/salon-view/team': typeof BarberSalonViewTeamRoute
  '/barber/stats/graphs': typeof BarberStatsGraphsRoute
  '/salon/join/setup': typeof SalonJoinSetupRoute
  '/barber/salon-view/': typeof BarberSalonViewIndexRoute
  '/barber/stats/': typeof BarberStatsIndexRoute
  '/salon/join/': typeof SalonJoinIndexRoute
  '/barber/bookings/$bookingId/check-in': typeof BarberBookingsBookingIdCheckInRoute
  '/barber/bookings/$bookingId/session': typeof BarberBookingsBookingIdSessionRoute
  '/barber/bookings/$bookingId/': typeof BarberBookingsBookingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/auth'
    | '/barber'
    | '/check-email'
    | '/verify-email'
    | '/welcome'
    | '/agent/aylanma'
    | '/agent/invite'
    | '/agent/login'
    | '/agent/payout'
    | '/agent/salons'
    | '/barber/activation'
    | '/barber/amenities'
    | '/barber/bookings'
    | '/barber/calendar'
    | '/barber/chat'
    | '/barber/clients'
    | '/barber/earnings'
    | '/barber/expenses'
    | '/barber/goals'
    | '/barber/help'
    | '/barber/inventory'
    | '/barber/invites'
    | '/barber/marketing'
    | '/barber/notifications'
    | '/barber/portfolio'
    | '/barber/profile'
    | '/barber/qr-pay'
    | '/barber/reviews'
    | '/barber/schedule'
    | '/barber/services'
    | '/barber/settings'
    | '/barber/stats'
    | '/barber/subscription'
    | '/barber/withdrawals'
    | '/independent/setup'
    | '/mybarber/setup'
    | '/salon/create'
    | '/salon/join'
    | '/agent/'
    | '/barber/'
    | '/barber/bookings/$bookingId'
    | '/barber/salon-view/edit'
    | '/barber/salon-view/gallery'
    | '/barber/salon-view/members'
    | '/barber/salon-view/reviews'
    | '/barber/salon-view/team'
    | '/barber/stats/graphs'
    | '/salon/join/setup'
    | '/barber/salon-view/'
    | '/barber/stats/'
    | '/salon/join/'
    | '/barber/bookings/$bookingId/check-in'
    | '/barber/bookings/$bookingId/session'
    | '/barber/bookings/$bookingId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/check-email'
    | '/verify-email'
    | '/welcome'
    | '/agent/aylanma'
    | '/agent/invite'
    | '/agent/login'
    | '/agent/payout'
    | '/agent/salons'
    | '/barber/activation'
    | '/barber/amenities'
    | '/barber/bookings'
    | '/barber/calendar'
    | '/barber/chat'
    | '/barber/clients'
    | '/barber/earnings'
    | '/barber/expenses'
    | '/barber/goals'
    | '/barber/help'
    | '/barber/inventory'
    | '/barber/invites'
    | '/barber/marketing'
    | '/barber/notifications'
    | '/barber/portfolio'
    | '/barber/profile'
    | '/barber/qr-pay'
    | '/barber/reviews'
    | '/barber/schedule'
    | '/barber/services'
    | '/barber/settings'
    | '/barber/subscription'
    | '/barber/withdrawals'
    | '/independent/setup'
    | '/mybarber/setup'
    | '/salon/create'
    | '/agent'
    | '/barber'
    | '/barber/salon-view/edit'
    | '/barber/salon-view/gallery'
    | '/barber/salon-view/members'
    | '/barber/salon-view/reviews'
    | '/barber/salon-view/team'
    | '/barber/stats/graphs'
    | '/salon/join/setup'
    | '/barber/salon-view'
    | '/barber/stats'
    | '/salon/join'
    | '/barber/bookings/$bookingId/check-in'
    | '/barber/bookings/$bookingId/session'
    | '/barber/bookings/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/auth'
    | '/barber'
    | '/check-email'
    | '/verify-email'
    | '/welcome'
    | '/agent/aylanma'
    | '/agent/invite'
    | '/agent/login'
    | '/agent/payout'
    | '/agent/salons'
    | '/barber/activation'
    | '/barber/amenities'
    | '/barber/bookings'
    | '/barber/calendar'
    | '/barber/chat'
    | '/barber/clients'
    | '/barber/earnings'
    | '/barber/expenses'
    | '/barber/goals'
    | '/barber/help'
    | '/barber/inventory'
    | '/barber/invites'
    | '/barber/marketing'
    | '/barber/notifications'
    | '/barber/portfolio'
    | '/barber/profile'
    | '/barber/qr-pay'
    | '/barber/reviews'
    | '/barber/schedule'
    | '/barber/services'
    | '/barber/settings'
    | '/barber/stats'
    | '/barber/subscription'
    | '/barber/withdrawals'
    | '/independent/setup'
    | '/mybarber/setup'
    | '/salon/create'
    | '/salon/join'
    | '/agent/'
    | '/barber/'
    | '/barber/bookings/$bookingId'
    | '/barber/salon-view/edit'
    | '/barber/salon-view/gallery'
    | '/barber/salon-view/members'
    | '/barber/salon-view/reviews'
    | '/barber/salon-view/team'
    | '/barber/stats/graphs'
    | '/salon/join/setup'
    | '/barber/salon-view/'
    | '/barber/stats/'
    | '/salon/join/'
    | '/barber/bookings/$bookingId/check-in'
    | '/barber/bookings/$bookingId/session'
    | '/barber/bookings/$bookingId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRouteWithChildren
  AuthRoute: typeof AuthRoute
  BarberRoute: typeof BarberRouteWithChildren
  CheckEmailRoute: typeof CheckEmailRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WelcomeRoute: typeof WelcomeRoute
  IndependentSetupRoute: typeof IndependentSetupRoute
  MybarberSetupRoute: typeof MybarberSetupRoute
  SalonCreateRoute: typeof SalonCreateRoute
  SalonJoinRoute: typeof SalonJoinRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber': {
      id: '/barber'
      path: '/barber'
      fullPath: '/barber'
      preLoaderRoute: typeof BarberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/aylanma': {
      id: '/agent/aylanma'
      path: '/aylanma'
      fullPath: '/agent/aylanma'
      preLoaderRoute: typeof AgentAylanmaRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/invite': {
      id: '/agent/invite'
      path: '/invite'
      fullPath: '/agent/invite'
      preLoaderRoute: typeof AgentInviteRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/login': {
      id: '/agent/login'
      path: '/login'
      fullPath: '/agent/login'
      preLoaderRoute: typeof AgentLoginRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/payout': {
      id: '/agent/payout'
      path: '/payout'
      fullPath: '/agent/payout'
      preLoaderRoute: typeof AgentPayoutRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/salons': {
      id: '/agent/salons'
      path: '/salons'
      fullPath: '/agent/salons'
      preLoaderRoute: typeof AgentSalonsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/barber/': {
      id: '/barber/'
      path: '/'
      fullPath: '/barber/'
      preLoaderRoute: typeof BarberIndexRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/activation': {
      id: '/barber/activation'
      path: '/activation'
      fullPath: '/barber/activation'
      preLoaderRoute: typeof BarberActivationRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/amenities': {
      id: '/barber/amenities'
      path: '/amenities'
      fullPath: '/barber/amenities'
      preLoaderRoute: typeof BarberAmenitiesRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/bookings': {
      id: '/barber/bookings'
      path: '/bookings'
      fullPath: '/barber/bookings'
      preLoaderRoute: typeof BarberBookingsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/calendar': {
      id: '/barber/calendar'
      path: '/calendar'
      fullPath: '/barber/calendar'
      preLoaderRoute: typeof BarberCalendarRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/chat': {
      id: '/barber/chat'
      path: '/chat'
      fullPath: '/barber/chat'
      preLoaderRoute: typeof BarberChatRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/clients': {
      id: '/barber/clients'
      path: '/clients'
      fullPath: '/barber/clients'
      preLoaderRoute: typeof BarberClientsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/earnings': {
      id: '/barber/earnings'
      path: '/earnings'
      fullPath: '/barber/earnings'
      preLoaderRoute: typeof BarberEarningsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/expenses': {
      id: '/barber/expenses'
      path: '/expenses'
      fullPath: '/barber/expenses'
      preLoaderRoute: typeof BarberExpensesRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/goals': {
      id: '/barber/goals'
      path: '/goals'
      fullPath: '/barber/goals'
      preLoaderRoute: typeof BarberGoalsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/help': {
      id: '/barber/help'
      path: '/help'
      fullPath: '/barber/help'
      preLoaderRoute: typeof BarberHelpRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/inventory': {
      id: '/barber/inventory'
      path: '/inventory'
      fullPath: '/barber/inventory'
      preLoaderRoute: typeof BarberInventoryRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/invites': {
      id: '/barber/invites'
      path: '/invites'
      fullPath: '/barber/invites'
      preLoaderRoute: typeof BarberInvitesRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/marketing': {
      id: '/barber/marketing'
      path: '/marketing'
      fullPath: '/barber/marketing'
      preLoaderRoute: typeof BarberMarketingRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/notifications': {
      id: '/barber/notifications'
      path: '/notifications'
      fullPath: '/barber/notifications'
      preLoaderRoute: typeof BarberNotificationsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/portfolio': {
      id: '/barber/portfolio'
      path: '/portfolio'
      fullPath: '/barber/portfolio'
      preLoaderRoute: typeof BarberPortfolioRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/profile': {
      id: '/barber/profile'
      path: '/profile'
      fullPath: '/barber/profile'
      preLoaderRoute: typeof BarberProfileRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/qr-pay': {
      id: '/barber/qr-pay'
      path: '/qr-pay'
      fullPath: '/barber/qr-pay'
      preLoaderRoute: typeof BarberQrPayRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/reviews': {
      id: '/barber/reviews'
      path: '/reviews'
      fullPath: '/barber/reviews'
      preLoaderRoute: typeof BarberReviewsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/schedule': {
      id: '/barber/schedule'
      path: '/schedule'
      fullPath: '/barber/schedule'
      preLoaderRoute: typeof BarberScheduleRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/services': {
      id: '/barber/services'
      path: '/services'
      fullPath: '/barber/services'
      preLoaderRoute: typeof BarberServicesRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/settings': {
      id: '/barber/settings'
      path: '/settings'
      fullPath: '/barber/settings'
      preLoaderRoute: typeof BarberSettingsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/stats': {
      id: '/barber/stats'
      path: '/stats'
      fullPath: '/barber/stats'
      preLoaderRoute: typeof BarberStatsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/subscription': {
      id: '/barber/subscription'
      path: '/subscription'
      fullPath: '/barber/subscription'
      preLoaderRoute: typeof BarberSubscriptionRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/withdrawals': {
      id: '/barber/withdrawals'
      path: '/withdrawals'
      fullPath: '/barber/withdrawals'
      preLoaderRoute: typeof BarberWithdrawalsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/independent/setup': {
      id: '/independent/setup'
      path: '/independent/setup'
      fullPath: '/independent/setup'
      preLoaderRoute: typeof IndependentSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mybarber/setup': {
      id: '/mybarber/setup'
      path: '/mybarber/setup'
      fullPath: '/mybarber/setup'
      preLoaderRoute: typeof MybarberSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon/create': {
      id: '/salon/create'
      path: '/salon/create'
      fullPath: '/salon/create'
      preLoaderRoute: typeof SalonCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon/join': {
      id: '/salon/join'
      path: '/salon/join'
      fullPath: '/salon/join'
      preLoaderRoute: typeof SalonJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/bookings/$bookingId': {
      id: '/barber/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/barber/bookings/$bookingId'
      preLoaderRoute: typeof BarberBookingsBookingIdRouteImport
      parentRoute: typeof BarberBookingsRoute
    }
    '/barber/salon-view/': {
      id: '/barber/salon-view/'
      path: '/salon-view'
      fullPath: '/barber/salon-view/'
      preLoaderRoute: typeof BarberSalonViewIndexRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/salon-view/edit': {
      id: '/barber/salon-view/edit'
      path: '/salon-view/edit'
      fullPath: '/barber/salon-view/edit'
      preLoaderRoute: typeof BarberSalonViewEditRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/salon-view/gallery': {
      id: '/barber/salon-view/gallery'
      path: '/salon-view/gallery'
      fullPath: '/barber/salon-view/gallery'
      preLoaderRoute: typeof BarberSalonViewGalleryRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/salon-view/members': {
      id: '/barber/salon-view/members'
      path: '/salon-view/members'
      fullPath: '/barber/salon-view/members'
      preLoaderRoute: typeof BarberSalonViewMembersRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/salon-view/reviews': {
      id: '/barber/salon-view/reviews'
      path: '/salon-view/reviews'
      fullPath: '/barber/salon-view/reviews'
      preLoaderRoute: typeof BarberSalonViewReviewsRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/salon-view/team': {
      id: '/barber/salon-view/team'
      path: '/salon-view/team'
      fullPath: '/barber/salon-view/team'
      preLoaderRoute: typeof BarberSalonViewTeamRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/stats/': {
      id: '/barber/stats/'
      path: '/'
      fullPath: '/barber/stats/'
      preLoaderRoute: typeof BarberStatsIndexRouteImport
      parentRoute: typeof BarberStatsRoute
    }
    '/barber/stats/graphs': {
      id: '/barber/stats/graphs'
      path: '/graphs'
      fullPath: '/barber/stats/graphs'
      preLoaderRoute: typeof BarberStatsGraphsRouteImport
      parentRoute: typeof BarberStatsRoute
    }
    '/salon/join/': {
      id: '/salon/join/'
      path: '/'
      fullPath: '/salon/join/'
      preLoaderRoute: typeof SalonJoinIndexRouteImport
      parentRoute: typeof SalonJoinRoute
    }
    '/salon/join/setup': {
      id: '/salon/join/setup'
      path: '/setup'
      fullPath: '/salon/join/setup'
      preLoaderRoute: typeof SalonJoinSetupRouteImport
      parentRoute: typeof SalonJoinRoute
    }
    '/barber/bookings/$bookingId/': {
      id: '/barber/bookings/$bookingId/'
      path: '/'
      fullPath: '/barber/bookings/$bookingId/'
      preLoaderRoute: typeof BarberBookingsBookingIdIndexRouteImport
      parentRoute: typeof BarberBookingsBookingIdRoute
    }
    '/barber/bookings/$bookingId/check-in': {
      id: '/barber/bookings/$bookingId/check-in'
      path: '/check-in'
      fullPath: '/barber/bookings/$bookingId/check-in'
      preLoaderRoute: typeof BarberBookingsBookingIdCheckInRouteImport
      parentRoute: typeof BarberBookingsBookingIdRoute
    }
    '/barber/bookings/$bookingId/session': {
      id: '/barber/bookings/$bookingId/session'
      path: '/session'
      fullPath: '/barber/bookings/$bookingId/session'
      preLoaderRoute: typeof BarberBookingsBookingIdSessionRouteImport
      parentRoute: typeof BarberBookingsBookingIdRoute
    }
  }
}

interface AgentRouteChildren {
  AgentAylanmaRoute: typeof AgentAylanmaRoute
  AgentInviteRoute: typeof AgentInviteRoute
  AgentLoginRoute: typeof AgentLoginRoute
  AgentPayoutRoute: typeof AgentPayoutRoute
  AgentSalonsRoute: typeof AgentSalonsRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentAylanmaRoute: AgentAylanmaRoute,
  AgentInviteRoute: AgentInviteRoute,
  AgentLoginRoute: AgentLoginRoute,
  AgentPayoutRoute: AgentPayoutRoute,
  AgentSalonsRoute: AgentSalonsRoute,
  AgentIndexRoute: AgentIndexRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface BarberBookingsBookingIdRouteChildren {
  BarberBookingsBookingIdCheckInRoute: typeof BarberBookingsBookingIdCheckInRoute
  BarberBookingsBookingIdSessionRoute: typeof BarberBookingsBookingIdSessionRoute
  BarberBookingsBookingIdIndexRoute: typeof BarberBookingsBookingIdIndexRoute
}

const BarberBookingsBookingIdRouteChildren: BarberBookingsBookingIdRouteChildren =
  {
    BarberBookingsBookingIdCheckInRoute: BarberBookingsBookingIdCheckInRoute,
    BarberBookingsBookingIdSessionRoute: BarberBookingsBookingIdSessionRoute,
    BarberBookingsBookingIdIndexRoute: BarberBookingsBookingIdIndexRoute,
  }

const BarberBookingsBookingIdRouteWithChildren =
  BarberBookingsBookingIdRoute._addFileChildren(
    BarberBookingsBookingIdRouteChildren,
  )

interface BarberBookingsRouteChildren {
  BarberBookingsBookingIdRoute: typeof BarberBookingsBookingIdRouteWithChildren
}

const BarberBookingsRouteChildren: BarberBookingsRouteChildren = {
  BarberBookingsBookingIdRoute: BarberBookingsBookingIdRouteWithChildren,
}

const BarberBookingsRouteWithChildren = BarberBookingsRoute._addFileChildren(
  BarberBookingsRouteChildren,
)

interface BarberStatsRouteChildren {
  BarberStatsGraphsRoute: typeof BarberStatsGraphsRoute
  BarberStatsIndexRoute: typeof BarberStatsIndexRoute
}

const BarberStatsRouteChildren: BarberStatsRouteChildren = {
  BarberStatsGraphsRoute: BarberStatsGraphsRoute,
  BarberStatsIndexRoute: BarberStatsIndexRoute,
}

const BarberStatsRouteWithChildren = BarberStatsRoute._addFileChildren(
  BarberStatsRouteChildren,
)

interface BarberRouteChildren {
  BarberActivationRoute: typeof BarberActivationRoute
  BarberAmenitiesRoute: typeof BarberAmenitiesRoute
  BarberBookingsRoute: typeof BarberBookingsRouteWithChildren
  BarberCalendarRoute: typeof BarberCalendarRoute
  BarberChatRoute: typeof BarberChatRoute
  BarberClientsRoute: typeof BarberClientsRoute
  BarberEarningsRoute: typeof BarberEarningsRoute
  BarberExpensesRoute: typeof BarberExpensesRoute
  BarberGoalsRoute: typeof BarberGoalsRoute
  BarberHelpRoute: typeof BarberHelpRoute
  BarberInventoryRoute: typeof BarberInventoryRoute
  BarberInvitesRoute: typeof BarberInvitesRoute
  BarberMarketingRoute: typeof BarberMarketingRoute
  BarberNotificationsRoute: typeof BarberNotificationsRoute
  BarberPortfolioRoute: typeof BarberPortfolioRoute
  BarberProfileRoute: typeof BarberProfileRoute
  BarberQrPayRoute: typeof BarberQrPayRoute
  BarberReviewsRoute: typeof BarberReviewsRoute
  BarberScheduleRoute: typeof BarberScheduleRoute
  BarberServicesRoute: typeof BarberServicesRoute
  BarberSettingsRoute: typeof BarberSettingsRoute
  BarberStatsRoute: typeof BarberStatsRouteWithChildren
  BarberSubscriptionRoute: typeof BarberSubscriptionRoute
  BarberWithdrawalsRoute: typeof BarberWithdrawalsRoute
  BarberIndexRoute: typeof BarberIndexRoute
  BarberSalonViewEditRoute: typeof BarberSalonViewEditRoute
  BarberSalonViewGalleryRoute: typeof BarberSalonViewGalleryRoute
  BarberSalonViewMembersRoute: typeof BarberSalonViewMembersRoute
  BarberSalonViewReviewsRoute: typeof BarberSalonViewReviewsRoute
  BarberSalonViewTeamRoute: typeof BarberSalonViewTeamRoute
  BarberSalonViewIndexRoute: typeof BarberSalonViewIndexRoute
}

const BarberRouteChildren: BarberRouteChildren = {
  BarberActivationRoute: BarberActivationRoute,
  BarberAmenitiesRoute: BarberAmenitiesRoute,
  BarberBookingsRoute: BarberBookingsRouteWithChildren,
  BarberCalendarRoute: BarberCalendarRoute,
  BarberChatRoute: BarberChatRoute,
  BarberClientsRoute: BarberClientsRoute,
  BarberEarningsRoute: BarberEarningsRoute,
  BarberExpensesRoute: BarberExpensesRoute,
  BarberGoalsRoute: BarberGoalsRoute,
  BarberHelpRoute: BarberHelpRoute,
  BarberInventoryRoute: BarberInventoryRoute,
  BarberInvitesRoute: BarberInvitesRoute,
  BarberMarketingRoute: BarberMarketingRoute,
  BarberNotificationsRoute: BarberNotificationsRoute,
  BarberPortfolioRoute: BarberPortfolioRoute,
  BarberProfileRoute: BarberProfileRoute,
  BarberQrPayRoute: BarberQrPayRoute,
  BarberReviewsRoute: BarberReviewsRoute,
  BarberScheduleRoute: BarberScheduleRoute,
  BarberServicesRoute: BarberServicesRoute,
  BarberSettingsRoute: BarberSettingsRoute,
  BarberStatsRoute: BarberStatsRouteWithChildren,
  BarberSubscriptionRoute: BarberSubscriptionRoute,
  BarberWithdrawalsRoute: BarberWithdrawalsRoute,
  BarberIndexRoute: BarberIndexRoute,
  BarberSalonViewEditRoute: BarberSalonViewEditRoute,
  BarberSalonViewGalleryRoute: BarberSalonViewGalleryRoute,
  BarberSalonViewMembersRoute: BarberSalonViewMembersRoute,
  BarberSalonViewReviewsRoute: BarberSalonViewReviewsRoute,
  BarberSalonViewTeamRoute: BarberSalonViewTeamRoute,
  BarberSalonViewIndexRoute: BarberSalonViewIndexRoute,
}

const BarberRouteWithChildren =
  BarberRoute._addFileChildren(BarberRouteChildren)

interface SalonJoinRouteChildren {
  SalonJoinSetupRoute: typeof SalonJoinSetupRoute
  SalonJoinIndexRoute: typeof SalonJoinIndexRoute
}

const SalonJoinRouteChildren: SalonJoinRouteChildren = {
  SalonJoinSetupRoute: SalonJoinSetupRoute,
  SalonJoinIndexRoute: SalonJoinIndexRoute,
}

const SalonJoinRouteWithChildren = SalonJoinRoute._addFileChildren(
  SalonJoinRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRouteWithChildren,
  AuthRoute: AuthRoute,
  BarberRoute: BarberRouteWithChildren,
  CheckEmailRoute: CheckEmailRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WelcomeRoute: WelcomeRoute,
  IndependentSetupRoute: IndependentSetupRoute,
  MybarberSetupRoute: MybarberSetupRoute,
  SalonCreateRoute: SalonCreateRoute,
  SalonJoinRoute: SalonJoinRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
