import {
  Accessibility,
  AirVent,
  Armchair,
  Baby,
  Ban,
  Bath,
  BatteryCharging,
  Bike,
  Brush,
  Calendar,
  CalendarCheck,
  Camera,
  Car,
  Coffee,
  Cookie,
  CreditCard,
  CupSoda,
  Dog,
  DoorClosed,
  Droplets,
  Fan,
  Footprints,
  Gem,
  Gift,
  GraduationCap,
  Heart,
  Home,
  KeyRound,
  Languages,
  Moon,
  Music,
  Newspaper,
  Nfc,
  Puzzle,
  QrCode,
  Shirt,
  ShoppingBag,
  ShowerHead,
  Smartphone,
  Sofa,
  Sparkles,
  Sun,
  Sunrise,
  Thermometer,
  Ticket,
  Tv,
  User,
  Users,
  UsersRound,
  Wifi,
  Wind,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  wifi: Wifi,
  car: Car,
  "credit-card": CreditCard,
  "air-vent": AirVent,
  sofa: Sofa,
  coffee: Coffee,
  "calendar-check": CalendarCheck,
  sparkles: Sparkles,
  gem: Gem,
  baby: Baby,
  accessibility: Accessibility,
  tv: Tv,
  music: Music,
  "door-closed": DoorClosed,
  gift: Gift,
  "cup-soda": CupSoda,
  cookie: Cookie,
  droplets: Droplets,
  bath: Bath,
  dog: Dog,
  user: User,
  users: Users,
  calendar: Calendar,
  footprints: Footprints,
  moon: Moon,
  sunrise: Sunrise,
  home: Home,
  "key-round": KeyRound,
  bike: Bike,
  "battery-charging": BatteryCharging,
  newspaper: Newspaper,
  smartphone: Smartphone,
  thermometer: Thermometer,
  wind: Wind,
  ban: Ban,
  "shower-head": ShowerHead,
  brush: Brush,
  armchair: Armchair,
  puzzle: Puzzle,
  heart: Heart,
  camera: Camera,
  "shopping-bag": ShoppingBag,
  ticket: Ticket,
  "graduation-cap": GraduationCap,
  "users-round": UsersRound,
  nfc: Nfc,
  "qr-code": QrCode,
  fan: Fan,
  shirt: Shirt,
  languages: Languages,
  sun: Sun,
};

export function amenityIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Sparkles;
}
