"""Salon qulayliklari katalogi (50 ta). seed_amenities va API uchun."""

from __future__ import annotations

# (code, lucide_icon, {uz, ru, en})
AMENITY_CATALOG: list[tuple[str, str, dict[str, str]]] = [
    ("wifi", "wifi", {"uz": "Wi‑Fi", "ru": "Wi‑Fi", "en": "Wi‑Fi"}),
    ("parking", "car", {"uz": "Avtoturargoh", "ru": "Парковка", "en": "Parking"}),
    ("card_payment", "credit-card", {"uz": "Karta orqali to'lov", "ru": "Оплата картой", "en": "Card payment"}),
    ("air_conditioning", "air-vent", {"uz": "Konditsioner", "ru": "Кондиционер", "en": "Air conditioning"}),
    ("waiting_area", "sofa", {"uz": "Kutish zonasi", "ru": "Зона ожидания", "en": "Waiting area"}),
    ("coffee_tea", "coffee", {"uz": "Choy va kofe", "ru": "Чай и кофе", "en": "Coffee & tea"}),
    ("online_booking", "calendar-check", {"uz": "Onlayn bron", "ru": "Онлайн-запись", "en": "Online booking"}),
    ("sanitized_tools", "sparkles", {"uz": "Dezinfeksiya", "ru": "Стерильность", "en": "Sanitized tools"}),
    ("premium_products", "gem", {"uz": "Premium mahsulotlar", "ru": "Премиум средства", "en": "Premium products"}),
    ("kids_friendly", "baby", {"uz": "Bolalar uchun", "ru": "Для детей", "en": "Kids friendly"}),
    ("wheelchair", "accessibility", {"uz": "Imkoniyati cheklanganlar", "ru": "Доступная среда", "en": "Accessible"}),
    ("tv", "tv", {"uz": "Televizor", "ru": "ТВ", "en": "TV"}),
    ("music", "music", {"uz": "Musiqa", "ru": "Музыка", "en": "Music"}),
    ("private_room", "door-closed", {"uz": "Alohida xona", "ru": "Отдельная комната", "en": "Private room"}),
    ("loyalty_program", "gift", {"uz": "Bonus dasturi", "ru": "Бонусная программа", "en": "Loyalty program"}),
    ("cold_drinks", "cup-soda", {"uz": "Sovuq ichimliklar", "ru": "Холодные напитки", "en": "Cold drinks"}),
    ("snacks", "cookie", {"uz": "Yengil taomlar", "ru": "Закуски", "en": "Snacks"}),
    ("free_water", "droplets", {"uz": "Bepul suv", "ru": "Бесплатная вода", "en": "Free water"}),
    ("restroom", "bath", {"uz": "Hojatxona", "ru": "Туалет", "en": "Restroom"}),
    ("pet_friendly", "dog", {"uz": "Uy hayvonlari bilan", "ru": "Можно с питомцами", "en": "Pet friendly"}),
    ("women_only", "user", {"uz": "Faqat ayollar", "ru": "Только для женщин", "en": "Women only"}),
    ("men_only", "users", {"uz": "Faqat erkaklar", "ru": "Только для мужчин", "en": "Men only"}),
    ("appointment_only", "calendar", {"uz": "Faqat oldindan yozilish", "ru": "Только по записи", "en": "Appointment only"}),
    ("walk_in", "footprints", {"uz": "Navbat bilan kirish", "ru": "Без записи", "en": "Walk-in welcome"}),
    ("late_hours", "moon", {"uz": "Kechki ish vaqti", "ru": "Поздние часы", "en": "Late hours"}),
    ("early_hours", "sunrise", {"uz": "Erta ochiladi", "ru": "Раннее открытие", "en": "Early opening"}),
    ("home_service", "home", {"uz": "Uyga chiqish xizmati", "ru": "Выезд на дом", "en": "Home service"}),
    ("valet_parking", "key-round", {"uz": "Valet parkovka", "ru": "Валет-парковка", "en": "Valet parking"}),
    ("bicycle_parking", "bike", {"uz": "Velosiped uchun joy", "ru": "Велопарковка", "en": "Bicycle parking"}),
    ("ev_charging", "battery-charging", {"uz": "Elektr avto zaryad", "ru": "Зарядка для EV", "en": "EV charging"}),
    ("magazines", "newspaper", {"uz": "Jurnallar", "ru": "Журналы", "en": "Magazines"}),
    ("phone_charging", "smartphone", {"uz": "Telefon zaryadlash", "ru": "Зарядка телефона", "en": "Phone charging"}),
    ("climate_control", "thermometer", {"uz": "Iqlim nazorati", "ru": "Климат-контроль", "en": "Climate control"}),
    ("ventilated", "wind", {"uz": "Yaxshi shamollatiladi", "ru": "Вентиляция", "en": "Well ventilated"}),
    ("no_smoking", "ban", {"uz": "Chekish taqiqlangan", "ru": "Запрет курения", "en": "No smoking"}),
    ("hair_wash", "shower-head", {"uz": "Soch yuvish", "ru": "Мытьё головы", "en": "Hair wash"}),
    ("beard_station", "brush", {"uz": "Soqol parvarishi", "ru": "Уход за бородой", "en": "Beard care station"}),
    ("massage_chair", "armchair", {"uz": "Massaj kreslosi", "ru": "Массажное кресло", "en": "Massage chair"}),
    ("kids_play", "puzzle", {"uz": "Bolalar o'yin zonasi", "ru": "Детская зона", "en": "Kids play area"}),
    ("bridal_room", "heart", {"uz": "Kelin xonasi", "ru": "Комната для невесты", "en": "Bridal room"}),
    ("photo_zone", "camera", {"uz": "Foto zona", "ru": "Фотозона", "en": "Photo zone"}),
    ("product_shop", "shopping-bag", {"uz": "Mahsulotlar do'koni", "ru": "Магазин косметики", "en": "Product shop"}),
    ("gift_cards", "ticket", {"uz": "Sovg'a kartalari", "ru": "Подарочные карты", "en": "Gift cards"}),
    ("student_discount", "graduation-cap", {"uz": "Talabalar chegirmasi", "ru": "Скидка студентам", "en": "Student discount"}),
    ("senior_discount", "users-round", {"uz": "Keksalar chegirmasi", "ru": "Скидка пенсионерам", "en": "Senior discount"}),
    ("contactless_pay", "nfc", {"uz": "Kontaktsiz to'lov", "ru": "Бесконтактная оплата", "en": "Contactless payment"}),
    ("qr_payment", "qr-code", {"uz": "QR orqali to'lov", "ru": "Оплата по QR", "en": "QR payment"}),
    ("air_purifier", "fan", {"uz": "Havo tozalagich", "ru": "Очиститель воздуха", "en": "Air purifier"}),
    ("towels_provided", "shirt", {"uz": "Sochiq beriladi", "ru": "Полотенца", "en": "Towels provided"}),
    ("multilingual_staff", "languages", {"uz": "Ko'p tilli xodimlar", "ru": "Многоязычный персонал", "en": "Multilingual staff"}),
]

assert len(AMENITY_CATALOG) == 50
