"""Davlat nomi → ISO + bayroq emoji."""

from __future__ import annotations

COUNTRY_ISO: dict[str, str] = {
    "Uzbekistan": "UZ",
    "USA": "US",
    "USA/Canada": "US",
    "Canada": "CA",
    "Russia": "RU",
    "Germany": "DE",
    "France": "FR",
    "Japan": "JP",
    "United Kingdom": "GB",
    "China": "CN",
    "Italy": "IT",
    "Spain": "ES",
    "Turkey": "TR",
    "Netherlands": "NL",
    "Austria": "AT",
    "Australia": "AU",
    "New Zealand": "NZ",
    "Switzerland": "CH",
    "Sweden": "SE",
    "Norway": "NO",
    "Finland": "FI",
    "Denmark": "DK",
    "Belgium/Luxembourg": "BE",
    "Poland": "PL",
    "Ukraine": "UA",
    "Kazakhstan": "KZ",
    "Kyrgyzstan": "KG",
    "Tajikistan": "TJ",
    "Turkmenistan": "TM",
    "Azerbaijan": "AZ",
    "Georgia": "GE",
    "Armenia": "AM",
    "Belarus": "BY",
    "Moldova": "MD",
    "India": "IN",
    "Pakistan": "PK",
    "Indonesia": "ID",
    "Malaysia": "MY",
    "Thailand": "TH",
    "Vietnam": "VN",
    "Singapore": "SG",
    "South Korea": "KR",
    "North Korea": "KP",
    "Taiwan": "TW",
    "Hong Kong": "HK",
    "Macau": "MO",
    "Mongolia": "MN",
    "Cambodia": "KH",
    "Philippines": "PH",
    "Sri Lanka": "LK",
    "Iran": "IR",
    "Iraq": "IQ",
    "Saudi Arabia": "SA",
    "United Arab Emirates": "AE",
    "Kuwait": "KW",
    "Bahrain": "BH",
    "Qatar": "QA",
    "Jordan": "JO",
    "Lebanon": "LB",
    "Syria": "SY",
    "Egypt": "EG",
    "Libya": "LY",
    "Morocco": "MA",
    "Algeria": "DZ",
    "Tunisia": "TN",
    "Nigeria": "NG",
    "Kenya": "KE",
    "Ghana": "GH",
    "Senegal": "SN",
    "South Africa": "ZA",
    "Ivory Coast": "CI",
    "Tanzania": "TZ",
    "Mauritius": "MU",
    "Israel": "IL",
    "Cyprus": "CY",
    "Greece": "GR",
    "Bulgaria": "BG",
    "Romania": "RO",
    "Hungary": "HU",
    "Czech Republic": "CZ",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Croatia": "HR",
    "Serbia": "RS",
    "Bosnia and Herzegovina": "BA",
    "Montenegro": "ME",
    "North Macedonia": "MK",
    "Albania": "AL",
    "Malta": "MT",
    "Ireland": "IE",
    "Portugal": "PT",
    "Iceland": "IS",
    "Estonia": "EE",
    "Latvia": "LV",
    "Lithuania": "LT",
    "Mexico": "MX",
    "Brazil": "BR",
    "Argentina": "AR",
    "Chile": "CL",
    "Colombia": "CO",
    "Peru": "PE",
    "Uruguay": "UY",
    "Paraguay": "PY",
    "Bolivia": "BO",
    "Ecuador": "EC",
    "Venezuela": "VE",
    "Cuba": "CU",
    "Guatemala": "GT",
    "El Salvador": "SV",
    "Honduras": "HN",
    "Nicaragua": "NI",
    "Costa Rica": "CR",
    "Panama": "PA",
    "Dominican Republic": "DO",
}


def iso_for_country(name: str) -> str:
    return COUNTRY_ISO.get((name or "").strip(), "")


def flag_emoji(iso: str) -> str:
    code = (iso or "").strip().upper()
    if len(code) != 2 or not code.isalpha():
        return ""
    return "".join(chr(0x1F1E6 + ord(ch) - ord("A")) for ch in code)


def country_flag_payload(name: str) -> dict[str, str]:
    iso = iso_for_country(name)
    return {
        "country_name": name,
        "iso": iso,
        "flag": flag_emoji(iso),
        "flag_url": f"https://flagcdn.com/w80/{iso.lower()}.png" if iso else "",
    }
