# Generated by Django 6.0.3 on 2026-06-09 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiStyleHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ai-style/history/%Y/%m/')),
                ('face_shape_key', models.CharField(blank=True, default='', max_length=16)),
                ('hair_type_key', models.CharField(blank=True, default='', max_length=16)),
                ('source', models.CharField(choices=[('camera_scan', 'Camera scan'), ('gallery', 'Gallery'), ('ai_analysis', 'AI analysis')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_style_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_aistyleh_user_id_9072ce_idx')],
            },
        ),
    ]
