# Generated by Django 6.0.3 on 2026-06-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_ai_style_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('style_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, max_length=64)),
                ('audience', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], db_index=True, max_length=8)),
                ('category', models.CharField(choices=[('barber', 'Barber'), ('beauty', 'Beauty')], max_length=16)),
                ('title', models.CharField(max_length=120)),
                ('title_uz', models.CharField(max_length=120)),
                ('face_shapes', models.JSONField(default=list)),
                ('hair_length', models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], max_length=8)),
                ('image_path', models.CharField(max_length=255)),
                ('description_uz', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(default=list)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['audience', 'sort_order', 'style_id'],
                'constraints': [models.UniqueConstraint(fields=('audience', 'slug'), name='uniq_hairstyle_audience_slug')],
            },
        ),
    ]
