# Generated by Django 6.0.3 on 2026-07-13 21:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_seed_full_men_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiGenerationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tryon', 'Try-on'), ('analyze', 'Style analyze'), ('face_check', 'Face check')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('prompt', models.TextField(blank=True, default='')),
                ('style_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('style_title', models.CharField(blank=True, default='', max_length=120)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('job_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('candidates_tokens', models.PositiveIntegerField(default=0)),
                ('thoughts_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('tokens_estimated', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error_detail', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='ai_aigenera_kind_3a5f21_idx'), models.Index(fields=['user', '-created_at'], name='ai_aigenera_user_id_8867e3_idx'), models.Index(fields=['status', '-created_at'], name='ai_aigenera_status_bb9576_idx')],
            },
        ),
    ]
