# Generated by Django 6.0.3 on 2026-07-13 21:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_aigenerationusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorphAiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_tryon_limit_per_user', models.PositiveIntegerField(default=20, help_text="0 = cheklov yo'q. User uchun kunlik try-on limiti.")),
                ('daily_analyze_limit_per_user', models.PositiveIntegerField(default=30, help_text="0 = cheklov yo'q.")),
                ('daily_budget_usd', models.DecimalField(decimal_places=4, default=Decimal('50'), help_text="0 = byudjet cheklovi yo'q. Kunlik soft-cap (USD).", max_digits=12)),
                ('budget_enforce', models.BooleanField(default=False, help_text="True bo'lsa byudjet yetganda yangi generatsiya to'xtatiladi.")),
                ('alert_success_rate_below', models.PositiveSmallIntegerField(default=80, help_text="Success rate shu foizdan past bo'lsa ogohlantirish.")),
                ('tryon_enabled', models.BooleanField(default=True)),
                ('analyze_enabled', models.BooleanField(default=True)),
                ('custom_tryon_prompt', models.TextField(blank=True, default='', help_text="Bo'sh bo'lsa default prompt ishlatiladi.")),
                ('custom_tryon_prompt_b', models.TextField(blank=True, default='', help_text='A/B variant B prompti.')),
                ('ab_enabled', models.BooleanField(default=False)),
                ('ab_traffic_percent_b', models.PositiveSmallIntegerField(default=50, help_text="0–100. Variant B ga yo'naltiriladigan so'rovlar foizi.")),
                ('preferred_model', models.CharField(blank=True, default='', help_text="Bo'sh = env / Django settings modeli.", max_length=80)),
                ('gallery_public', models.BooleanField(default=False, help_text='Admin galleryda faqat opt-in tarix (hozir history yozuvlari).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Morph AI settings',
                'verbose_name_plural': 'Morph AI settings',
            },
        ),
    ]
