# Generated by Django 6.0.3 on 2026-09-05 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0031_careproduct_audience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareShelfItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("brand", models.CharField(blank=True, default="", max_length=80)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hair", "Soch"),
                            ("face", "Yuz"),
                            ("scalp", "Bosh terisi"),
                            ("beard", "Soqol"),
                            ("other", "Boshqa"),
                        ],
                        default="hair",
                        max_length=16,
                    ),
                ),
                ("volume_ml", models.PositiveIntegerField(default=100)),
                ("usage_frequency", models.CharField(default="kuniga_1", max_length=48)),
                ("uses_per_day", models.FloatField(default=1.0)),
                ("dose_ml_per_use", models.FloatField(default=1.0)),
                ("opened_at", models.DateField()),
                ("pao_months", models.PositiveSmallIntegerField(choices=[(3, "3M"), (6, "6M"), (12, "12M"), (24, "24M")], default=12)),
                ("ai_advice", models.CharField(blank=True, default="", max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shelf_items",
                        to="ai.careproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_shelf_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddIndex(
            model_name="careshelfitem",
            index=models.Index(fields=["user", "-updated_at"], name="ai_careshel_user_id_d80a5d_idx"),
        ),
        migrations.AddIndex(
            model_name="careshelfitem",
            index=models.Index(fields=["user", "opened_at"], name="ai_careshel_user_id_66fd7c_idx"),
        ),
        migrations.AddIndex(
            model_name="careshelfitem",
            index=models.Index(fields=["user", "pao_months"], name="ai_careshel_user_id_18710f_idx"),
        ),
    ]
