/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SalonViewRouteImport } from './routes/salon-view'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalonViewIndexRouteImport } from './routes/salon-view.index'
import { Route as SalonViewReviewsRouteImport } from './routes/salon-view.reviews'
import { Route as SalonViewGalleryRouteImport } from './routes/salon-view.gallery'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonViewRoute = SalonViewRouteImport.update({
  id: '/salon-view',
  path: '/salon-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonViewIndexRoute = SalonViewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalonViewRoute,
} as any)
const SalonViewReviewsRoute = SalonViewReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SalonViewRoute,
} as any)
const SalonViewGalleryRoute = SalonViewGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SalonViewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/salon-view': typeof SalonViewRouteWithChildren
  '/setup': typeof SetupRoute
  '/salon-view/gallery': typeof SalonViewGalleryRoute
  '/salon-view/reviews': typeof SalonViewReviewsRoute
  '/salon-view/': typeof SalonViewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/setup': typeof SetupRoute
  '/salon-view/gallery': typeof SalonViewGalleryRoute
  '/salon-view/reviews': typeof SalonViewReviewsRoute
  '/salon-view': typeof SalonViewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/salon-view': typeof SalonViewRouteWithChildren
  '/setup': typeof SetupRoute
  '/salon-view/gallery': typeof SalonViewGalleryRoute
  '/salon-view/reviews': typeof SalonViewReviewsRoute
  '/salon-view/': typeof SalonViewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/chat'
    | '/clients'
    | '/notifications'
    | '/profile'
    | '/reviews'
    | '/salon-view'
    | '/setup'
    | '/salon-view/gallery'
    | '/salon-view/reviews'
    | '/salon-view/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/chat'
    | '/clients'
    | '/notifications'
    | '/profile'
    | '/reviews'
    | '/setup'
    | '/salon-view/gallery'
    | '/salon-view/reviews'
    | '/salon-view'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/chat'
    | '/clients'
    | '/notifications'
    | '/profile'
    | '/reviews'
    | '/salon-view'
    | '/setup'
    | '/salon-view/gallery'
    | '/salon-view/reviews'
    | '/salon-view/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  ChatRoute: typeof ChatRoute
  ClientsRoute: typeof ClientsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReviewsRoute: typeof ReviewsRoute
  SalonViewRoute: typeof SalonViewRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon-view': {
      id: '/salon-view'
      path: '/salon-view'
      fullPath: '/salon-view'
      preLoaderRoute: typeof SalonViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon-view/': {
      id: '/salon-view/'
      path: '/'
      fullPath: '/salon-view/'
      preLoaderRoute: typeof SalonViewIndexRouteImport
      parentRoute: typeof SalonViewRoute
    }
    '/salon-view/reviews': {
      id: '/salon-view/reviews'
      path: '/reviews'
      fullPath: '/salon-view/reviews'
      preLoaderRoute: typeof SalonViewReviewsRouteImport
      parentRoute: typeof SalonViewRoute
    }
    '/salon-view/gallery': {
      id: '/salon-view/gallery'
      path: '/gallery'
      fullPath: '/salon-view/gallery'
      preLoaderRoute: typeof SalonViewGalleryRouteImport
      parentRoute: typeof SalonViewRoute
    }
  }
}

interface SalonViewRouteChildren {
  SalonViewGalleryRoute: typeof SalonViewGalleryRoute
  SalonViewReviewsRoute: typeof SalonViewReviewsRoute
  SalonViewIndexRoute: typeof SalonViewIndexRoute
}

const SalonViewRouteChildren: SalonViewRouteChildren = {
  SalonViewGalleryRoute: SalonViewGalleryRoute,
  SalonViewReviewsRoute: SalonViewReviewsRoute,
  SalonViewIndexRoute: SalonViewIndexRoute,
}

const SalonViewRouteWithChildren = SalonViewRoute._addFileChildren(
  SalonViewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  ChatRoute: ChatRoute,
  ClientsRoute: ClientsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReviewsRoute: ReviewsRoute,
  SalonViewRoute: SalonViewRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
