# Generated by Django 6.0.3 on 2026-04-02 20:12

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def dedupe_salon_names(apps, schema_editor):
    """Takroriy nomlarni (trim + lower bo‘yicha) noyob qilish — eski yozuvlar uchun."""
    Salon = apps.get_model("salons", "Salon")
    seen = {}
    for s in Salon.objects.all().order_by("id"):
        key = (s.name or "").strip().lower()
        if not key:
            continue
        if key in seen:
            base = (s.name or "").strip()
            s.name = f"{base} ({s.pk})"
            s.save(update_fields=["name"])
        else:
            seen[key] = s.id


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_salon_names, noop_reverse),
        migrations.AddConstraint(
            model_name="salon",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("name")
                ),
                name="salon_name_unique_ci_trim",
            ),
        ),
    ]
