# Generated by Django 6.0.3 on 2026-07-26 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_field_agent_referral'),
        ('salons', '0016_business_kind_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='referred_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_salons', to='agents.fieldagent'),
        ),
        migrations.AddField(
            model_name='salon',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('none', "Yo'q"), ('trial', 'Trial'), ('active', 'Faol'), ('expired', 'Tugagan')], db_index=True, default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='salon',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='trial_value_uzs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
