# Generated by Django 6.0.3 on 2026-07-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0017_drop_orphan_salon_type'),
        ('salons', '0017_field_agent_referral'),
    ]

    operations = [
    ]
